### PR TITLE
ADD: multisig for everyone

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3f7jx9q4ctjdy814225bw8gf5g

[download apk](http://filestorage.bluewallet.io:1488/1607380648.apk)

**Review by marcosrdz — APPROVED** [review]

**Review by limpbrains — APPROVED** [review]
🥳

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pffkpwxgrt28kwcmzcew90udxw

[download apk](http://filestorage.bluewallet.io:1488/1607728630.apk)

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mu16933jewy2zqpjnab7v9z32w

[download apk](http://filestorage.bluewallet.io:1488/1607891786.apk)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
