### PR TITLE
OPS: Update Camera Kit

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4pfkqxaozvtsugrwq6hdrnkd5i?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11640)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4ehfwfrflt2banquydpqa4rhju?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11641)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/lkoc2yycglbqtj7oujjjdt5e5i?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11642)

**Review by Overtorment — APPROVED** [review]

**Comment by Overtorment** [comment]
E2E failed

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

**Comment by marcosrdz** [comment]
> Reference

Can you help me figure out this issue? im able to complete the test locally

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ain2ywa4olog5odfzrm76idrqi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11658)

**Review by Overtorment — APPROVED** [review]
E2E failed

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

**Comment by Overtorment** [comment]
@marcosrdz 
looking at e2e logs, something bad happend when trying to tap backdoor button `ScanQrBackdoorButton`

try running the app and manually tapping that button, iirc its on the top left corner of opened camera screen.  5 taps should open a input box

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qkh74mskn3xjrew6zgzrfksnf4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11694)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/y5xrmb5xqyaq7uyrzlqlo5r2wq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11695)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

**Comment by Overtorment** [comment]
im looking into e2e

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/t3g26tq373mzc7sv5zykkwgdzq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11707)

**Comment by Overtorment** [comment]
https://github.com/teslamotors/react-native-camera-kit/issues/614

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gvhwq5vqjlbdmtwqbkr4ozysby?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11818)

**Pull request closed without merging**
