### PR TITLE
FIX: New tcp client lacked retries

### PR DESCRIPTION
**Pull request by marcosrdz**
## Release Notes

- **New Features**
  - Enhanced retry mechanisms for fetching market data and connection attempts, improving reliability in various scenarios.
  
- **Bug Fixes**
  - Improved error handling for connection failures and data reception errors.

- **Documentation**
  - Updated method signatures to reflect new parameters and functionality across various classes.

These updates collectively enhance the user experience by providing more reliable data fetching and connection handling capabilities.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
