### PR TITLE
REF: move all inline styles to StyleSheet.create 💅

### PR DESCRIPTION
**Pull request by limpbrains**
Related to #139

At first, I wanted to move only styles with 3 and more rules to static. But it still doesn't feel right.
So then I've discovered this nice [codemod](https://github.com/ignacioola/react-native-fix-inline-styles) and converted all the styles.

I understand this probably too much and you will want to exclude some screens from this patch, no problem.

Personally I prefer this style to be forced everywhere. It helps with readability of huge render functions. 

I haven't changed BlueComponents. They should be treated differently, each component probably should has it's own set of styles, not the global value.

Also, I've run `eslint --fix` on every file I've changed.

PS
I've found out that almost all usage of `SafeBlueArea` comes with `<SafeBlueArea style={{ flex: 1 }}>`. Probably I can make it default ?

### CODE REVIEW

**Comment by Overtorment** [comment]
is there a eslint rule to forbid inline styles?

**Comment by limpbrains** [comment]
> is there a eslint rule to forbid inline styles?

[eslint-plugin-react-native](https://github.com/Intellicode/eslint-plugin-react-native/blob/master/docs/rules/no-inline-styles.md) has what we need. Do you want me to add it to this PR ?

Also looks like I've missed a few files in root like App and UnlockWith

**Comment by Overtorment** [comment]
ok lets _not_ add extra dep

**Comment by Overtorment** [comment]
@marcosrdz can I get your blessing?

**Pull request merged**
