### PR TITLE
DEL: Obsolete DynamicQRCode

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9b8uwrrexm9f42c82kamhgqr3m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8253)

**Comment by jaonoctus** [comment]
Why this is obsolete?

**Comment by marcosrdz** [comment]
Its outdated. We moved it to the components folder and never removed it from BluComponents

**Review by jaonoctus — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by Overtorment** [comment]
its nice that we didnt have to amend e2e tests

**Pull request merged**
