### PR TITLE
FIX: If language is the selected one then disable row

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/drdjyenlfb2tstrki364knm5iq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1243)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — CHANGES_REQUESTED** [review]
`Expected '===' and instead saw '=='`

**Comment by marcosrdz** [comment]
> `Expected '===' and instead saw '=='`

Oops. Fixed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dfwxjgn5iawe27atgpo6aia5lm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1252)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
