### PR TITLE
FIX: Use merge:true when navigating to a previous screen

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xcsyhlsutuutmbj2ngzjb6r2re?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12186)

**Comment by Overtorment** [comment]
@marcosrdz i tested and changed how this merge parameter is passed, now it works.

btw, any ideas ho to find all `navigate()` calls which might actually need this `merge`parameter..?

**Comment by Overtorment** [comment]
plus, added some dirty fixes to UI to make e2e work on my specific android emulator

**Review by Overtorment — APPROVED** [review]

**Comment by marcosrdz** [comment]
> @marcosrdz i tested and changed how this merge parameter is passed, now it works.
> 
> 
> 
> btw, any ideas ho to find all `navigate()` calls which might actually need this `merge`parameter..?

I could be wrong but Its possible its just these two

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
