### PR TITLE
FIX:  Quorum modal, not possible to go back #2069

### PR DESCRIPTION
**Pull request by marcosrdz**
Simulator Screen Shot - iPhone 11 Pro - 2020-11-10 at 22 02 01

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wumxap3meb2z8mvf09myf5cx30

[download apk](http://filestorage.bluewallet.io:1488/1605065062.apk)

**Review by ncoelho — APPROVED** [review]

**Review by limpbrains — CHANGES_REQUESTED** [review]
Actually, `react-native-modal` supports `onBackButtonPress` I used it in coin control, works fine. I suggest remove Close button and add `onBackButtonPress` to be consistent.

Probably, it would be nice to add `onBackButtonPress` everywhere.

**Review by Overtorment — CHANGES_REQUESTED** [review]
agree with @limpbrains

**Comment by marcosrdz** [comment]
> agree with @limpbrains

Done

**Review by limpbrains — APPROVED** [review]

**Review by Overtorment — APPROVED** [review]
conflicts

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rqdkku6gje06fpydfh60w6ye5c

[download apk](http://filestorage.bluewallet.io:1488/1605116234.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/afhwy8qgrxdj03k2qkbzkmyukm

[download apk](http://filestorage.bluewallet.io:1488/1605141188.apk)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
