### PR TITLE
REF: Use our useTheme

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cxeqwzx354rj6j3r34qivz3qhi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11734)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/iyyjmwpyjgvdtnyvmkvfvfhwkm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11735)

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by Overtorment** [comment]
eh
image

**Comment by marcosrdz** [comment]
> eh
> 
> image
> 
> 

Mindlessly repeated changes

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
