### PR TITLE
FIX: Unhandled promise rejection on GC

### PR DESCRIPTION
**Pull request by marcosrdz**
## Release Notes

- **New Features**
	- Enhanced the `Notifications` module for better error handling and logging.
	- Improved `AddressInput` component with dynamic theming, clipboard access, and file/image handling.
  
- **Bug Fixes**
	- Added robust error handling in the `ReceiveDetails` component for obtaining wallet addresses and notification permissions.
  
- **Style**
	- Reformatted the `Button` component in the `Confirm` screen for improved readability.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
