### PR TITLE
FIX: Eliminate the need for a save button.

### PR DESCRIPTION
**Pull request by marcosrdz**
Follows modern HIGs

## Summary by CodeRabbit

- **New Features**
	- Enhanced coin management with new options for freezing and using coins.
	- Improved transaction details saving logic, ensuring data is saved when navigating away from the screen.

- **Bug Fixes**
	- Removed outdated strings related to transaction and wallet saving, streamlining user interface language.

- **Refactor**
	- Streamlined navigation header button logic for consistency across transaction-related screens.
	- Optimized the `TransactionDetails` component for better performance and clarity in saving transaction details.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
