### PR TITLE
OPS: RNDevice Info Update

### PR DESCRIPTION
**Pull request by marcosrdz**
windows support.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vmgfv6w707y61etfpb4m5q9fjm

[download apk](http://filestorage.bluewallet.io:1488/1607731879.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e20t873nz61fftk9bmja8880pr

[download apk](http://filestorage.bluewallet.io:1488/1607740215.apk)

**Review by Overtorment — APPROVED** [review]
why do we need this package? can we drop it?

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
