### PR TITLE
REF: navigation styles

### PR DESCRIPTION
**Pull request by limpbrains**
I was trying to fix this annoying react error

<details>
<summary>

```
Warning: React has detected a change in the order of Hooks called by StackNavigator. 
This will lead to bugs and errors if not fixed. For more information, 
read the Rules of Hooks: https://fb.me/rules-of-hooks
```

</summary>

```
Warning: React has detected a change in the order of Hooks called by StackNavigator. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://fb.me/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useState                   useState
2. useContext                 useContext
3. useEffect                  useEffect
4. useContext                 useContext
5. useRef                     useRef
6. useCallback                useCallback
7. useCallback                useCallback
8. useContext                 useContext
9. useMemo                    useMemo
10. useRef                    useRef
11. useEffect                 useEffect
12. useContext                useContext
13. useEffect                 useEffect
14. useEffect                 useEffect
15. useRef                    useRef
16. useCallback               useCallback
17. useRef                    useRef
18. useEffect                 useEffect
19. useRef                    useRef
20. useCallback               useCallback
21. useCallback               useCallback
22. useMemo                   useMemo
23. useContext                useContext
24. useRef                    useRef
25. useEffect                 useEffect
26. useEffect                 useEffect
27. useEffect                 useEffect
28. useEffect                 useEffect
29. useRef                    useRef
30. useCallback               useCallback
31. useRef                    useRef
32. useCallback               useCallback
33. useContext                useContext
34. useRef                    useRef
35. useEffect                 useEffect
36. useCallback               useCallback
37. useContext                useContext
38. useContext                useContext
39. useEffect                 useEffect
40. useEffect                 useEffect
41. useContext                useContext
42. useCallback               useCallback
43. useContext                useContext
44. useContext                useContext
45. useMemo                   useMemo
46. useContext                useContext
47. useCallback               useCallback
48. useEffect                 useEffect
49. useContext                useContext
50. useContext                useContext
51. useCallback               useCallback
52. useEffect                 useEffect
53. useState                  useState
54. useContext                useContext
55. useMemo                   useMemo
56. useMemo                   useMemo
57. useMemo                   useMemo
58. useContext                useContext
59. useEffect                 useContext
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    in StackNavigator (at Navigation.js:116)
    in WalletsRoot (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:222)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:221)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:190)
    in CardContainer (at CardStack.tsx:621)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:84)
    in MaybeScreen (at CardStack.tsx:614)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:54)
    in MaybeScreenContainer (at CardStack.tsx:496)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:34)
    in View (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at Navigation.js:344)
    in Navigation (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at ResourceSavingScene.tsx:58)
    in RCTView (at View.js:34)
    in View (at ResourceSavingScene.tsx:41)
    in ResourceSavingScene (at DrawerView.tsx:183)
    in RCTView (at View.js:34)
    in View (at src/index.native.js:139)
    in ScreenContainer (at DrawerView.tsx:162)
    in RCTView (at View.js:34)
    in View (at Drawer.tsx:645)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:240)
    in AnimatedComponent(View) (at Drawer.tsx:638)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:240)
    in AnimatedComponent(View) (at Drawer.tsx:628)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Drawer.tsx:619)
    in DrawerView (at DrawerView.tsx:215)
    in SafeAreaProviderCompat (at DrawerView.tsx:213)
    in RCTView (at View.js:34)
    in View (at DrawerView.tsx:212)
    in DrawerView (at createDrawerNavigator.tsx:47)
    in DrawerNavigator (at Navigation.js:290)
    in DrawerRoot (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:222)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:221)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:190)
    in CardContainer (at CardStack.tsx:621)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:84)
    in MaybeScreen (at CardStack.tsx:614)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:54)
    in MaybeScreenContainer (at CardStack.tsx:496)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:34)
    in View (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at Navigation.js:330)
    in InitRoot (at App.js:283)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at App.js:282)
    in RCTView (at View.js:34)
    in View (at App.js:281)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
    in SafeAreaProvider (at App.js:280)
    in App (at BlueWallet-orig/index.js:20)
    in BlueStorageProvider (at BlueWallet-orig/index.js:19)
    in BlueAppComponent (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
```

</details>

It turned out that it is because `useTheme` is used in a non react component function `BlueComponents.BlueNavigationStyle`. 

To solve this issue I suggest passing theme to screen options in `Navigation.js`. `createNavigationStyle` helper allows you to pass any additional arguments to screen options as before.

For now, I've only changed 2 screens: `Settings` and `WalletAdd`. 
@marcosrdz @Overtorment please take a look at this, if it is ok, I will migrate all the other screens.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9a3phjuya2a5cqfctgv31wnyj4

[download apk](http://filestorage.bluewallet.io:1488/1606916625.apk)

**Review by marcosrdz — APPROVED** [review]
Tested. works great.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9bra4395kuquuq2kp3vkj64hw0

[download apk](http://filestorage.bluewallet.io:1488/1606943621.apk)

**Comment by limpbrains** [comment]
> Tested. works great.

Thanks! I will start migrating all the other screens

**Review by Overtorment — APPROVED** [review]
i have no idea whats going on here but if @marcosrdz said its ok then lgtm

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4f9j8wkrn6gc6bzkh6gyx2twhc

[download apk](http://filestorage.bluewallet.io:1488/1607021220.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rgjd58g9m08qjj84bv1yu67peg

[download apk](http://filestorage.bluewallet.io:1488/1607065770.apk)

**Comment by limpbrains** [comment]
It is quite a big change and can probably break things
I've also refactored imports a little - external modules at first, then internal, I hope you don't mind

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/q5qk7bjqepn1mr0ccmzkbnrwrw

[download apk](http://filestorage.bluewallet.io:1488/1607077779.apk)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Comment by limpbrains** [comment]
@GladosBlueWallet bad bot!

**Comment by Overtorment** [comment]
unmerged in https://github.com/BlueWallet/BlueWallet/pull/2263

put labels DO NOT MERGE or WIP to prevent glados merges

**Comment by Overtorment** [comment]
pls redo the PR

**Pull request merged**
