### PR TITLE
FIX: Remove padding

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rqhrflfwpspril45644pczejea?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/150)

**Review by Overtorment — APPROVED** [review]

**Comment by Overtorment** [comment]
E2E failed & deepscan bitchin

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kbdne47bh4l44tlqi5cu4itrca?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/152)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/eowaaugqazfeftoxnxiypkpyqu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/176)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ma6m63csemwlef7fdyw6ypu7g4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/178)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
