### PR TITLE
FIX: OnePlus text cutoff

### PR DESCRIPTION
**Pull request by marcosrdz**
OnePlus offers custom fonts which breaks RN. The only solution that has worked is adding 2 whitespaces.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9fxrqbcayhz4dkdj3660ftpht8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7508)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by limpbrains — CHANGES_REQUESTED** [review]
I think we should separate string translation and representation.
If you change these strings, same changes should be replicated in all translations.
It is hard to explain people why 2 spaces are needed in certain strings.
It is better to add those spaces in JS.

**Comment by marcosrdz** [comment]
> I think we should separate string translation and representation.
> 
> If you change these strings, same changes should be replicated in all translations.
> 
> It is hard to explain people why 2 spaces are needed in certain strings.
> 
> It is better to add those spaces in JS. 

True. Ill make the changes

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by Overtorment** [comment]
@marcosrdz theres a "re-request review" button

**Comment by marcosrdz** [comment]
I gotta apply the changes mentioned by @limpbrains . Ill re-request his review in a few mins

**Comment by marcosrdz** [comment]
Done

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u8d0jpc56uu12gw29am6whp8gw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7529)

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
