### PR TITLE
ADD: IRT

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6aneemx0xn2xyd3u1h40h8pwt4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8408)

**Comment by mcsaeid** [comment]
The app does not show toman. Instead, it says “IRT.”
IRT

Compared to rial:
IRR

**Comment by marcosrdz** [comment]
@mcsaeid  that is because it follows the list provided by: 

https://en.wikipedia.org/wiki/ISO_4217

**Comment by mcsaeid** [comment]
I guess we can’t have everything haha.

It works okay.

**Pull request closed without merging**
