### PR TITLE
REF: Add mempool.space as the main explorer

### PR DESCRIPTION
**Pull request by ncoelho**

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/m2taexuru7b1rrjm0yv648fbp4

[download apk](http://filestorage.bluewallet.io:1488/mempool4win-1617982682.apk)

**Review by limpbrains — APPROVED** [review]

**Review by marcosrdz — APPROVED** [review]

**Review by jaonoctus — APPROVED** [review]

**Comment by softsimon** [comment]
utACK

**Comment by MiguelMedeiros** [comment]
Nice PR! 
I love the mempool.space UX! 
It deserved to be the default explorer! 👍

**Comment by wiz** [comment]
Hey guys, thanks for integrating with @mempool :heart:
We added a link to BlueWallet on [mempool.space/about](https://mempool.space/about) :)
Let us know anything else we can do for you.

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
