### PR TITLE
FIX: ecctests failing wallet creation

### PR DESCRIPTION
**Pull request by Serdnad**
Trying to import a wallet via seed phrase (and potentially other methods, I only tried with a phrase) fails due to an exception around `privateNegate` being undefined.

Adding the function back fixes this - let me know though if there's a better interface to throw this into than `TinySecp256k1InterfaceExtended`. I added it to this one because the other relevant types are imported from external libraries.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by Overtorment** [comment]
How to reproduce it? 
Import bip39 seed with a paraphrase option?

**Comment by Serdnad** [comment]
@Overtorment just importing a BIP39 seed, no password. This happens when running the current master branch on an Android emulator.

Reproduction video:

https://github.com/BlueWallet/BlueWallet/assets/4723453/30a36324-bca3-4427-9c86-50ff257ff694

**Comment by Overtorment** [comment]
Something is not right. That kind of bug would have been caught by a bunch of tests, including e2e test

**Comment by Serdnad** [comment]
That'd make sense, I was a bit surprised it hadn't already come up :). That was Android emulator on a Linux machine, I'll try setting up fresh and running in the iOS simulator on a mac and report back.

**Comment by Serdnad** [comment]
Hm that said, Typescript is reporting the lack of `privateNegate` as an actual problem. Is there a particular reason this function is commented out?

```
Argument of type 'TinySecp256k1InterfaceExtended & TinySecp256k1Interface & TinySecp256k1Interface' is not assignable to parameter of type 'TinySecp256k1Interface'.
  Property 'privateNegate' is missing in type 'TinySecp256k1InterfaceExtended & TinySecp256k1Interface & TinySecp256k1Interface' but required in type 'TinySecp256k1Interface'.
```

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by Overtorment** [comment]
i dont get this error. 
also, `npm run tslint && npm run lint`  is checked on CI for all PRs.

i dont remember why its commented out. probably because its not needed and was interfering with type definitions or smth

**Comment by limpbrains** [comment]
@Serdnad maybe you are using yarn? And it ignores npm package-lock.json?

**Comment by Serdnad** [comment]
@limpbrains ah yeah that might be it, I am using  yarn. I'll confirm later today.

**Comment by Serdnad** [comment]
Yeah, using `npm` instead of `yarn` caused the issue to go away. Thanks for helping me figure it out, guess I should've listened to the README better. I'll close this PR, since it doesn't seem like there's any real reason to add this function back.

**Pull request closed without merging**
