### PR TITLE
REF: Companion Delegates to TS hooks

### PR DESCRIPTION
**Pull request by marcosrdz**
## Summary by CodeRabbit

- **New Features**
	- Introduced a `CompanionDelegate` component for managing wallet functionalities and notifications.
	- Added a new notification management system with enhanced features.
	- Implemented custom hooks for managing app launch state and device quick actions.

- **Bug Fixes**
	- Improved error handling and state management in wallet-related components.
	- Enhanced notification handling to ensure better user experience.

- **Refactor**
	- Streamlined notification imports and handling across multiple components.
	- Transitioned lifecycle management to ensure better performance and memory management.
	- Updated various components to utilize new hooks for improved state management.

- **Documentation**
	- Added TypeScript declarations for `react-native-quick-actions` module.
	- Expanded localization strings for a better user experience.

### CODE REVIEW

**Comment by Overtorment** [comment]
been testing deeplinks against https://bluewallet.io/testpage/ found some bugs:


1)  `&message=` in deeplink is not recognized (but `&label=` is recognized ok, they are basically the same per BIP21)

2) when deeplinking to action `setelectrumserver`  in  server input box an extra `"` symbol appears for  no reason

3) when editing port for electrum server cant clean up the field, it resets to display `0`


mostly deeplinking works fine with BW

**Comment by Overtorment** [comment]
e2e failed btw

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by Overtorment** [comment]
mentioned bugs fixed?

**Comment by Overtorment** [comment]
e2e failed btw

**Pull request closed without merging**
