### PR TITLE
FIX: iOS icon

### PR DESCRIPTION
**Pull request by ncoelho**
fixes iOS icon borders and proper display for dark mode

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xkwpjqqr6na7m6jpyjurwazn7g

[download apk](http://filestorage.bluewallet.io:1488/1588672955.apk)

**Comment by Overtorment** [comment]
I think new icon has to be uploaded to itunesconnect manually to fix border issue

**Comment by ncoelho** [comment]
`This icon will be used on the App Store. For apps built with Xcode 9 or later, add this icon in the build. For apps built with earlier versions of Xcode, add the icon here`

From appstoreconnect

**Comment by ncoelho** [comment]
Tested with testflight and everything seems fine

**Pull request merged**
