### PR TITLE
Update build-ios-release-pullrequest.yml

### PR DESCRIPTION
**Pull request by marcosrdz**
## Summary by CodeRabbit

- **Chores**
	- Streamlined iOS release workflow by removing caching steps for Ruby gems.
	- Updated artifact handling to ensure consistent naming conventions across jobs.
	- Enhanced upload processes for IPA and Bugsnag sourcemaps with dynamic references.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
