### PR TITLE
REF: speedup multisig creation (closes #2097)

### LINKED ISSUE #2097: Multisig creation on android is slow
Multisig creation on android is slow. The device enters in rest mode before the multisig creation finishes.

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by Overtorment** [comment]
@ncoelho I speeded up multisig a bit. saves about 2 sec per each mnemonic cosigner when user presses CREATE button.
there are ways to speed it up a bit more, but its more invasive, so maybe this will do for now

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xn72v6wqbcv3uz2yw1hcwqaxwc

[download apk](http://filestorage.bluewallet.io:1488/1605292566.apk)

**Comment by ncoelho** [comment]
Will test!

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
