### PR TITLE
Fix fs save and open android

### PR DESCRIPTION
**Pull request by Overtorment**
Actual change is in the first commit, the second commit is converting to ts, cleanup, remove unused function

### CODE REVIEW

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/crtetkxjjsohp4f5rtybdjnoxi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/186)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zb2uxy6y3gruuub66cavqxte7a?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/187)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
