### PR TITLE
FIX: Currency preference is not permanent #7365

### PR DESCRIPTION
**Pull request by marcosrdz**
## Summary by CodeRabbit

- **New Features**
	- Improved handling of preferred currency settings for a more streamlined user experience.
	- Enhanced display of total balance reflecting the user's preferred fiat currency.

- **Bug Fixes**
	- Resolved issues with currency setting and retrieval, ensuring default values are correctly applied.

- **Refactor**
	- Simplified logic for managing and displaying currency preferences, improving code clarity and efficiency.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by Overtorment** [comment]
integration tests failed tho

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
