### PR TITLE
ADD: Script to remove a passed key from all locale JSON files

### PR DESCRIPTION
**Pull request by marcosrdz**
./scripts/remove-loc-key.sh invalid_animated_qr_code_fragment 

or

./scripts/remove-loc-key.sh entropy.save

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ypxd63csln5lylzzoiqwhvsnee?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12230)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
not sure,but i think its enough  to remove key from en.json only, and transifex wil update all langs later. @limpbrains is it how it is?

**Comment by marcosrdz** [comment]
> not sure,but i think its enough to remove key from en.json only, and transifex wil update all langs later. @limpbrains is it how it is?

not sure but Ive seen some orphan strings in other JSON files. having this script will let u remove it from every JSON immediately on the same PR as the changes you're making.

**Comment by limpbrains** [comment]
It would be shorter to write it in js.
Yes, you don't need to manually remove old lines, they will be removed with next language sync, but it will save a few bytes if you do it before, so why not

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
