### PR TITLE
REF: Use a better QR image decoder

### PR DESCRIPTION
**Pull request by marcosrdz**
## Release Notes

- **New Features**
  - Enhanced QR code detection capabilities using the `rn-qr-generator` library.
  - Added support for pasting from clipboard in various components, improving user interaction.

- **Bug Fixes**
  - Improved error handling for QR code detection and clipboard operations.

- **Localization Updates**
  - Updated terminology across multiple languages for clarity, specifically changing references from "copy from clipboard" to "paste from clipboard."

- **Documentation**
  - Enhanced user guidance and error messages in the application for better user experience.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
