### PR TITLE
FIX:  Android: 'Leave us a review' button becomes unresponsive #3577

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0v7gub88j7d2mcw3wv0qdnv7g8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7749)

**Review by brettl-03 — APPROVED** [review]
Test passes: the "Leave us a review" button becoming unresponsive is fixed with this change 
- Tapping on the "Leave us a review" button now opens the BlueWallet product page within the Google Play Store every time it's tapped/pressed, and the button remains responsive.

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
