### PR TITLE
OPS: Apply remaining patches for Catalyst without the need for forks

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1ftvpd9m7g5xucnf83cy8q4b08

[download apk](http://filestorage.bluewallet.io:1488/1605496585.apk)

**Review by limpbrains — APPROVED** [review]
@marcosrdz I'am curious, why patches are better than forks?

**Comment by marcosrdz** [comment]
> @marcosrdz I'am curious, why patches are better than forks? 

The goal is to be as close to master as possible. Having forks means we have to keep up with those package's upstream if the version on master's package.json changes.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n4tyzuxrczpybd2vr2v808t9nw

[download apk](http://filestorage.bluewallet.io:1488/1605638425.apk)

**Review by Overtorment — APPROVED** [review]
lgtm.
also, is there some kind of signaling to know that patching failed? this might happen if dependency is updated by accident.

**Comment by marcosrdz** [comment]
> lgtm.
> 
> also, is there some kind of signaling to know that patching failed? this might happen if dependency is updated by accident.

It shows "patching failed" and lets you know which one failed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xqx7c6t7xpc0xb2h4b34v8qmuw

[download apk](http://filestorage.bluewallet.io:1488/1605715736.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x6uj0uuwpxyfhc357m7m2t32pw

[download apk](http://filestorage.bluewallet.io:1488/1605804331.apk)

**Pull request merged**
