### PR TITLE
ADD: Trader Main view component - Static layout

### PR DESCRIPTION
**Pull request by ncoelho**
1st iteration of the Local Trader component on the main view

<image src="https://user-images.githubusercontent.com/1238429/78703811-27598200-790b-11ea-89fb-eb2434150738.png" width="320px">

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vtbyhc3047uuvzfu9r92djb494

[download apk](http://filestorage.bluewallet.io:1488/1586288941.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nuaxvwrwdxgwxbxbbte8uvdggg

[download apk](http://filestorage.bluewallet.io:1488/1586346512.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/favwyajrr44w5puvx2daztn1wg

[download apk](http://filestorage.bluewallet.io:1488/1586351912.apk)

**Comment by Overtorment** [comment]
cleanup

**Pull request closed without merging**
