### PR TITLE
REF: remove assert dependency

### PR DESCRIPTION
**Pull request by limpbrains**
Looks like assert is still should be in package.json, because blue_modules/bip38 is still using it.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/axkzpuqxhapex2e6w65wkmg3xg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7416)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/g2dyw38n1n851r0cf3bjqkwkew?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7417)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rmqtqvjpj9vzxdggtte0b18kzw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7418)

**Comment by Overtorment** [comment]
afair `assert` is bundled with nodejs so there's no need to fix all tests to use `expect`..?

**Comment by limpbrains** [comment]
It doesn't seem like a good idea to me anymore

**Pull request closed without merging**
