### PR TITLE
FIX: Set '0.' on BTC Amount

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3a4m7tkqx9nwtp4e3qgyj1mhtg

[download apk](http://filestorage.bluewallet.io:1488/1605146775.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by Overtorment** [comment]
if you start typing with dot, secondary amount will render NaN
image

**Review by Overtorment — CHANGES_REQUESTED** [review]
NaN in secondary

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1uv2zckzuwp6ehb7mmwgb1qcr4

[download apk](http://filestorage.bluewallet.io:1488/1605192261.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8zb8k6b1wnma2pqhzt4ky3myag

[download apk](http://filestorage.bluewallet.io:1488/1605196400.apk)

**Comment by Overtorment** [comment]
is the problem with NaN solved? cause I open last appetize, create a wallet, tap send, type '.' and get NaN

**Review by Overtorment — CHANGES_REQUESTED** [review]
NaN

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zc04gw2trwzn83enbwyhttaf5m

[download apk](http://filestorage.bluewallet.io:1488/1605307170.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z9zw8hb4yx43jzcwg4dhcbqw1c

[download apk](http://filestorage.bluewallet.io:1488/1605326780.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cmwbp97nx0n7yamvar7thjbngm

[download apk](http://filestorage.bluewallet.io:1488/1605327624.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7w8u7ehyve6cyb1x06fc74x368

[download apk](http://filestorage.bluewallet.io:1488/1605370462.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6akftkd2ju8xk55ctemh188aew

[download apk](http://filestorage.bluewallet.io:1488/1605415301.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jqxnu3fg5dua86xgct15a25mdr

[download apk](http://filestorage.bluewallet.io:1488/1605459258.apk)

**Review by Overtorment — APPROVED** [review]
tested on appetize, lgtm

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
