### PR TITLE
REF: Use Switch for SSL Electrum port

### PR DESCRIPTION
**Pull request by marcosrdz**
simulator_screenshot_0F5FF814-6AE2-4433-90FC-0EA3884C4E76

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/25dv6juhmhw24uvz7b1t4q9njg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7210)

**Review by Overtorment — CHANGES_REQUESTED** [review]
tested on appetize. 
bug: tcp port doesnt persist when saving, going a screen back and forth. input is not filled

otherwise works as expected

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xgu36yqhtzm5m8raazjbp1g7xc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7230)

**Review by Overtorment — APPROVED** [review]
lgtm.
@ncoelho your word

**Comment by ncoelho** [comment]
When you open the app SSL is deactivated be default. Does that make sense?

Screenshot 2021-07-07 at 17 28 43

**Comment by marcosrdz** [comment]
Thats cause theres no specific server saved thus no sslPort data which leads to an off state. We could have it on by default

**Review by ncoelho — APPROVED** [review]

**Comment by Overtorment** [comment]
default could be  'disabled' since all other fields are empty as well

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
