### PR TITLE
Fix fee and add vault translation in Finnish

### PR DESCRIPTION
**Pull request by tlindi**

### CODE REVIEW

**Comment by limpbrains** [comment]
Thank you for the contribution, please join us at [Transifex](https://www.transifex.com/bluewallet/bluewallet/) to work on translation. There are about 100 more untranslated Finnish string

**Comment by tlindi** [comment]
> Thank you for the contribution, please join us at [Transifex](https://www.transifex.com/bluewallet/bluewallet/) to work on translation. There are about 100 more untranslated Finnish string

I noticed there was some issues to overwrite already made translations...

Would it be more convenient for you and sure way to get translations to release?

**Comment by limpbrains** [comment]
To edit strings you need Reviewer rights. Currently [Biocycle](https://www.transifex.com/user/profile/Biocycle/) has them. 
I think it is better if you write him so you two can come to consensus about which translation to use.
Editing Transifex is more convenient way to contribute to BlueWallet translations than github PR.

**Comment by tlindi** [comment]
I see. I wrote to him. 

To me transiflex is yet one more system to use, so I'd prefer PR's.

**Comment by tlindi** [comment]
> Thank you for the contribution, please join us at [Transifex](https://www.transifex.com/bluewallet/bluewallet/) to work on translation. There are about 100 more untranslated Finnish string

Translated all of them there.

**Comment by limpbrains** [comment]
> > Thank you for the contribution, please join us at [Transifex](https://www.transifex.com/bluewallet/bluewallet/) to work on translation. There are about 100 more untranslated Finnish string
> 
> Translated all of them there.

Nice!
It will be in next BW release #4470

**Pull request closed without merging**
