### PR TITLE
Add more segwit v1 tests

### PR DESCRIPTION
**Pull request by junderw**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dbv4x7xhjemy21txvvzm4v4fxc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9186)

**Comment by Overtorment** [comment]
thanks, I missed this PR and added same directly to master:

https://github.com/BlueWallet/BlueWallet/commit/3195977a0e5176b395f5358b91e8dbfa7327cda1

**Comment by dwg868** [comment]
If you please call me 586-525-8684

**Comment by dwg868** [comment]
Incredibly Successful

**Comment by dwg868** [comment]
I would very much enjoy Sitting and meeting you in person

**Pull request closed without merging**
