### PR TITLE
fix: import discovery ts

### PR DESCRIPTION
**Pull request by limpbrains**
## Summary by CodeRabbit

- **New Features**
	- Enhanced wallet import functionality with clearer promise resolution and status tracking.
  
- **Bug Fixes**
	- Improved type handling for wallet import tasks, ensuring better error management and user feedback.

- **Documentation**
	- Updated type definitions for wallet import processes to reflect changes in the underlying structure.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n7ymokjokii6tobqrmxor7g5he?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1138)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/larshl67c34sng53zqtnio6mrm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1850)

**Comment by Overtorment** [comment]
@limpbrains lets finalize it? whats left?

**Comment by limpbrains** [comment]
Just small leftovers from my original PR

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
