### PR TITLE
FIX: set fee to lower value if balance is not enought

### LINKED ISSUE #1799: Fee should have in consideration user balance
Fee suggestion shouldn't not suggest a bigger amount that what is possible for the wallet to send (bigger than current balance)

### PR DESCRIPTION
**Pull request by limpbrains**
Closes #1799

If balance is not enough even for Slow option, 1 sat/byte will be used

https://user-images.githubusercontent.com/155891/106481874-ef38b680-64bd-11eb-885f-b18121087599.mov

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rqh3cjhzfmph7r2kpkbkbbpeyc

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-fee-low-balance-1612196176.apk)

**Review by Overtorment — APPROVED** [review]
are `lgtm-com bot` complains addressed..?

**Comment by limpbrains** [comment]
> are `lgtm-com bot` complains addressed..?

Yes, I've fixed them

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gtfxv76ndxdh26agcf60bn7p38

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-fee-low-balance-1612197720.apk)

**Review by ncoelho — APPROVED** [review]

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
