### PR TITLE
REF: Latest package supports function on both OS

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — CHANGES_REQUESTED** [review]
so if both platforms now support `hasImage`, you dont need a platform `if` at all?
cause code looks idiotic now

**Comment by marcosrdz** [comment]
> so if both platforms now support `hasImage`, you dont need a platform `if` at all?
> 
> cause code looks idiotic now

hasImage is iOS only. GetImage used to be Android only.

**Comment by marcosrdz** [comment]
> so if both platforms now support `hasImage`, you dont need a platform `if` at all?
> 
> cause code looks idiotic now

hasImage on iOS checks the clipboard data type without triggering the alert. If it matches an image then hasImage = true

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
