### PR TITLE
ADD: Scan tooltip

### PR DESCRIPTION
**Pull request by marcosrdz**
press and hold to see menu so u dont have to load the scanner to access features

Screenshot 2024-05-25 at 12 56 51 PM

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/atdz4mkf5facgwvenf5bmzn6wu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1743)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/y5fwnwqn46dpvvh4nb6ueq2cxm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1744)

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
