### PR TITLE
FIX: Update details UI to match design

### PR DESCRIPTION
**Pull request by marcosrdz**
https://www.figma.com/file/4uQl30azjeFvexPhDergH7/pending?node-id=9%3A206

Simulator Screen Shot - iPhone 12 - 2021-09-05 at 13 34 15

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fm53ep68nff0tuhz3jyekdgfeg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8139)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8zev25dpbg2jkwpkeb7q17f5qm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8147)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4ky84t37q175nu2gga8r5ck3p8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8152)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ak8zhuc08enf751y45afd36ftm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8157)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
