### PR TITLE
TST: wallet details tests

### LINKED ISSUE #1908: e2e: bip84 -> wallet details -> check all subscreens (export, xpub etc)

### PR DESCRIPTION
**Pull request by limpbrains**
closes #1908 #2694 #2695

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/201tvpkh29jhjwfeew3ee2qgf4

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-test-walletdetails-1614693624.apk)

**Review by Overtorment — CHANGES_REQUESTED** [review]
lgtm, except travis e2e fails

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4pu0q8thxm731cc4v4vh5gc018

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-test-walletdetails-1614843110.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/r09kkkbx8aq2t0nk4hvg810ahc

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-test-walletdetails-1614852043.apk)

**Comment by limpbrains** [comment]
@Overtorment merge it, it's ready

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
