### PR TITLE
ADD: CoinGecko

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]

**Comment by Overtorment** [comment]
Do CHF if coingexko has it

**Comment by marcosrdz** [comment]
> Do CHF if coingexko has it

done

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ifsb5ik5jcarldgwh5haaketpi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11103)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2oedmvplynbw2fmypmzthe5kda?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11105)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
