### PR TITLE
ci(travis): check if installing libxcursor helps

### PR DESCRIPTION
**Pull request by noomorph**
See https://github.com/wix/Detox/issues/1995

### CODE REVIEW

**Comment by Overtorment** [comment]
@noomorph дякую! but you didn't up detox version (master still has 16.0.0). i ported your changes to https://github.com/BlueWallet/BlueWallet/pull/951 lets see if it helps

**Comment by noomorph** [comment]
@Overtorment, будь ласка! This pull request targets not `master` but your 'test-detox-upgrade` branch, so I think I should not have up'ed detox version in this case.

**Comment by Overtorment** [comment]
oh okay! anyway, tests passed on both PRs, which is good news!

**Comment by Overtorment** [comment]
closing in favor of https://github.com/BlueWallet/BlueWallet/pull/951

**Pull request closed without merging**
