### PR TITLE
Update Android build instructions

### PR DESCRIPTION
**Pull request by bolatovumar**
address #759

### CODE REVIEW

**Comment by Overtorment** [comment]
Thanks!

**Comment by Overtorment** [comment]
So did you and @marcosrdz get to the bottom of it? 
I usually run `npm start` and leave it hanging. And while it runs I launch `npm run android`

**Comment by marcosrdz** [comment]
@Overtorment  this process changed fairly recently. RN now uses npx, which explains why the instructions in place were not working.

**Comment by Overtorment** [comment]
Isn’t npx just a shortcut to “npm run” ?

**Comment by marcosrdz** [comment]
idk the specifics but it’s like npm run without installing the package locally.

**Comment by Overtorment** [comment]
It runs it from local node modules

**Comment by bolatovumar** [comment]
@Overtorment `npx` allows you to run a package that's in your local `node_modules` folder without having to install it globally or do an `npm run <command-name>`

**Pull request merged**
