### PR TITLE
REF: swap tiny-secp256k1 for noble-secp256k1

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/niuzux5ngaimp42higblxhw2lm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10550)

**Comment by Overtorment** [comment]
apparently, need RN70 for BigInt to work

**Comment by Overtorment** [comment]
ok, migrated to RN 70+

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rctfcrzyvzi4yvexizyxqjxadq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11152)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5boyznyrqfv2kne2ws5nyanc5i?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11153)

**Comment by Overtorment** [comment]
wow, performance if off the charts

image

image

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zolaribhothep4aq37rzt57yja?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11158)

**Review by junderw — APPROVED** [review]
noble is a great library, and using BigInt will greatly increase performance (and security) over the `elliptic` package we used in v1 for JS.

utACK

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4sa4gy5loswoglghngyotgmdam?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11168)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
