### PR TITLE
Fileimport

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qrkvffjf7fm3z3aymye457be7r

[download apk](http://filestorage.bluewallet.io:1488/1604705928.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6awt2vw6n01k1rpevvwr2qdnwg

[download apk](http://filestorage.bluewallet.io:1488/1604718788.apk)

**Comment by ncoelho** [comment]
Is this updated @marcosrdz ?

**Comment by marcosrdz** [comment]
> Is this updated @marcosrdz ?

Yup

**Review by Overtorment — APPROVED** [review]

**Pull request merged**
