### PR TITLE
FIX: Modal on iOS

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k8tb7rm0exf4zh0jq295wmb9wg

[download apk](http://filestorage.bluewallet.io:1488/1601052797.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/m5u823185yd96xhfmjy39wg84r

[download apk](http://filestorage.bluewallet.io:1488/1601054044.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f9mu7dfggrxvpcxr77cymxkv30

[download apk](http://filestorage.bluewallet.io:1488/1601055924.apk)

**Review by Overtorment — APPROVED** [review]
Lgtm

**Review by ncoelho — APPROVED** [review]

**Pull request merged**
