### PR TITLE
FIX: Dont use SafeAreaView on non-macOS

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uh2mf0my199kqpgrnw9nzk08u8

[download apk](http://filestorage.bluewallet.io:1488/1609618800.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mhjzbx2tm44mhjjtka3xdqdcrm

[download apk](http://filestorage.bluewallet.io:1488/1609692586.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0kpv1h94ujcr90azugv6dh9vdr

[download apk](http://filestorage.bluewallet.io:1488/1609707125.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by Overtorment** [comment]
e2e fails

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6bgequaz0w8wkhpadzudubc8cg

[download apk](http://filestorage.bluewallet.io:1488/1609776310.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hh2ck4ct0wfmbwjvgt8jmqew24

[download apk](http://filestorage.bluewallet.io:1488/1609791044.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k0wqgty2efc7c8rk8cxncuk7z8

[download apk](http://filestorage.bluewallet.io:1488/1609811872.apk)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
