### PR TITLE
FIX: Update drawer view for nav 6

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/baavfnfdyn7po2pzuqg5huteiy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11915)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u2jgckktyict7lw73reipre65q?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11916)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z7z2wz74gsnzeuwarob56iqcbi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11917)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/irkqtche4ae2iiabxsw6w7tvkm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11918)

**Review by Overtorment — APPROVED** [review]

**Pull request merged**
