### PR TITLE
[Snyk] Upgrade metro-react-native-babel-preset from 0.63.0 to 0.65.0

### PR DESCRIPTION
**Pull request by GladosBlueWallet**
<h3>Snyk has created this PR to upgrade metro-react-native-babel-preset from 0.63.0 to 0.65.0.</h3>

merge advice
:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **2 versions** ahead of your current version.
- The recommended version was released **22 days ago**, on 2021-01-28.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>metro-react-native-babel-preset</b></summary>
    <ul>
      <li>
        <b>0.65.0</b> - <a href="https://snyk.io/redirect/github/facebook/metro/releases/tag/v0.65.0">2021-01-28</a></br><ul>
<li><strong>[Breaking]</strong>: Remove JSON from default asset types (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="715986361" data-permission-text="Title is private" data-url="https://github.com/facebook/metro/issues/593" data-hovercard-type="pull_request" data-hovercard-url="/facebook/metro/pull/593/hovercard" href="https://snyk.io/redirect/github/facebook/metro/pull/593">#593</a>)</li>
<li><strong>[Breaking]</strong>: Removes support for Node 10 (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/bc8a3f057c7fe277742de6ca9ce98808a76b1d03/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/bc8a3f057c7fe277742de6ca9ce98808a76b1d03"><tt>bc8a3f0</tt></a>)</li>
<li><strong>[Feature]</strong>: <code>metro-symbolicate</code>: Support for symbolicating Chrome heap timelines (TODO get hashes of <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/cb542c0f00987996caeef9672288e2b386d36d8b/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/cb542c0f00987996caeef9672288e2b386d36d8b"><tt>cb542c0</tt></a>, <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/6b0a0cb6afaa28d3a72fb2df7cbd2a99dc7362c4/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/6b0a0cb6afaa28d3a72fb2df7cbd2a99dc7362c4"><tt>6b0a0cb</tt></a>)</li>
<li><strong>[Feature]</strong>: Update the default list of lazy imports to match RN 0.63 (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="730072636" data-permission-text="Title is private" data-url="https://github.com/facebook/metro/issues/602" data-hovercard-type="pull_request" data-hovercard-url="/facebook/metro/pull/602/hovercard" href="https://snyk.io/redirect/github/facebook/metro/pull/602">#602</a>)</li>
<li><strong>[Performance]</strong>: Several changes that improve Metro's startup and bundling performance (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/807bea7d2e1d6bb6660e0d7a31139f5a9fddefbb/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/807bea7d2e1d6bb6660e0d7a31139f5a9fddefbb"><tt>807bea7</tt></a>, <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/bc8a3f057c7fe277742de6ca9ce98808a76b1d03/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/bc8a3f057c7fe277742de6ca9ce98808a76b1d03"><tt>bc8a3f0</tt></a>,<br>
<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/aceafc588334b765f7c76de148bdeb80ee4e8790/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/aceafc588334b765f7c76de148bdeb80ee4e8790"><tt>aceafc5</tt></a>, <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/279b295ecc752a1287843256185e4a9af8b26f5c/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/279b295ecc752a1287843256185e4a9af8b26f5c"><tt>279b295</tt></a>, <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/745e2d87b3b0126054b03b3e85f9da07792547a3/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/745e2d87b3b0126054b03b3e85f9da07792547a3"><tt>745e2d8</tt></a>, <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/a94200229df4e7f3a9549665142d4ad4b8d32de5/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/a94200229df4e7f3a9549665142d4ad4b8d32de5"><tt>a942002</tt></a>, <a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/d6eefe44bdc163c04b3ada92d825451b52ecf41a/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/d6eefe44bdc163c04b3ada92d825451b52ecf41a"><tt>d6eefe4</tt></a>)</li>
<li><strong>[Fix]</strong>: Optimize <code>Platform.select()</code> calls correctly when the argument includes methods (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/4d9908bf0298765af02ae8574ff15807ee5a6217/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/4d9908bf0298765af02ae8574ff15807ee5a6217"><tt>4d9908b</tt></a>)</li>
<li><strong>[Fix]</strong>: Handle EISDIR errors in <code>buildCodeFrameMessage</code> (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="635052504" data-permission-text="Title is private" data-url="https://github.com/facebook/metro/issues/567" data-hovercard-type="pull_request" data-hovercard-url="/facebook/metro/pull/567/hovercard" href="https://snyk.io/redirect/github/facebook/metro/pull/567">#567</a>)</li>
</ul>
      </li>
      <li>
        <b>0.64.0</b> - <a href="https://snyk.io/redirect/github/facebook/metro/releases/tag/v0.64.0">2020-11-05</a></br><ul>
<li><strong>[Feature]</strong>: Add <code>mkdtemp</code> and <code>mkdtempSync</code> implementations to <code>metro-memory-fs</code> (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/1ed78495ec5b492d3ce6f1f375bc596b18d9dc52/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/1ed78495ec5b492d3ce6f1f375bc596b18d9dc52"><tt>1ed7849</tt></a>)</li>
<li><strong>[Feature]</strong>: Add <code>chmod</code>, <code>lchmod</code>, and <code>fchmod</code> implementations to <code>metro-memory-fs</code> (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/d99b55be2cb9567e31f5a09ff96e3fd10c54941b/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/d99b55be2cb9567e31f5a09ff96e3fd10c54941b"><tt>d99b55b</tt></a>)</li>
<li><strong>[Feature]</strong>: Support function-name inference for flow typecast-expressions to source-maps  (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/d48277f5b78f43365333652a459602b7990fca54/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/d48277f5b78f43365333652a459602b7990fca54"><tt>d48277f</tt></a>)</li>
<li><strong>[Feature]</strong>: Support <code>SegmentID</code> field in Hermes mini-dump stack traces (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/d0634a858a860b4739ca821cec744b705edf9013/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/d0634a858a860b4739ca821cec744b705edf9013"><tt>d0634a8</tt></a>)</li>
<li><strong>[Feature]</strong>: Support node modules algorithm for resolving configuration path (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/dea7e0549c286f8052df86f833de6221463687c7/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/dea7e0549c286f8052df86f833de6221463687c7"><tt>dea7e05</tt></a>)</li>
<li><strong>[Feature]</strong>: Remove template literal and shorthand prop transformation from hermes-stable preset (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/1367b711d8807d0b300e23a06d11befe3e66d6f1/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/1367b711d8807d0b300e23a06d11befe3e66d6f1"><tt>1367b71</tt></a>)</li>
<li><strong>[Feature]</strong>: Add <code>nodeModulesPath</code> option to resolver (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/b2528d40c46085a32adbae370d0e47b6a24e3c8c/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/b2528d40c46085a32adbae370d0e47b6a24e3c8c"><tt>b2528d4</tt></a>)</li>
<li><strong>[Feature]</strong>: Remove computed properties, spread, and spread rest transform plugins from <code>Hermes-canary</code> preset (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/82818e778b75cdd1398f974513111a9a0ed43907/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/82818e778b75cdd1398f974513111a9a0ed43907"><tt>82818e7</tt></a>)</li>
<li><strong>[Breaking]</strong>: Renames the Metro <code>transform.inlineRequires.blacklist</code> option to <code>blockList</code>. (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/b25fe89261732bd0befe965e4cf0bd38ff55b2b6/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/b25fe89261732bd0befe965e4cf0bd38ff55b2b6"><tt>b25fe89</tt></a>)</li>
<li><strong>[Fix]</strong>: Prevent inlining of <code>__DEV__</code> in object property-keys (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/42942ca2ba81d03e50167ed028c8efb733bb0a3b/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/42942ca2ba81d03e50167ed028c8efb733bb0a3b"><tt>42942ca</tt></a>)</li>
<li><strong>[Fix]</strong>: Include <code>/node_modules</code> in resolver search path (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/04a2a466eb353ea2953aac108654276c262fedfb/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/04a2a466eb353ea2953aac108654276c262fedfb"><tt>04a2a46</tt></a>)</li>
<li><strong>[Fix]</strong>: Correctly escape the path separator in blocklist regular expressions on Windows (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/881d9f6d97da92fbf510236fef697642ac9a3fe2/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/881d9f6d97da92fbf510236fef697642ac9a3fe2"><tt>881d9f6</tt></a>)</li>
<li><strong>[Experimental]</strong>: Support absolute file paths when symbolicating stack traces (<a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/facebook/metro/commit/7be228453f5ff93191401c54614feb7c336fa86c/hovercard" href="https://snyk.io/redirect/github/facebook/metro/commit/7be228453f5ff93191401c54614feb7c336fa86c"><tt>7be2284</tt></a>)</li>
</ul>
      </li>
      <li>
        <b>0.63.0</b> - <a href="https://snyk.io/redirect/github/facebook/metro/releases/tag/v0.63.0">2020-08-21</a></br><ul>
<li>[fix] Change initialisation logo and text from RN to Metro</li>
</ul>
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/facebook/metro/releases">metro-react-native-babel-preset GitHub release notes</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/bluewallet/project/4d0df22a-0152-410a-8584-6df0d0a596d4?utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/bluewallet/project/4d0df22a-0152-410a-8584-6df0d0a596d4/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/bluewallet/project/4d0df22a-0152-410a-8584-6df0d0a596d4/settings/integration?pkg&#x3D;metro-react-native-babel-preset&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6h7bm631p59ek7h26p3eh0mbr8

[download apk](http://filestorage.bluewallet.io:1488/snyk-upgrade-32af47bd1c6d8697e92e767e87c79208-1613707902.apk)

**Comment by Overtorment** [comment]
@marcosrdz are we supposed to upgrade it only with RN..?

**Comment by marcosrdz** [comment]
> @marcosrdz are we supposed to upgrade it only with RN..?

I would merge it if all tests pass. Based on the changelog there arent breaking changes.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pqg5ae52hzg57025yc88z2dqmw

[download apk](http://filestorage.bluewallet.io:1488/snyk-upgrade-32af47bd1c6d8697e92e767e87c79208-1613753040.apk)

**Pull request merged**
