### PR TITLE
TST: fix detox

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/89v0279jgu1x4nk9jvbnda7duw?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/fix-detox-1620840778.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rxgvp9z9h6qf2h44ntt7620nmg?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/fix-detox-1620845708.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gfn1qg0uacmyupzc9md58k8z0w?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/fix-detox-1620899960.apk)

**Comment by Overtorment** [comment]
@limpbrains I noticed travis was failing, and tracked down failures to those changes which I'm reverting now.
nature of failures was quite strange: if you build *detox* build (not the production one) it will crash _when accessing realm_, with no meaningful error message. and it will crash only on travis or my laptop, but not on github actions.
so basically, to reproduce i did `npm run e2e:debug`, stop the running test when app is launched, and then manually go to create wallet and observe crash (as soon as code reaches `saveToDisk` and `offloadToRealm`)

**Comment by Overtorment** [comment]
maybe `reanimated` was not integrated 100% correctly

**Comment by limpbrains** [comment]
I will look into it

**Comment by Overtorment** [comment]
@limpbrains would you like to approve this pr to merge it and then work on reanimated, or introduce a fix right in this pr..? or smth else?

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Comment by limpbrains** [comment]
I've tried to reproduce this issue on my mac/android emulator, but it didn't crash - everything works fine.
Looks like it happens only on Linux. GitHub actions are run on mac, that is why it is ok there.

**Comment by Overtorment** [comment]
try creating emulator with `tests/e2e/detox-prepare-android-emu.sh`

**Pull request merged**
