### PR TITLE
FIX: 'min relay fee not met' - better estimation of tx size for feera…

### LINKED ISSUE #4352: Cannot send anything at 1sat/byte
to reproduce

Select a single UTXO with coin control

Select default fee of 1 sat per byte.

Wallet will produce a transaction of 113 Bytes with a total fee of 112 Sat making it below the minimum relay fee of 1sat/byte.

I might have posted a few similar issue or comments, This has been happening to me regularly.

### PR DESCRIPTION
**Pull request by Overtorment**
…te calculation when creating a tx (closes #4352)

### CODE REVIEW

**Comment by Overtorment** [comment]
@junderw can you pls take a look?

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/176mpd60668am950ruevkx5ypw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9704)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zz45fapzmf56amvrfckk0kmc70?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9705)

**Review by junderw — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
