### PR TITLE
feat: use ccache in CI

### PR DESCRIPTION
**Pull request by limpbrains**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f77nngcygmholcllwhu7fkhg5y?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/139)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bngrlv6kqqnbipjgx647ap3ovq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/140)

**Comment by Overtorment** [comment]
alright, whats all this then

**Comment by limpbrains** [comment]
https://reactnative.dev/docs/build-speed#use-a-compiler-cache

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/sxqvnesqskokwo6h7j7v62gxo4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/209)

**Comment by limpbrains** [comment]
First build with ccache: 
```
::group::ccache stats
ccache stats
  /usr/local/bin/ccache -s
  Cacheable calls:    23 /  41 (56.10%)
    Hits:              0 /  23 ( 0.00%)
      Direct:          0
      Preprocessed:    0
    Misses:           23 /  23 (100.0%)
  Uncacheable calls:  18 /  41 (43.90%)
  Local storage:
    Cache size (GB): 0.0 / 0.5 ( 0.45%)
    Hits:              0 /  23 ( 0.00%)
    Misses:           23 /  23 (100.0%)
  ::endgroup::
```

Build time: 20m 46s

**Comment by limpbrains** [comment]
Build after ccacche:
Build time: 28m 10s lol, probably not worth it
```
  /usr/local/bin/ccache -s
  Cacheable calls:    23 /  41 (56.10%)
    Hits:             17 /  23 (73.91%)
      Direct:         17 /  17 (100.0%)
      Preprocessed:    0 /  17 ( 0.00%)
    Misses:            6 /  23 (26.09%)
  Uncacheable calls:  18 /  41 (43.90%)
  Local storage:
    Cache size (GB): 0.0 / 0.5 ( 0.65%)
    Hits:             17 /  23 (73.91%)
    Misses:            6 /  23 (26.09%)
```

**Comment by Overtorment** [comment]
hmm now im interested.
worth trying putting it in `BuildReleaseApk` and `BuildReleaseTestflight`

**Pull request closed without merging**
