### PR TITLE
FIX: Scan to receive is more visible

### PR DESCRIPTION
**Pull request by marcosrdz**
Simulator Screen Shot - iPhone 11 - 2019-12-13 at 00 28 11

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/ynqcebaeyk6vzjpchdmvw9y3a8

**Comment by marcosrdz** [comment]
Wouldve used "Scan to receive" but smaller screens would be affected. other languages too. I think Scan is good enough.

**Comment by Overtorment** [comment]
@ncoelho your review requested. do you approve this change?

**Comment by ncoelho** [comment]
Yep. Sorry I tested it but forgot to mention. Looks good

**Pull request merged**
