### PR TITLE
ADD: Hebrew language

### PR DESCRIPTION
**Pull request by limpbrains**
- Hebrew language
- a little of alphabet sorting in language definitions

### CODE REVIEW

**Comment by ncoelho** [comment]
This is rtl 😅 ?

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vj51q06x0tezkxcc3xb61a8b5c

[download apk](http://filestorage.bluewallet.io:1488/1598602726.apk)

**Comment by limpbrains** [comment]
Sure!

image

image

**Comment by Overtorment** [comment]
oi wei, shalom shabbat 😂

**Pull request merged**
