### PR TITLE
DEBUG: psbt multisig share (rel #2298)

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/35247yr6uyha0enebg0j13mz0m

[download apk](http://filestorage.bluewallet.io:1488/1607533088.apk)

**Comment by Overtorment** [comment]
ok @marcosrdz I think its worth merging so users could actually see whats going on, e.g.:

image

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/commit/fcd61c35b29b0353d6787fed55aa9841998fc229

**Review by marcosrdz — APPROVED** [review]
I thought my previous PR covered this but ok.

**Pull request closed without merging**
