### PR TITLE
REF: better fee estimate

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/riymemdlf3spwexdkdic6yffhm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11617)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ibce6av2zs6kd5celm6s2ksgca?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11732)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by limpbrains** [comment]
It is hard to say if it is more accurate or not

Mempool.space shows:
17 sat/vB $0.81
22 sat/vB $1.05
33 sat/vB $1.58 

 Current BW shows:
 1 sat/vB
 14 sat/vB
 22 sat/vB
 
 New:
 2 sat/vB
 27 sat/vB
 41 sat/vB

Mempool: 11 / 11 / 11
Current: 1 / 9 / 15
New: 2 / 20 / 31

Mempool: 12 / 12 / 12
Current: 1 / 10 / 17
New: 2 / 25 / 38

Feels like overpaying

**Comment by Overtorment** [comment]
fair point

**Pull request closed without merging**
