### PR TITLE
ADD: Platform option for releasenotes script

### PR DESCRIPTION
**Pull request by marcosrdz**
scripts/release-notes.sh apple 

If apple : remove any mention of android or google

else: show all

### CODE REVIEW

**Review by Overtorment — CHANGES_REQUESTED** [review]
* youre excluding the whole line based on platform. suboptimal
* google doesnt care
* even apple doesnt care, if its deep inside on sub-screen in the app. only Appstore release notes matter, and iirc we put them manually

**Comment by marcosrdz** [comment]
> * youre excluding the whole line based on platform. suboptimal
> 
> * google doesnt care
> 
> * even apple doesnt care, if its deep inside on sub-screen in the app. only Appstore release notes matter, and iirc we put them manually



Its intended as a building stone to automate app store and google play store deployments via fastlane. That way we dont have to manually verify

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6kis6zmjgsibfl6kxnhbxgo7zu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12180)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/a2vh2c2wk7vnszrnyc3dowhpki?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12182)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/no66f6lamrombdjnsoueay2ppu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12218)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — CHANGES_REQUESTED** [review]
your `sed` nukes the whole line, while the idea was to replace word 'android' on smth neutral so apple moderators wont get triggered, at the same time keeping the changelog line to figure out what was cahnged. for example, this  line

```
* REF: Handle isTorCapable in-code rather than script changes Refactoring so making builds for mac and old android is less hacky
```

was completely nuked, while we couldve replaced 'android' on smth, i dunno 'other devices'..?

**Comment by marcosrdz** [comment]
This is solely for the app store review team. The release notes inside the about screen remain untouched

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fsxh4gmoaozths7gm4c7ugbylq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12235)

**Pull request merged**
