### PR TITLE
REF: speed-up wait for electrum

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by Overtorment** [comment]
for some reason it really speeded up wait for me. from like, couple of seconds to almost instantly (if electrum is already connected).
dunno why exactly

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hmvt04bv4ap4mep7g51cvhq418?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7816)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
