### PR TITLE
FIX: alert no LN wallet

### LINKED ISSUE #1809: Notice about missing lighting wallet is immediately closed
When app is opened and there is lighting invoice in the clipboard, it will offer to use it. But then it shows notice about missing lighting wallet just for a second:

https://www.dropbox.com/s/ewvj0wc3cxhusxd/RPReplay_Final1600178955.MP4?dl=0

Btw, I think it is not good for usability that user have to care about type of wallet.

### PR DESCRIPTION
**Pull request by limpbrains**
closes #1809

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/502ad5jhd046nnzd34rbvjdwdg

[download apk](http://filestorage.bluewallet.io:1488/1610271170.apk)

**Review by marcosrdz — APPROVED** [review]

**Comment by marcosrdz** [comment]
@limpbrains  conflict

**Comment by limpbrains** [comment]
> @limpbrains conflict

fixed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xg00c344za1ztj9xw785v084a4

[download apk](http://filestorage.bluewallet.io:1488/1610355951.apk)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
