### PR TITLE
FIX: Conf number reflects correct number.

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/35qbxn4dxw8e5y9upmnbcyv9c4

[download apk](http://filestorage.bluewallet.io:1488/ccfix-1611453092.apk)

**Review by limpbrains — APPROVED** [review]

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mxtrqhn8aryhr3fnbbavwmt4q4

[download apk](http://filestorage.bluewallet.io:1488/ccfix-1611591874.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9h6h800vvnhywyjqv6eyp99jv8

[download apk](http://filestorage.bluewallet.io:1488/ccfix-1611600668.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xr1yekbeq3rua94v03kwrfh670

[download apk](http://filestorage.bluewallet.io:1488/ccfix-1611949688.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k1caq840nzthn8uy7kfb7vt2hw

[download apk](http://filestorage.bluewallet.io:1488/ccfix-1611954713.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ahg5acb18k46cvvckxgw15p7b4

[download apk](http://filestorage.bluewallet.io:1488/ccfix-1611979111.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0gece94y7buyaq316r138z50kw

[download apk](http://filestorage.bluewallet.io:1488/ccfix-1611983472.apk)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
