### PR TITLE
FIX:  Modal on multisig seed #2176

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/h1xj9h1x7bwbbvfyqw08mnfmqg

[download apk](http://filestorage.bluewallet.io:1488/1607142635.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/38ut0pfg2cqfyg48jrycrp9jd4

[download apk](http://filestorage.bluewallet.io:1488/1607143854.apk)

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by ncoelho** [comment]
conflits

**Comment by marcosrdz** [comment]
> conflits

fixed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xqv8gr92b00qgry12g93pf05d4

[download apk](http://filestorage.bluewallet.io:1488/1607541433.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dadypjn8ncrrbyb2b8325rcz7w

[download apk](http://filestorage.bluewallet.io:1488/1607725608.apk)

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
