### PR TITLE
OPS: Add Maps package

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6r5ju8q4g3tw3qur7eucczzn30

[download apk](http://filestorage.bluewallet.io:1488/1578378046.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/a0rjtdyb8am5qzrwwxru7tyuar

[download apk](http://filestorage.bluewallet.io:1488/1578429030.apk)

**Comment by Overtorment** [comment]
cleanup

**Comment by Overtorment** [comment]
@marcosrdz  btw, what if we do ATM map in a webview? will it suck?

**Comment by marcosrdz** [comment]
> @marcosrdz  btw, what if we do ATM map in a webview? will it suck?

Yup. Bad experience. Its been tried before

**Pull request closed without merging**
