### PR TITLE
FIX: Vault UI fixes

### PR DESCRIPTION
**Pull request by marcosrdz**
## Summary by CodeRabbit

- **New Features**
	- Enhanced modal handling and user interaction flow in the wallets section.
	- Introduced keyboard visibility management for improved footer display.
	- Added a new header component in modals for better user guidance.

- **Bug Fixes**
	- Adjusted modal dimensions and layout for consistency across platforms.

- **Style**
	- New styles added for header and QR code presentation.
	- Updated padding and margin styles for improved layout consistency.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
