### PR TITLE
DEL: babel-cli babel-eslint babel-jest eslint-plugin-babel

### PR DESCRIPTION
**Pull request by limpbrains**
removing babel-cli, I can't find where it is used 
babel-jest, because we are now running tests with ts-jest
babel-eslint and eslint-plugin-babel, because we are now using @typescript-eslint/parser in eslint config

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] 

[download apk](https://lambda-download-android-build.herokuapp.com/download/11451)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by Overtorment** [comment]
wow niiiiice, i love deleting shit from dependencies

**Pull request merged**
