### PR TITLE
FIX: Statusbar barstyle

### PR DESCRIPTION
**Pull request by marcosrdz**
No need to specify StatusBar on every screen. Only on the main ones, it's children will follow the parent's barStyle

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k2pbf36w8ubwpynmqtz6czm6hg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8525)

**Comment by ncoelho** [comment]
Did a fast test, found this one so far. 

Screenshot 2021-09-27 at 19 03 28

**Comment by marcosrdz** [comment]
> Did a fast test, found this one so far.
> 
> Screenshot 2021-09-27 at 19 03 28

Fixed. Check again

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/khceu0rv33m4hqkpzhymgajh10?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8529)

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
