### PR TITLE
ADD: SignVerify screen

### PR DESCRIPTION
**Pull request by limpbrains**
This is for upcoming #990

image

cc @jaonoctus 

Screen expects  `address` and `walletID` from route params

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/v0rj7chhj404eray3yvmamneg8

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sign-verify-1615630598.apk)

**Review by Overtorment — CHANGES_REQUESTED** [review]
1) needs keyboard avoiding view:

image

2) signing on android takes some time, so needs some kind os isLoading state

3) alerts "signature is correct" & "signature is incorrect"  look too lookalike

4) create single-address wallet -> signVerify button crashes the walelt. probably  because you used _geExternalAddress()

**Comment by limpbrains** [comment]
I've tried `KeyboardAvoidingView` but can't figure it out how to use it here so that everything works nicely.
@marcosrdz can you please take a look why 
`inputAccessoryViewID={BlueDoneAndDismissKeyboardInputAccessory.InputAccessoryViewID}` 
doesn't work here on Android. On iOS it woks as expected.

2. added loading
3. changed alerts 
4. It is just temporary. When @jaonoctus will finish addresses list it should be used there, not in wallet/details

**Comment by marcosrdz** [comment]
> I've tried `KeyboardAvoidingView` but can't figure it out how to use it here so that everything works nicely.
> 
> @marcosrdz can you please take a look why 
> 
> `inputAccessoryViewID={BlueDoneAndDismissKeyboardInputAccessory.InputAccessoryViewID}` 
> 
> doesn't work here on Android. On iOS it woks as expected.
> 

This is an iOS only RN component. For Android, look at import.js
We render the same toolbar and listen for keyboarddidshow and keyboarddidhide to determine when to render it on android. Multiline TextFields must NOT have a static height.

> 
> 
> 2. added loading
> 
> 3. changed alerts 
> 
> 4. It is just temporary. When @jaonoctus will finish addresses list it should be used there, not in wallet/details

**Comment by limpbrains** [comment]
> This is an iOS only RN component. For Android, look at import.js
> We render the same toolbar and listen for keyboarddidshow and keyboarddidhide to determine when to render it on android. Multiline TextFields must NOT have a static height.
> 

I did exactly the same way as in `wallets/import.js`

**Comment by marcosrdz** [comment]
> > This is an iOS only RN component. For Android, look at import.js
> > We render the same toolbar and listen for keyboarddidshow and keyboarddidhide to determine when to render it on android. Multiline TextFields must NOT have a static height.
> 
> I did exactly the same way as in `wallets/import.js`

Screen Shot 2021-03-17 at 9 01 30 PM

**Comment by marcosrdz** [comment]
> > > This is an iOS only RN component. For Android, look at import.js
> > > We render the same toolbar and listen for keyboarddidshow and keyboarddidhide to determine when to render it on android. Multiline TextFields must NOT have a static height.
> > 
> > 
> > I did exactly the same way as in `wallets/import.js`
> 
> Screen Shot 2021-03-17 at 9 01 30 PM

Seems to be working for me

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ad1z3zymm3t0pxtn2r932hpat4

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sign-verify-1616030542.apk)

**Comment by limpbrains** [comment]
image
Looks like it is hidden, because it is rendered after the buttons

**Comment by limpbrains** [comment]
I figured it out, thanks

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2k5qw17m57yd10655rca5204km

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sign-verify-1616067219.apk)

**Review by Overtorment — CHANGES_REQUESTED** [review]
single-address wallet -> signverify -> crash

image

**Comment by limpbrains** [comment]
- Single address wallets has been fixed
- watch-only and custodian lightning wallets can't sign/verify

PR ready to be merged

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f73269mehptb9nmy5tqf9w5mrr

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sign-verify-1616502851.apk)

**Review by Overtorment — APPROVED** [review]
@marcosrdz

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
