### PR TITLE
OPS: Package Update

### PR DESCRIPTION
**Pull request by marcosrdz**
Windows auto link support

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ky71pcuy1tfvdwjjwtgm0w3btr

[download apk](http://filestorage.bluewallet.io:1488/asyncs-1611336826.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8wfq6fwz1cnjd4wpjvudfapu3c

[download apk](http://filestorage.bluewallet.io:1488/asyncs-1611362962.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1q6fy6amc2ww3u0kfnye2p72x0

[download apk](http://filestorage.bluewallet.io:1488/asyncs-1611368635.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
