### PR TITLE
Update .yarnrc.yml

### PR DESCRIPTION
**Pull request by marcosrdz**
## Summary by CodeRabbit

- **Chores**
	- Updated package management settings to ensure that checksums are actively updated during installations, enhancing dependency validation and integrity checks.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by limpbrains** [comment]
This should not be default in yarnrc

**Comment by Overtorment** [comment]
maybe we need`reset` instead of `update` ?

**Pull request closed without merging**
