### PR TITLE
REF: Encrypt/Decrypt prompt

### PR DESCRIPTION
**Pull request by marcosrdz**
Further remove dependency on broken prompt package. 

Simulator Screenshot - iPhone 15 Pro Max - 2024-08-02 at 13 07 43

## Summary by CodeRabbit

- **New Features**
	- Introduced a `PromptPasswordConfirmationModal` for improved password management, allowing users to create and enter passwords with visual feedback.
	- Implemented a modal for password confirmation in the `PlausibleDeniability` component, enhancing interaction clarity and user experience.
	- Enhanced the `EncryptStorage` component with a modal for password confirmation, streamlining the password input process and improving overall user experience.
	- Improved text rendering in the `TransactionsNavigationHeader` by allowing dynamic font size adjustments for better visibility.

- **Bug Fixes**
	- Updated localization strings for password prompts to enhance clarity by changing "retype password" to "confirm password."

- **Documentation**
	- Updated localization files across multiple languages for clearer user instructions regarding password entry and storage encryption.

- **Tests**
	- Enhanced UI test interactions for password inputs to improve targeting and realism, contributing to a more reliable testing framework.

- **Chores**
	- Added conditional checks in the `StorageProvider` to optimize connection management based on wallet availability.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by limpbrains** [comment]
typescript errors, tests are failing

**Review by Overtorment — CHANGES_REQUESTED** [review]
LGTM but lint & tests failed.

also @marcosrdz ELI5 how does the new prompt works? old prompt was a package. and it rendered _always_ on top of the app, modal.
tell me about the new one?

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by marcosrdz** [comment]
Ill be updating the code. The old prompt would always render on top cause it used old mechanisms no longer recommended. It would break on macOS and sometimes on iPad. This one is a bit more complex syntax wise but you essentially provide the type of prompt you need (numeric, password or password with confirmation), then pass the then/catch as onConfirmationSuccess onConfirmationFailure.

**Comment by Overtorment** [comment]
@marcosrdz but technically, how does it work? is it some master component that wraps the whole app and provides  a modal that would always be on top?

**Comment by marcosrdz** [comment]
> @marcosrdz but technically, how does it work? is it some master component that wraps the whole app and provides  a modal that would always be on top?

At the moment no. Its inside the render per screen. But im looking into implementing that later on a different PR

**Review by Overtorment — CHANGES_REQUESTED** [review]
tests failed

**Review by colorado392 — APPROVED** [review]

**Review by colorado392 — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
