### PR TITLE
OPS: Remove JCenter lines from build.gradle

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by Overtorment — CHANGES_REQUESTED** [review]
all android builds broke

**Comment by emanuelb** [comment]
> all android builds broke

Cause the PR didn't added the needed maven replacement like `mavenCentral()`, see for more details and migration from JCenter at: https://jeroenmols.com/blog/2021/02/04/migratingjcenter/

**Comment by emanuelb** [comment]
looks like need to fix first (RN upgrade) as errors from RN dep: https://github.com/BlueWallet/BlueWallet/pull/3170 which might not fix errors as maybe small number of deps still didn't migrated from JCenter.
also I also suggest to first fixing https://github.com/BlueWallet/BlueWallet/issues/3166 which make easier to see all deps downloaded by gradle and thus locate the deps that need fixing (contact vendor, etc..)

**Comment by emanuelb** [comment]
You can declare specific usages of jcenter like explained in https://jeroenmols.com/blog/2021/02/04/migratingjcenter/#consumed-dependencies-from-bintrayjcenter and like it's done for example in this PR of unstoppable wallet "Gradually migrate from jcenter to mavenCentral"
https://github.com/horizontalsystems/unstoppable-wallet-android/pull/3752/files

**Comment by Overtorment** [comment]
for reference https://blog.gradle.org/jcenter-shutdown

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/3170


JCenter removed except for those packages that haven't been placed into mavenCentral repo yet. Im expecting the next RN release to have everything it needs placed in mavenCentral.

**Comment by Overtorment** [comment]
@marcosrdz conflicts

**Comment by marcosrdz** [comment]
Closing as the the RN 64 branch dealt with this.

**Pull request closed without merging**
