### PR TITLE
REF: Custom receive

### PR DESCRIPTION
**Pull request by marcosrdz**
Simulator Screen Shot - iPhone 11 - 2019-12-15 at 01 38 36

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/qhwhvmp4c1md8q0tutta1j0zzw

**Comment by ncoelho** [comment]
Just change the reset to below the create and with the white background button, so it doesn't take away the highlight the create should have over it. (If the reset is really needed, otherwise I would remove it)

**Comment by marcosrdz** [comment]
> Just change the reset to below the create and with the white background button, so it doesn't take away the highlight the create should have over it. (If the reset is really needed, otherwise I would remove it)

Simulator Screen Shot - iPhone 11 - 2019-12-15 at 07 53 24


Done. Modal on top of modal is no longer the case. #applehig

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/85nv5r2yd6pdyrh4qd4d78dqcw

**Comment by Overtorment** [comment]
@marcosrdz are you cool with LGTM.com bitchin..?

**Comment by marcosrdz** [comment]
> @marcosrdz are you cool with LGTM.com bitchin..?

Yup. Will be rewritten with hooks later anyways. Proceed

**Pull request merged**
