### PR TITLE
OPS: Package update

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5zklepxeuzyeniadeasyp5wjom?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11018)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vbeud3l4jiod26pqarewjsntga?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11035)

**Comment by Overtorment** [comment]
something is not right. e2e fails

**Pull request closed without merging**
