### PR TITLE
ADD: allow send MAX and BATCH for all wallet types

### LINKED ISSUE #1007: Enable batch send on BIP49
quite easy, make bip49 class return true in allowBatchSend method and test it properly

### PR DESCRIPTION
**Pull request by limpbrains**
Remove `allowSendMax` and `allowBatchSend` flags
closes #1007

### CODE REVIEW

**Comment by limpbrains** [comment]
I've tested legacy single address with batch send, works fine

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u2vxpahvnhvjkba612y5yb4890

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-bach-max-all-wallets-1616064917.apk)

**Review by Overtorment — APPROVED** [review]
very noice

**Review by marcosrdz — APPROVED** [review]

**Comment by Overtorment** [comment]
confclicts

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/11n78fv5d41zpvbfet6ypj6758

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-bach-max-all-wallets-1616424633.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/88kbhxe55ytr8dj6zbu7t8drmr

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-bach-max-all-wallets-1616612297.apk)

**Comment by Overtorment** [comment]
@ncoelho wake the fuck up samurai, we've got PRs to merge

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
