### PR TITLE
REF: make provideEntropy looks fine on desktop

### PR DESCRIPTION
**Pull request by limpbrains**

### CODE REVIEW

**Comment by limpbrains** [comment]
not ready yet

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u7awaba4h93bn7meab010vw1u0

[download apk](http://filestorage.bluewallet.io:1488/1600593129.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/h5vw4tvzw333ab32yt1zrr65g8

[download apk](http://filestorage.bluewallet.io:1488/1600945300.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/761hzr5p5vyf1kunaggpg5zz2m

[download apk](http://filestorage.bluewallet.io:1488/1600946466.apk)

**Review by Overtorment — APPROVED** [review]
lgtm

**Review by marcosrdz — APPROVED** [review]

**Pull request merged**
