### PR TITLE
REF:: Navigation had multiple containers instead of just 1

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]

**Comment by Overtorment** [comment]
Lgtm.
Some tests failed tho

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ai54oq77newf3766bhi6672mmq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1447)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Review by limpbrains — APPROVED** [review]

**Comment by marcosrdz** [comment]
> Lgtm.
> Some tests failed tho

Which one

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
