### PR TITLE
Feature broadcast page

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hy17vur4p0vrw1cm6g95gtb60r

[download apk](http://filestorage.bluewallet.io:1488/1587380084.apk)

**Comment by ncoelho** [comment]
This in not working on iOS, it missing two features:
- Dismiss keyboard button
- avoidKeyboardTouch

Gonna try to add them
sadfa

Also @Overtorment a though, this is a general feature not attached to a wallet right? Shouldn't it be better under settings > network. wdyt?

**Comment by Overtorment** [comment]
@dr3am3r height of text input should be limited (on other broadcast screen we have it limited to like 5 lines, I think).  no sane person really needs to see whole hex before broadcasting.

as to where to place it, I think it makes sense to place in in  both places - wallet details AND wallet settings

**Comment by Overtorment** [comment]
image
@dr3am3r їбати в сраку, що це за гімно

**Comment by dr3am3r** [comment]
> @dr3am3r height of text input should be limited (on other broadcast screen we have it limited to like 5 lines, I think). no sane person really needs to see whole hex before broadcasting.
> 
> as to where to place it, I think it makes sense to place in in both places - wallet details AND wallet settings

I've just added it somewhere :) roger that

**Comment by dr3am3r** [comment]
> This in not working on iOS, it is missing two features:
> 
> * Dismiss keyboard button
> * avoidKeyboardTouch
affirmative!

**Comment by dr3am3r** [comment]
> @dr3am3r їбати в сраку, що це за гімно
це їбаний `FormInput` з `react-native-elements`, спробую версію підняти

**Comment by Overtorment** [comment]
@marcosrdz can I get your blessing?

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/p3xyr4g6ugm6068hvg68ej3jpw

[download apk](http://filestorage.bluewallet.io:1488/1588090001.apk)

**Pull request merged**
