### PR TITLE
OPS: Upgrade targetSdkVersion to 30 - target Android 11 (closes #3082)

### LINKED ISSUE #3082: Upgrade targetSdkVersion to 30 (target Android 11)
currently the app target SDK 29 (Android 10) which is the minimum required for publishing the apk to google-play currently (in November will be required to upgrade to SDK 30), it's better to upgrade sooner to benefit from the security improvements.

list of changes for apps that target Android 11: (see that it's not affecting the app, fix issues if exists, etc..)
https://developer.android.com/about/versions/11/behavior-changes-11

which will also require fixing #3081 (sign apk with v2+ signing scheme is required for apps targeting SDK 30)

The entries in:
https://github.com/BlueWallet/BlueWallet/blob/1bdd37d0fb3d79880fefe5a624b6598572f5a1ca/android/build.gradle#L7-L9

will need to be changed into:
```
buildToolsVersion = "30.0.3"
compileSdkVersion = 30
targetSdkVersion = 30
```

https://github.com/BlueWallet/BlueWallet/blob/1bdd37d0fb3d79880fefe5a624b6598572f5a1ca/android/build.gradle#L55-L56

to:

```
 compileSdkVersion 30 
 buildToolsVersion '30.0.3' 
```

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by ncoelho** [comment]
nACK. This should be done only when strictly necessary.

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4r4bn6n8u5wacw5nngbw3yn6jw?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/up-android-11-1620235838.apk)

**Comment by Overtorment** [comment]
https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html

will wait till august (or november)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/w5t5f8p5u6j0893nf2yua9y9a0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7633)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
