### PR TITLE
feat: refactor biometrics to typescript

### PR DESCRIPTION
**Pull request by limpbrains**

### CODE REVIEW

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/edfknlecd2q2h2sg2h4j2gytn4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12293)

**Comment by marcosrdz** [comment]
@limpbrains conflicts

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wlox7vmvelea363ndfgplfxfty?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12304)

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by Overtorment** [comment]
@limpbrains conflicts

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wdrbifv5z6z2fk77ytntyqscje?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/36)

**Comment by Overtorment** [comment]
e2e failed. i restarted it

**Comment by marcosrdz** [comment]
@limpbrains e2e fails.

**Comment by limpbrains** [comment]
Yes, will work on it

**Comment by Overtorment** [comment]
@limpbrains conflicts

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zxknzej2ylzaf44ucmqhuzhpta?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/290)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/imnxdz6gyyphqnr7zuzprdlo4u?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/291)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/36xva2afj26ro3uk4lul4grmce?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/308)

**Comment by Overtorment** [comment]
oops i missed the updates and now we haveconflicts again. @limpbrains can you pls take a look..?

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/a26hzqkcjcdjupebei2bcixbeu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/431)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7j3oxeax3qgzgcwtdiec3pgldu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/434)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
