### PR TITLE
REF: Align elements on backup view

### PR DESCRIPTION
**Pull request by ncoelho**
Screenshot 2021-04-20 at 16 33 51

### CODE REVIEW

**Review by Overtorment — CHANGES_REQUESTED** [review]
lint failed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8b0e1rnumddbq2zhfzq9jwg6km

[download apk](http://filestorage.bluewallet.io:1488/backupview-1618934908.apk)

**Comment by marcosrdz** [comment]
How does it look with RTL? Not sure how it will look with Those style changes

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k5tkhuw0chz2awp86rfgnfbuj4

[download apk](http://filestorage.bluewallet.io:1488/backupview-1618935869.apk)

**Comment by ncoelho** [comment]
The change is vertical, to put the button on the bottom keeping the scrollview at the same time.

Screenshot 2021-04-20 at 19 12 03

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/r73c0j9rgua6kag7gt68hp2jy8

[download apk](http://filestorage.bluewallet.io:1488/backupview-1618984054.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
