### PR TITLE
ADD: support truncated words during slip39 wallet import

### LINKED ISSUE #4286: SLIP39 4-letter import
Dear valued BlueWallet Team!
The advantage of SLIP39 over a Shamir Secret Scheme is that no tools are required for decoding. 
Therefore, it would be extremely practical if the wallet could be imported directly from the steel plates. 
However, this is - should I have done nothing wrong - not yet the case.

I would be delighted should BlueWallet support this option. Without this last step towards full implementation, the use of SLIP39 is still questionable.

PS: My favorite software has made tremendous progress again this year. I am more than happy about your efforts!
I am already looking forward to next year and will in any case remain active as a superuser.

---- HERE THE TEST - THE WALLET IST EMPTY ---

crucial pajamas academic acne biology acrobat sugar silver medical losing scatter evening obtain budget corner category race husky wildlife unkind
crucial pajamas academic agree debut patrol shaped campus result pencil living ruin usual laden again group exhaust decision ceiling silent
crucial pajamas academic amazing answer grownup unfair vampire adorn race valid kind promise learn discuss dynamic fraction rhythm blessing always
crucial pajamas academic arcade deadline scene wrist company decorate multiple provide visitor scout tolerate birthday isolate paper zero smart crush
crucial pajamas academic axle daisy charity duration mortgage process charity laden dragon party ladybug cultural escape superior destroy friar believe

CRUC PAJA ACAD ACNE BIOL ACRO SUGA SILV MEDI LOSI SCAT EVEN OBTA BUDG CORN CATE RACE HUSK WILD UNKI
CRUC PAJA ACAD AGRE DEBU PATR SHAP CAMP RESU PENC LIVI RUIN USUA LADE AGAI GROU EXHA DECI CEIL SILE
CRUC PAJA ACAD AMAZ ANSW GROW UNFA VAMP ADOR RACE VALI KIND PROM LEAR DISC DYNA FRAC RHYM BLES ALWA
CRUC PAJA ACAD ARCA DEAD SCEN WRIS COMP DECO MULT PROV VISI SCOU TOLE BIRT ISOL PAPE ZERO SMAR CRUS
CRUC PAJA ACAD AXIE DAIS CHAR DURA MORT PROC CHAR LADE DRAG PART LADY CULT ESCA SUPE DEST FRIA BELI

### PR DESCRIPTION
**Pull request by limpbrains**
Needs to be https://github.com/BlueWallet/slip39-js/pull/1 merged at first

closes #4286

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tx8eg7w85fdyz47pynnfrzuyh0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9237)

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/slip39-js/pull/1 merged

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/m988wph7pnqwdbvujz1upfxatc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9242)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
