### PR TITLE
REF: Move LT to Tools

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/znnj5kwzqt66b0d74zxe58m4yr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7830)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/d01y9qyzehxtrf538yj1k8e48w?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7831)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3d7e3d7rxce4geqjxj1hy1y35r?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7832)

**Comment by Overtorment** [comment]
ios build failed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pjbgezggzdcbc9yq512c8ua7vc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7836)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2nrfj619aq62u3vm7me283ffbr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7838)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xdfa65zf8emmebznhvq1qqwu5c?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7839)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
