### PR TITLE
FIX: Set biometric flag off when enabling encryption

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6cv9zw5dyj9wq4jw2hz61pz5yc

[download apk](http://filestorage.bluewallet.io:1488/setbiometricflag-1614311792.apk)

**Review by Overtorment — CHANGES_REQUESTED** [review]
why do we disable it?
storage encryption doesn't means we should not verify biometrics prior to showing wallet export/other risky stuff

**Comment by marcosrdz** [comment]
> why do we disable it?
> storage encryption doesn't means we should not verify biometrics prior to showing wallet export/other risky stuff

You're right.

**Comment by Overtorment** [comment]
@marcosrdz  dont forget to delete branches if you're closing the pr

**Pull request closed without merging**
