### PR TITLE
 REF: Lazy Load wallet export

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6ca4oyn5dpdfomcmjvodepchyq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1523)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3mdglquluiqicvbep7agzd3ewe?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1524)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/q763fzv3kexcqpjslpfse7x2dm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1525)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zif6poxt7dw4gs7bx7vc3hjm6a?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1526)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
