### PR TITLE
REF: AddressInput to TSX

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hvt3h2j4wmv6mra5d5krqnizha?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/92)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6u22ar3kirsw6v5zeo2xuy5ynq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/98)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pq2aqhhymofuyzx4qyuay36ddi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/100)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/c4coa3pttt6goddez5y7jaqyc4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/101)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nzrjrdmf3end3cx72tn47ypiqq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/103)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
