### PR TITLE
ADD: HodlHodl accept offers

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bd6mecpkedhtq0f5u139hyraj8

[download apk](http://filestorage.bluewallet.io:1488/1590871183.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f68d0462gedejee9jdkd1a4f60

[download apk](http://filestorage.bluewallet.io:1488/1591123546.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xu1pav3qkwantuw9jxxykhtwcg

[download apk](http://filestorage.bluewallet.io:1488/1591126876.apk)

**Comment by marcosrdz** [comment]
Can we move the Image data prop content into a different file? Its massive and I gotta scroll a lot every time I wanna update the file or read it

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6m5ar6843nggfk9vcgmefjnrv4

[download apk](http://filestorage.bluewallet.io:1488/1591290009.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/d1uubjr81thdb4v0pxv9w2fazg

[download apk](http://filestorage.bluewallet.io:1488/1591296647.apk)

**Comment by Overtorment** [comment]
@ncoelho @marcosrdz give it a spin

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x3qge9b0uxd188k2gxqzybqxc0

[download apk](http://filestorage.bluewallet.io:1488/1591636359.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fhqxnh2gyj7kpn1adgppy0wpw4

[download apk](http://filestorage.bluewallet.io:1488/1591638626.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e4tarr37tvk4ff6j4c2n5pr6yg

[download apk](http://filestorage.bluewallet.io:1488/1591650652.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/r6exh9vq08ub3wu9hv9ubwyw5m

[download apk](http://filestorage.bluewallet.io:1488/1591697902.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/85ngd81tyy3894z5x34m26n9yr

[download apk](http://filestorage.bluewallet.io:1488/1592235581.apk)

**Comment by ncoelho** [comment]
Blessed!

**Pull request merged**
