### PR TITLE
REF: TransactionStatus to TSX

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vne3zy7pribynqvqnsuyaz7cku?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1255)

**Review by Overtorment — CHANGES_REQUESTED** [review]
deepscan is unhappy

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yi7dod5oxilp54wunak3ola66u?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1262)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ppbtiyiik3m42z7rem77w5vwhe?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1265)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
