### PR TITLE
ADD: Ask user if they have backed up their seed phrase

### PR DESCRIPTION
**Pull request by marcosrdz**
Simulator Screen Shot - iPhone 5s - 2019-12-24 at 21 31 56

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pnamtx4xqjzx5gvdud840z64bg

[download apk](http://filestorage.bluewallet.io:1488/1577245382.apk)

**Comment by Overtorment** [comment]
Peek 2019-12-25 21-17

**Comment by Overtorment** [comment]
+ doesnt look like LN export string copies to clipboard on click

**Comment by marcosrdz** [comment]
> * doesnt look like LN export string copies to clipboard on click

Thats on a different PR

**Comment by Overtorment** [comment]
> > * doesnt look like LN export string copies to clipboard on click
> 
> Thats on a different PR

kk

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/epmura5yp9ya5f3aupkqdmag20

[download apk](http://filestorage.bluewallet.io:1488/1577316067.apk)

**Pull request merged**
