### PR TITLE
REF: BlueClipboard JS -> TS

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]
Lgtm

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/g6weljbbsyvndp35pmiuextk5e?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11074)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vdvw5bqh2w7zd5eonk6trzjwxm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11085)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
