### PR TITLE
FIX: Wallet Storage bug with removal

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2u2aj7112bnp9uq5rxjjkgm8gm

[download apk](http://filestorage.bluewallet.io:1488/1591312449.apk)

**Comment by Overtorment** [comment]
is that the build `11988`? i tested it, lgtm. tried to turn on & off wipe after delete option, relaunched several times.
Id say lets merge while our testfligh beta testers testing it. @ncoelho @marcosrdz thoughts?

**Comment by marcosrdz** [comment]
You gotta uninstall and reinstall the app. Uninstall the app. Reinstall. Open, close, open. Toggle the option, uninstall, reinstall. Open close open

**Comment by Overtorment** [comment]
i had no issues with missing wallets. I just tested that if you simply update BW (like most of users do - just update) - nothing breaks

**Comment by marcosrdz** [comment]
Merge!

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vmddjk6qgmwt1q9gn8rkpnqeb0

[download apk](http://filestorage.bluewallet.io:1488/1591386751.apk)

**Comment by Overtorment** [comment]
@ncoelho your word

**Comment by ncoelho** [comment]
No issues with updating. Not able to reproduce

**Pull request merged**
