### PR TITLE
ADD: Watch app Handoff #989

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/c3zq6uv1tczrf73vqwtw5vn5m4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8550)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bbj921f962nkn64q6k31gh4r2c?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8552)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/47hj9b2pvz4493m63auq5wnkk8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8554)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Pull request merged**
