### PR TITLE
REF: useReducer for on app launch

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]
@marcosrdz remind me whats the point of this approach?
i find it hard to read.

@limpbrains what do you think?

**Comment by marcosrdz** [comment]
> @marcosrdz remind me whats the point of this approach?
> 
> i find it hard to read.
> 
> 
> 
> @limpbrains what do you think?

Its so every possible UI state is documented and predictable

**Comment by limpbrains** [comment]
I like useReducer, but I don't think we should refactor all screens to use it. Only complex ones.
Component with 2 state variables and 2 actions looks simpler with just useState

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
