### PR TITLE
REF: refactor localization

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8u3eev7y62btju2yea53bg31fg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10125)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u55gkmuugx2z3aub0aa97meke4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10126)

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7kjvfqrj6bm08qzq3v123rw8wg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10127)

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
