### PR TITLE
FIX: amount toolbar should be hidden on Android by default

### LINKED ISSUE #2949: Keyboard helper on send view
Screenshot 2021-04-12 at 11 46 15

### PR DESCRIPTION
**Pull request by limpbrains**
closes #2949

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hk0qt317n8djdb76jf3zadcw38

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-amount-toolbar-1618476812.apk)

**Comment by ncoelho** [comment]
I don't see the toolbar now

Screenshot 2021-04-15 at 12 03 44

**Comment by limpbrains** [comment]
@ncoelho Yeah, it is hidden after Next button. And BW has this bug for a long time. I've just checked v5.6.7 - same thing.
I suggest we merge this PR and I will try to fix a hidden toolbar in another one.

**Comment by ncoelho** [comment]
Tested 6.0.0 working correctly
Tested 6.0.8 bug is present.

PS: Check import screen toolbar behaviour. working correctly there on 6.0.8

**Comment by limpbrains** [comment]
> Tested 6.0.0 working correctly
> Tested 6.0.8 bug is present.
> 
> PS: Check import screen toolbar behaviour. working correctly there on 6.0.8

Which android device? Appetize ?

On my local Pixel 2 emulator:

изображение

**Comment by marcosrdz** [comment]
inputview on Android is different from iOS. iOS places it as an actual part of the keyboard. On Android we "shrink" or "hide" elements so it looks like the toolbar is part of the keyboard. On import.js we allow the textinput to shrink to accommodate for this.

**Comment by limpbrains** [comment]
Yes. I want to try position=absolute for this toolbar or make Send screen more shrinkable.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/azqbgh0rd67rbwu3r7rygm8ft8

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-amount-toolbar-1618590951.apk)

**Comment by limpbrains** [comment]
I've moved `BlueUseAllFundsButton` to separate file in components/ and refactored to use `position: absolute`.
Now it correctly works on small screens 

изображение

**Comment by marcosrdz** [comment]
> I've moved `BlueUseAllFundsButton` to separate file in components/ and refactored to use `position: absolute`.
> 
> Now it correctly works on small screens 
> 
> 
> 
> изображение
> 
> 

Such an obvious thing to Do but I never did . Awesome!

**Review by marcosrdz — APPROVED** [review]

**Review by ncoelho — APPROVED** [review]

**Comment by ncoelho** [comment]
Nice!

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
