### PR TITLE
REF: Correcting Punctuation Marks

### PR DESCRIPTION
**Pull request by mcsaeid**
Periods, commas, dashes (hyphens and em dashes).

Notable Issues
1. No comma is required after “please.”
2. A period is required to end a sentence. A full sentence must have a full stop at the end.
3. Incorrect use of the exclamation mark. Here is a quick read: grammarly.com/blog/exclamation-mark.
4. When a sentence is followed by a dependent phrase, such as the one below, an em dash (—) is recommended instead of a comma:
Example: This is your transaction's hex—signed and ready to be broadcasted to the network. (A dependent phrases such as “signed and ready to be broadcasted to the network” cannot stand on its own as a full sentence because it is not.)
5. Extra space between the last word of the sentence and period, namely: “…has been saved in your Downloads folder .” The extra space must be omitted.
6. Some prepositions are not capitalized in titles, namely “for” and “by” (in Replace by Fee and Child Pays for Parent).

There is a reason for each specific change that I made, thus making all of the necessary. I would be happy to provide sources if necessary.

### CODE REVIEW

**Review by marcosrdz — APPROVED** [review]

**Comment by limpbrains** [comment]
Please be advised that changing strings in en.json will reset all corresponding translations on Transifex. It can be fixed by re-uploading json files, but requires certain preparations.

Same for  #2289 #2290 #2291 

Also, I think it is better to unite all these PR in one, for simplicity

**Comment by mcsaeid** [comment]
I was advised by Nuno (@ncoelho) to do these separately so that reviewing them was easier for the team member and contributors. However, I can do all of the necessary changes (punctuation, capitalization, spacing, and so on) in one request. I do agree that it will be more clear.

Let me know, and I can get started. You can then deny or remove the current pull requests. I will also be making a backup of the translations in case they reset, so I can put them in as soon as the merge happens.

**Comment by limpbrains** [comment]
If Nuno is fine with it, I'm fine too

**Review by Overtorment — CHANGES_REQUESTED** [review]
could you please also amend `tests/e2e/bluewallet.spec.js` ?

'Your storage is encrypted. Password is required to decrypt it'
`Retype password`

otherwise TravisCI tests fail (those tests check existence of elements with specific test)

**Comment by Overtorment** [comment]
otherwise solid PR, good job!

**Comment by mcsaeid** [comment]
Thank you.

I don't know how to edit that file or where I can find it. Would you kindly provide a link?

**Comment by Overtorment** [comment]
> Thank you.
> 
> I don't know how to edit that file or where I can find it. Would you kindly provide a link?

https://github.com/BlueWallet/BlueWallet/blob/master/tests/e2e/bluewallet.spec.js

**Comment by mcsaeid** [comment]
The “bluewallet.spec.js” should now be compliant. I made sure that every change that I previously made was reflected in there as well. Let me know how it goes.

**Comment by Overtorment** [comment]
merged in https://github.com/BlueWallet/BlueWallet/pull/2316
thanks!

**Comment by mcsaeid** [comment]
Beautiful! I am looking forward to improving the written material. Keep the features coming.

**Pull request merged**
