### PR TITLE
REF: Place network calls in InteractionManager

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ghqlufoxw5ob374xapr4ytkbxy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1562)

**Review by Overtorment — CHANGES_REQUESTED** [review]
a bit doubtful about this one. do we really want to delay network fetch in favor of more  smooth animations..?

@limpbrains wdyt?

**Comment by marcosrdz** [comment]
> a bit doubtful about this one. do we really want to delay network fetch in favor of more  smooth animations..?
> 
> 
> 
> @limpbrains wdyt?

Its more of a debounce behavior

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Review by limpbrains — APPROVED** [review]
I think it is usefull. 
Would prefer Promise syntax thought
```js
await new Promise((resolve) => {
  InteractionManager.runAfterInteractions(() => resolve(null));
});
```

**Review by Overtorment — APPROVED** [review]
if @limpbrains blessed it then its fine with me too

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
