### PR TITLE
Feat: yarn v3

### LINKED ISSUE #6594: Migration to Yarn
npm scripts are hardcoded

### PR DESCRIPTION
**Pull request by limpbrains**
- ~~yarn lock was generated by [synp](https://github.com/imsnif/synp)~~
- circle ci tests are failing because of Memory Overflow :)
- yarn doesn't have `npm install --production` functionality out of the box
- I've used yarn version that RN community suggests 

How I generated yarn.lock file:
- npm i --lockfile-version 2  - to downgrade package-lock.json
- yarn@1 import - to generate yarn.lock v1
- yarnv3 install - to convert yarn.lock to v6
- replace `git+ssh://git@` with `https://` in yarn.lock to speedup install

closes #6594

### CODE REVIEW

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by limpbrains** [comment]
I'm using `@lodev09/react-native-true-sheet` from npm because yarn doesn't run `prepare` script as npm does and typescript complians

**Comment by Overtorment** [comment]
> I'm using `@lodev09/react-native-true-sheet` from npm because yarn doesn't run `prepare` script as npm does and typescript complians

maybe the solution is to run `prepare` on a fork, and commit it to the forked repo?

**Comment by marcosrdz** [comment]
> > I'm using `@lodev09/react-native-true-sheet` from npm because yarn doesn't run `prepare` script as npm does and typescript complians
> 
> 
> 
> maybe the solution is to run `prepare` on a fork, and commit it to the forked repo?

We use a forked repo. Its under BW

**Review by Overtorment — APPROVED** [review]
LGTM. YOLO

**Comment by Overtorment** [comment]
weird, why circleci is not on a listof checks

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Comment by Overtorment** [comment]
> > > I'm using `@lodev09/react-native-true-sheet` from npm because yarn doesn't run `prepare` script as npm does and typescript complians
> > 
> > 
> > maybe the solution is to run `prepare` on a fork, and commit it to the forked repo?
> 
> We use a forked repo. Its under BW

yes, so i proposed trying to run `npm prepare` on a forked repo, its gona build, and then force-commit the buillt folder to repo

**Comment by limpbrains** [comment]
> LGTM. YOLO

I messaged you about it

**Comment by limpbrains** [comment]
> weird, why circleci is not on a listof checks

I messaged you about it

**Pull request merged**
