### PR TITLE
REF: Use button instead of icons to unlock

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4fvjasvwzwdvmuc4i2g4cmx7ti?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/774)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/flhjjuokfzaevuqowlsllpsk4y?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/775)

**Review by Overtorment — COMMENTED** [review]
lgtm, but lint complains that  `Unused loc key: loc._.unlock`

**Comment by marcosrdz** [comment]
Fixed conflicts

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
