### PR TITLE
ADD: main view SCAN button can now import watch-only wallets (closes …

### PR DESCRIPTION
**Pull request by Overtorment**
…#2817)

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ad6ka00hq0qrjd0ugvgu3vatu8

[download apk](http://filestorage.bluewallet.io:1488/fix-2817-1616246020.apk)

**Comment by marcosrdz** [comment]
Why not use WalletImport processImport function directly?

**Comment by Overtorment** [comment]
> Why not use WalletImport processImport function directly?

havent looked in there, don't know if it has error handling etc..? and it adds temp wallet card..?
this way we just piggy-back on existing functionality. if we want we can even let the user to press the import button as a confirmation.

**Review by marcosrdz — APPROVED** [review]

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
