### PR TITLE
ADD: opt-out of analytics tracking in settings/privacy (rel #3084)

### PR DESCRIPTION
**Pull request by Overtorment**
added a switch in settings/general/privacy to disable tracking.
should prevent sending data to amplitude & sentry.

@marcosrdz pay attention to how I used context, I might have done it wrong 

image

### CODE REVIEW

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/utb3qmc3u70fc32hpnkme36w7r?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/add-privacy-opt-out-1620403750.apk)

**Comment by Overtorment** [comment]
@marcosrdz can you pls do your pod magic on this one..? ios build failed

**Review by limpbrains — APPROVED** [review]
Great feature to have!

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Comment by Overtorment** [comment]
@ncoelho feel free to send a pr with the correct texts instead of

```
    "privacy_do_not_track": "Do Not Track",
    "privacy_do_not_track_explanation": "Some anonymized analytics and debug data won't be sent to analytics service.",
```

before next release

**Pull request merged**
