### PR TITLE
OPS: use npm@7 (closes #3080)

### LINKED ISSUE #3080: Use newer lockfileVersion > 1 (newer Lockfile format for package-lock.json)
https://github.com/BlueWallet/BlueWallet/blob/59b2fa5a50c58b9569bacc1d94d62c4fc70c82b8/package-lock.json#L4
old format of package-lock.json is used (`"lockfileVersion": 1`), npm 7 released with newer lockfile format, more details in links:
https://github.blog/2021-02-02-npm-7-is-now-generally-available/#changes-to-the-lockfile
> The lockfile v2 unlocks the ability to do deterministic and reproducible builds to produce a package tree.

https://nitayneeman.com/posts/catching-up-with-package-lockfile-changes-in-npm-v7/

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by limpbrains** [comment]
Too early. It doesn't work for current nodejs LTS stable v14. 
Next Active release will be v16 in October 2021, then we should switch.

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Pull request closed without merging**
