### PR TITLE
REF: LDK Open Channel flow

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8ak8wy04n4j57r524x3cnw2ch8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8517)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bzq5p6pnfxn36z2nfxqb1bct74?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8518)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5qyyw0vye120jdgfxxbf3xrn5g?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8519)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/q6nw24dc02qa1bu615u0b1y1xw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8551)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/neetp85n6f85cr7jf9dnp03xcw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8587)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kvaaquqe5zq5c2tavxk2xx49nr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8588)

**Comment by marcosrdz** [comment]
Probably needs some UI love but it uses the correct Modal process.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qag8z29zwdq5h4r33v46neeabw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8589)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/q2e5dxvw7yunrmdd3wrzb0m4jw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8590)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/308ny6zk7zmu9f5cd7n87zza40?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8594)

**Review by Overtorment — CHANGES_REQUESTED** [review]
tests failed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u0fzb0ada5g9ettxkucg9qhk8c?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8600)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/b1q0x0ypxrmh553d380ktxghrr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8601)

**Comment by marcosrdz** [comment]
> tests failed

Synced with master

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Pull request merged**
