### PR TITLE
Add Italian language

### PR DESCRIPTION
**Pull request by davidullo**

### CODE REVIEW

**Comment by Overtorment** [comment]
needs work

**Comment by davidullo** [comment]
> needs work

I already made the a pull request for the complete translation, what am I missing?

**Comment by Overtorment** [comment]
if you look into `changes` youll see that `it.js` file is missing. also, circleci fails

**Comment by ncoelho** [comment]
it.js is on another PR, can you make all the commits into a single PR?

there's 3 files you need to change on a translation. Hope it helps, we can do this 💪 

- loc/index.js
- loc/new_translation_you_are_creating.js
- screen/settings/language.js

**Comment by davidullo** [comment]
Okay I'll try to do it 👍

**Pull request closed without merging**
