### PR TITLE
Fix exchange rate providers

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Review by marcosrdz — CHANGES_REQUESTED** [review]
Swift file also needs an update

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zrrjqe6vonf2226xuda3hym3dq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10831)

**Comment by Overtorment** [comment]
@marcosrdz can we merge this and you update swift file later?

**Review by marcosrdz — APPROVED** [review]

**Comment by marcosrdz** [comment]
> @marcosrdz can we merge this and you update swift file later?

Its gonna cause a crash on widgets on builds once its merged but ill update it

**Comment by marcosrdz** [comment]
Note so its not forgotten:

I think we store the actual fiat object along with its source so anyone updating will have coindesk in their asyncstorage

**Review by marcosrdz — CHANGES_REQUESTED** [review]
Update code to handle source changes

**Review by limpbrains — APPROVED** [review]

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
