### PR TITLE
ADD: show message if no wallets has been found during the import

### PR DESCRIPTION
**Pull request by limpbrains**
изображение

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/c597atzj858449bwx4m84mq1tg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8461)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
