### PR TITLE
REF: Remove error-prone random placeholder scroll calculation

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rxf7m1qeghxmzhtk1kp4aqh0xg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7324)

**Review by Overtorment — APPROVED** [review]
lgtm. 
tested a bit on appetize, works. except small glitch that when you create new wallet it's card is a bit offsetted on x axis

**Comment by marcosrdz** [comment]
@Overtorment  fixed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ztjy80pa8d8mchd1w9ba3gjawg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7325)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/upy47xjrp323pzefafhxp7aeqc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7328)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/48u5mcjwqke4xh52jj3t0fc6dc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7331)

**Pull request merged**
