### PR TITLE
ADD: Process notifications when app state changees to foreground

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ujpd747cz1zjz76v4141942x6r

[download apk](http://filestorage.bluewallet.io:1488/1609211268.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tgxwpq5ephgdpbkbvf7an1j4kw

[download apk](http://filestorage.bluewallet.io:1488/1609283324.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rddhzv7c6z8ccn9rdvyaaddjz0

[download apk](http://filestorage.bluewallet.io:1488/1609295296.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
