### PR TITLE
REF: Use menu package since showPopmenu is being removed

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by Overtorment** [comment]
New dep? Elaborate

**Comment by marcosrdz** [comment]
Access to uimanager show popup was removed on rn 74. This is the package that is now assigned to it

**Comment by marcosrdz** [comment]
https://github.com/facebook/react-native/pull/42441

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by marcosrdz** [comment]
> New dep? Elaborate 

Rn iOS context menu package will be removed once this package's iOS code matures to the same level

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
