### PR TITLE
ADD: Settings > Clear Cache

### PR DESCRIPTION
**Pull request by marcosrdz**
This will make it easy to clear the cache.

Simulator Screenshot - iPhone 15 Pro Max - 2024-05-17 at 22 33 41

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6bntunio5wfqmm7qthrcnuvbz4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1631)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — CHANGES_REQUESTED** [review]
when do we need cache cleared?

**Comment by marcosrdz** [comment]
> when do we need cache cleared?

Look at attached issue plus when Realm gets corrupted(personally has happened to me)

**Comment by marcosrdz** [comment]
> when do we need cache cleared?

Also can happen on Mac due to the freedom of being able to downgrade

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
