### PR TITLE
REF: Use nav prop for statusbar

### PR DESCRIPTION
**Pull request by marcosrdz**
Let RNScreens/RNav handle status bar instead of waiting for the Component's render call.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6os7rih7q22b3k3en4qu64amne?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11672)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j52dnce46ziaoyryzgyrk6rxpq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11673)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xwawmv7ak6lo7xcmipdnn2242y?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11674)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4n6ukpac7rd5ktg5327s5qd3ou?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11675)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7eymchlkh6zmeasqbxocbtrlqe?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11677)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nu2e3q3be4h2p7rhy3pfighp5q?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11679)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4kbizgn4zogistx43qciq4siue?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11680)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tawjktgjustpbnopy3phq3td2m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11682)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
