### PR TITLE
FIX: correctly save data if wallets are big, >1500 txs (closes #1319)

### LINKED ISSUE #1319: Too big keys saved to storage (>16 mb)
Sentry Issue: [BLUEWALLET-1S8](https://sentry.io/organizations/bluewallet/issues/1599571634/?referrer=github_integration)

```
Error: {"message":"error saving key"}
  at setItem (class/app-storage.js:76:31)
  at call (class/app-storage.js:400:17)
  at callImmediates (app:///[native code])
  at value (app:///[native code])
  at value (app:///[native code])
...
(14 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/p5evpcawznuq1155rw4wd83b2c

[download apk](http://filestorage.bluewallet.io:1488/1593783358.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8cgvfzxqwyh7yvp3dv0tekrcam

[download apk](http://filestorage.bluewallet.io:1488/1593796095.apk)

**Comment by Overtorment** [comment]
ok ive tested it on real device, and with a bunch of huge wallets (4k+ transactions) this works, but not very nicely: slow & crashes

**Comment by Overtorment** [comment]
@limpbrains @marcosrdz  what are your thoughts on this?

Ive looked into realm.io & watermelondb and inclined to use pure db engine instead, probably sqlite. I found this https://github.com/andpor/react-native-sqlite-storage
are there any other options?
we need to offload _transactions only_, probably  rows consisting of walletid and json data, probably encrypted.

**Pull request closed without merging**
