### PR TITLE
FIX: Expand useExtendedNavigation

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by Lostthought1 — APPROVED** [review]

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Lostthought1] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Lostthought1

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Lostthought1] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Lostthought1

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Lostthought1] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Lostthought1

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Lostthought1] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Lostthought1

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Lostthought1] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Lostthought1

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Lostthought1] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Lostthought1

**Pull request merged**
