### PR TITLE
REF: Use NavigationContainer Ref for NavigationService

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gtmq55u0u5et2ydeuvtq5bfj4g

[download apk](http://filestorage.bluewallet.io:1488/1592526997.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/r3cmeqhw1e4hk02w7p1j1vmv5r

[download apk](http://filestorage.bluewallet.io:1488/1592567655.apk)

**Comment by Overtorment** [comment]
@marcosrdz are you going to write an e2e test for deeplinks?

**Comment by marcosrdz** [comment]
> @marcosrdz are you going to write an e2e test for deeplinks?

Its on my todo list

**Pull request merged**
