### PR TITLE
FIX: Response handling for Widget

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/re3u8b8kftbwatr50jewd9nq30

[download apk](http://filestorage.bluewallet.io:1488/1604804053.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z0e8xu0e5v2hy1v9w3h86e8kg8

[download apk](http://filestorage.bluewallet.io:1488/1604804804.apk)

**Review by Overtorment — APPROVED** [review]

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3vjw8nw497b3c0h7ak7jwn5w48

[download apk](http://filestorage.bluewallet.io:1488/1605029372.apk)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
