### PR TITLE
ADD: Telegram and Discord links on about section

### PR DESCRIPTION
**Pull request by ncoelho**

### CODE REVIEW

**Review by marcosrdz — APPROVED** [review]

**Review by limpbrains — COMMENTED** [review]
If you decided to remove github link, it is better to remove  `about_sm_github` from `loc/en.json` or it will remain there forever.

**Review by marcosrdz — CHANGES_REQUESTED** [review]
Remove github?

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uqwmm8zyxgnfpxk3j5x7h0k0yc

[download apk](http://filestorage.bluewallet.io:1488/1608400117.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4u0u3f5rcj6jndm0h0maqa2p38

[download apk](http://filestorage.bluewallet.io:1488/1608403584.apk)

**Review by Overtorment — APPROVED** [review]

**Review by limpbrains — APPROVED** [review]

**Review by marcosrdz — APPROVED** [review]

**Pull request merged**
