### PR TITLE
OPS: Upgrade to RNav 6

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/a52buv65k293k94c73z3qhdzb4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8304)

**Review by Overtorment — COMMENTED** [review]
lgtm

**Comment by marcosrdz** [comment]
e2e failed. Gotta address it

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zvm3ddbuprbp9cz6rpcv8gptdc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8390)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/d6rcj5rk6na38f8k9ekyd4c0jg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8683)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/etn68tykwj16d4q6jy7kuy3y68?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8685)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/v0d6bxrtqkch0z4yp94df4fv6m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8687)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mzr5epzvvk5ex2pvz0fwcke0kc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8691)

**Comment by Overtorment** [comment]
still fighting e2e?

**Comment by marcosrdz** [comment]
> still fighting e2e?

Yeah looks like the RNav changes are more significant then just simply updating some things here and there. Ill continue to tackle this screen by screen

**Comment by Overtorment** [comment]
@marcosrdz is this pr still needed?

**Pull request closed without merging**
