### PR TITLE
REF: remove old and untranslated values from loc files

### PR DESCRIPTION
**Pull request by limpbrains**
I'm cleaning loc json files by deleting old and untranslated strings 
It is needed for #2288

### CODE REVIEW

**Comment by Overtorment** [comment]
how do you find old values? 
I would write a script for that

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1w300jfa6k34cyjqp0u8ztu8dw

[download apk](http://filestorage.bluewallet.io:1488/1607534730.apk)

**Comment by limpbrains** [comment]
> how do you find old values?
> I would write a script for that

I've downloaded json from transifex which contains only translated strings. And then removed empty strings using:
```js
const fs = require('fs')
const path = require('path')
const stringify = require('json-stable-stringify')

const dir = '/Users/limpbrains/b/BlueWallet-orig/loc'

fs.readdirSync(dir).forEach(name => {
  const file = path.join(dir, name)
  if (name === 'en.json' || !name.endsWith('.json')) return

  const data = require(file)

  // remove empty strings
  Object.entries(data).forEach(([secName, secValues]) => {
    Object.entries(secValues).forEach(([key, string]) => {
      if (string === '') delete secValues[key]
    })
  })

  // remove empty sections
  Object.entries(data).forEach(([secName, secValues]) => {
    if (Object.keys(secValues).length === 0) delete data[secName]
  })

  // save to json
  const json = stringify(data, { space: '  ' }) + '\n'
  fs.writeFileSync(file, json)
})
```

**Comment by Overtorment** [comment]
ready for merge?

**Comment by limpbrains** [comment]
Yes

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1rnzcy9h01jf8k3h06vwtxa0j0

[download apk](http://filestorage.bluewallet.io:1488/1607581088.apk)

**Review by Overtorment — APPROVED** [review]
lgtm. btw, I would also write a script to purge unused translations. basically, grab all keys from en.json and grep if its used in `screen/` (we always import localization as `loc`)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
