### PR TITLE
ADD: Keychain clear

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e3n9qkp4105wz4vxkkzd31pqf0

[download apk](http://filestorage.bluewallet.io:1488/1594861970.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qyt5vqqaw83f9v5kqqz8fmgy9m

[download apk](http://filestorage.bluewallet.io:1488/1594956261.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3zf36fu98y269cbcfak99nr3r0

[download apk](http://filestorage.bluewallet.io:1488/1594956965.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/v194afw8m5vabhprx9q2drh5m8

[download apk](http://filestorage.bluewallet.io:1488/1595120887.apk)

**Comment by marcosrdz** [comment]
> me gusto

Yo quiero taco bell

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f9jvm47kgqz58f3h5brx4b5c34

[download apk](http://filestorage.bluewallet.io:1488/1595256040.apk)

**Pull request merged**
