### PR TITLE
DEL: Remove blur package. Use builtin solution

### PR DESCRIPTION
**Pull request by marcosrdz**
Simulator Screen Shot - iPhone 12 - 2021-09-12 at 01 10 12

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/71v25g5vax3fuw0vgen8e75g5m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8258)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vg8vgc3rfzv9fvac2hjt4n6wzm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8261)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ryudd86vx8jn25q658uu4n329m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8263)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @ncoelho] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/ncoelho

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
fuk yea

**Pull request merged**
