### PR TITLE
FIX: Remove whitespace and minus character when copying amount

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uz9g0xwbkpttqv3u16z3tny72m

[download apk](http://filestorage.bluewallet.io:1488/tooltip-1614363938.apk)

**Review by limpbrains — APPROVED** [review]

**Review by Overtorment — APPROVED** [review]

**Comment by Overtorment** [comment]
E2e failed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1g1fu19jtkhurwe8gfhyfvuuem

[download apk](http://filestorage.bluewallet.io:1488/tooltip-1614383149.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/aty9avax0nrupbvy4hndzpwhmr

[download apk](http://filestorage.bluewallet.io:1488/tooltip-1614441478.apk)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
