### PR TITLE
Update build-ios-release-browserstack.yml

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hlc6icdin277qf3v477iyd5mbm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/691)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kpv4bxkvawlgh2ra4sqd6hzmhu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/692)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tx6a5smk2ognwgw23r5mzhdgle?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/693)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/eggxvh75aslx6iuummrizc2nmu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/697)

**Comment by Overtorment** [comment]
@marcosrdz still wip?

**Pull request closed without merging**
