### PR TITLE
ADD: Manual trigger of TF upload

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/g2z764stfb4euqgvn6mpvbn43e?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12176)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gzb32uliw5mtgun667wozomi6a?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12179)

**Comment by Overtorment** [comment]
@marcosrdz is this ready for merge? how do i trigger the upload?

**Comment by marcosrdz** [comment]
> @marcosrdz is this ready for merge? how do i trigger the upload?

I could be wrong, but I read that you have to first merge this into master before being able to use it

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3d4ezauqlktwtuqttscmlyhusm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/270)

**Comment by marcosrdz** [comment]
> is this ready for merge?
> 
> conflicts btw

Yup

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
