### PR TITLE
OPS: dYSM

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dbvwqce2q66yv4n33j0pecq544?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8171)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bexezgug7bz68bagz66pe3e6aw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8184)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by Overtorment** [comment]
fuck it. lets merge and see what happens. i tried validating pod lock file against yaml validator and it said all good, so probably just snyk bitchin

**Pull request merged**
