### PR TITLE
ADD: Native segwit as default wallet

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/yt55d96zdndvtj64kxp08kzbar

**Comment by Overtorment** [comment]
otherwise lgtm

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/8kerr1qu10np5tr431w3pn2u9c

**Comment by marcosrdz** [comment]
> 1. deepscan bitchin

fixed.

> 2. scanQrWif should be modified as well. so default fallback, if no transactions found, should be bip84

It was already giving bip84 priority

> 3. same for import  textbox screen (forgot the name)

Moved bip84 as priority.

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/er7q32573grk1nqx1j778q0pz0

**Pull request merged**
