### PR TITLE
Limpbrains remove inline styles

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gg9rnd2ezaqpu9w06mfw1wa1q4

[download apk](http://filestorage.bluewallet.io:1488/1590399753.apk)

**Comment by Overtorment** [comment]
@ncoelho can you run through the build to make sure nothing is visually broken pls?

**Comment by Overtorment** [comment]
@ncoelho ^^^

**Comment by ncoelho** [comment]
All good 👍

**Pull request closed without merging**
