### PR TITLE
ADD: redeem Azte.co vouchers

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by Overtorment** [comment]
azteco fail

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uzq1nvfabj8jnud34znt509x64

[download apk](http://filestorage.bluewallet.io:1488/1590159206.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pmhmt0x6g19qgbhb501hqr0av4

[download apk](http://filestorage.bluewallet.io:1488/1590171968.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pwa7b0qg07mp9kvb1319xq997w

[download apk](http://filestorage.bluewallet.io:1488/1590242010.apk)

**Pull request merged**
