### PR TITLE
FIX: Polish Receive screen

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/buk49m428jrv3c8xcx093mrwe8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8036)

**Comment by Overtorment** [comment]
o kurwa

**Review by Overtorment — APPROVED** [review]
ja pierdole

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
