### PR TITLE
OPS: Rate package replacement

### PR DESCRIPTION
**Pull request by marcosrdz**
Package has isAvailable method to determine wether to display button or not based on GMS availability

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]

**Comment by Overtorment** [comment]
i assume this fixes https://github.com/BlueWallet/BlueWallet/issues/3577  ?

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j1hfa00xh355grk6tmmdag8gn8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7730)

**Comment by marcosrdz** [comment]
It won't. Its an enhancement. The bug in that ticket seems to be present in all Rate packages and its an Android-only issue. Verifying if theres a work around

**Comment by brettl-03** [comment]
Hey guys! What precisely am I looking to test with this one here? I downloaded the above APK and the "Leave us a review" button still remains unresponsive like before, and using the appetize link above and attempting to access/press the "Leave us a review" button produces the following error message - 
2021-08-12 13-01-52 High Res Screenshot

**Comment by marcosrdz** [comment]
Shall we just send the user to the product page on Android until this API is fixed? @Overtorment @ncoelho

**Comment by Overtorment** [comment]
yes, whatever works (and reduces number of deps)

**Pull request closed without merging**
