### PR TITLE
FIX: Some widgets were not showing on drawer

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7c7c7aw2tdgr3t1fhetaujp130

[download apk](http://filestorage.bluewallet.io:1488/widgetdrawer-1613530352.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ha3n59thhkpc1r3dzekqepa5n8

[download apk](http://filestorage.bluewallet.io:1488/widgetdrawer-1613538914.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cfhxtdjwn24gnrwav0u1brfqmm

[download apk](http://filestorage.bluewallet.io:1488/widgetdrawer-1613683622.apk)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
