### PR TITLE
FIX: wallet->receive->qr share as an image

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/new5vv2rc5nbrmusqv6snkdyqu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11345)

**Comment by marcosrdz** [comment]
@Overtorment E2e failed

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u2agfl5eatvt4k33gh3pblz56i?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11347)

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
