### PR TITLE
OPS:  RN Update

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]
Is it even worth it to bump to such minor version of rn..?

**Comment by marcosrdz** [comment]
> Is it even worth it to bump to such minor version of rn..?

Yup. two UI hangs fixes:

fix Symbol not found: (_JSGlobalContextSetInspectable
Fixed possible deadlock in dispatchViewUpdates

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bkh4ihuodozt3rr7kkytqhhs3e?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1499)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
