### PR TITLE
FIX: Multisig Forget alerts where visible after closing modal (macOS)

### PR DESCRIPTION
**Pull request by marcosrdz**
Screenshot 2024-03-08 at 11 47 09 PM

Screenshot 2024-03-09 at 12 02 41 AM

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zipmtpzesgp3xw2luzdktvl7zy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/722)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/64jkpvkbsnhc2amowsu5m7wbru?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/723)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/642miedjpw4ljw22ifz3titfgy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/724)

**Review by Overtorment — APPROVED** [review]
Lgtm. Nice comments

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
