### PR TITLE
[Snyk] Upgrade detox from 17.11.0 to 18.1.0

### PR DESCRIPTION
**Pull request by Overtorment**
<h3>Snyk has created this PR to upgrade detox from 17.11.0 to 18.1.0.</h3>

merge advice
:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

*Warning:* This is a major version upgrade, and may be a breaking change.
- The recommended version is **34 versions** ahead of your current version.
- The recommended version was released **24 days ago**, on 2021-01-06.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>detox</b></summary>
    <ul>
      <li>
        <b>18.1.0</b> - <a href="https://snyk.io/redirect/github/wix/Detox/releases/tag/18.1.0">2021-01-06</a></br><p>This release repatriates TypeScript definitions from DefinitelyTyped to the official Detox repo. (<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="777064998" data-permission-text="Title is private" data-url="https://github.com/wix/Detox/issues/2564" data-hovercard-type="pull_request" data-hovercard-url="/wix/Detox/pull/2564/hovercard" href="https://snyk.io/redirect/github/wix/Detox/pull/2564">#2564</a>)</p>
<p>Thanks to:</p>
<ul>
<li>Tareq El-Masri</li>
<li>Jeff Held</li>
<li>Steve Chun</li>
<li>Hammad Jutt</li>
<li>pera</li>
<li>Max Komarychev</li>
<li>Christian Bar</li>
<li>Henrik Raitasola</li>
<li>dbilgin</li>
<li>Dor Ben Baruch</li>
<li>Luis Naranjo</li>
<li>Martin Treurnicht</li>
<li>Martin Yrjola</li>
<li>Nick Pachulski</li>
<li>Simon Treny</li>
<li>Wesley Wigham</li>
</ul>
      </li>
      <li>
        <b>18.0.3</b> - <a href="https://snyk.io/redirect/github/wix/Detox/releases/tag/18.0.3">2021-01-05</a></br><p>Fixed crashes with map views on iOS.</p>
      </li>
      <li>
        <b>18.0.2</b> - <a href="https://snyk.io/redirect/github/wix/Detox/releases/tag/18.0.2">2021-01-04</a></br><p>18.0.2</p>
      </li>
      <li>
        <b>18.0.1</b> - <a href="https://snyk.io/redirect/github/wix/Detox/releases/tag/18.0.1">2021-01-03</a></br><p>18.0.1</p>
      </li>
      <li>
        <b>18.0.0</b> - <a href="https://snyk.io/redirect/github/wix/Detox/releases/tag/18.0.0">2020-12-29</a></br><p>Detox now uses a custom synchronization system on iOS, <a href="https://snyk.io/redirect/github/wix/DetoxSync">developed in-house</a>; this is the second step in phasing out our Earl Grey usage. We have tested this system extensively internally, and are confident that it should work as expected. There are no known limitations with the new system.</p>
<p>If you are seeing issues with the new sync system, please open an issue.</p>
      </li>
      <li>
        <b>18.0.0-next.9</b> - 2020-12-23
      </li>
      <li>
        <b>18.0.0-next.8</b> - 2020-12-20
      </li>
      <li>
        <b>18.0.0-next.7</b> - 2020-12-17
      </li>
      <li>
        <b>18.0.0-next.6</b> - 2020-12-09
      </li>
      <li>
        <b>18.0.0-next.5</b> - 2020-11-24
      </li>
      <li>
        <b>18.0.0-next.4</b> - 2020-11-21
      </li>
      <li>
        <b>18.0.0-next.3</b> - 2020-11-11
      </li>
      <li>
        <b>18.0.0-next.2</b> - 2020-11-04
      </li>
      <li>
        <b>18.0.0-next.1</b> - 2020-11-03
      </li>
      <li>
        <b>18.0.0-next.0</b> - 2020-11-03
      </li>
      <li>
        <b>18.0.0-alpha.0</b> - 2020-11-03
      </li>
      <li>
        <b>17.15.0-smoke.0</b> - 2020-12-21
      </li>
      <li>
        <b>17.14.9</b> - <a href="https://snyk.io/redirect/github/wix/Detox/releases/tag/17.14.9">2020-12-27</a></br><p>Added back --args to xcrun simctl launch, was wrongly removed in <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="770828453" data-permission-text="Title is private" data-url="https://github.com/wix/Detox/issues/2540" data-hovercard-type="pull_request" data-hovercard-url="/wix/Detox/pull/2540/hovercard" href="https://snyk.io/redirect/github/wix/Detox/pull/2540">#2540</a> (<a class="user-mention" data-hovercard-type="user" data-hovercard-url="/users/rotemmiz/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/rotemmiz">@ rotemmiz</a>, <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="775124214" data-permission-text="Title is private" data-url="https://github.com/wix/Detox/issues/2556" data-hovercard-type="pull_request" data-hovercard-url="/wix/Detox/pull/2556/hovercard" href="https://snyk.io/redirect/github/wix/Detox/pull/2556">#2556</a>)</p>
      </li>
      <li>
        <b>17.14.8</b> - 2020-12-27
      </li>
      <li>
        <b>17.14.6</b> - 2020-12-14
      </li>
      <li>
        <b>17.14.5</b> - 2020-12-13
      </li>
      <li>
        <b>17.14.4</b> - 2020-12-10
      </li>
      <li>
        <b>17.14.3</b> - 2020-12-03
      </li>
      <li>
        <b>17.14.1</b> - 2020-11-30
      </li>
      <li>
        <b>17.14.0</b> - 2020-11-29
      </li>
      <li>
        <b>17.13.2</b> - 2020-11-25
      </li>
      <li>
        <b>17.13.1</b> - 2020-11-23
      </li>
      <li>
        <b>17.13.0</b> - 2020-11-20
      </li>
      <li>
        <b>17.12.1-genycloud.0</b> - 2020-11-22
      </li>
      <li>
        <b>17.12.0</b> - 2020-11-17
      </li>
      <li>
        <b>17.11.5-smoke.0</b> - 2020-11-16
      </li>
      <li>
        <b>17.11.4</b> - 2020-11-12
      </li>
      <li>
        <b>17.11.2</b> - 2020-11-09
      </li>
      <li>
        <b>17.11.1</b> - 2020-11-08
      </li>
      <li>
        <b>17.11.0</b> - 2020-11-04
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/wix/Detox/releases">detox GitHub release notes</a>
  </details>
</details>

<details>
  <summary><b>Commit messages</b></summary>
  </br>
  <details>
    <summary>Package name: <b>detox</b></summary>
    <ul>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/b52a7c89d29e6eb8ad293bbd424cc4edf40a4387">b52a7c8</a> Publish 18.1.0 [ci skip]</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/027bf9c46b8bfa5fdafae616589624f8e8d23f2c">027bf9c</a> Merge pull request #2564 from wix/feat/typescript-defs</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/3c50e21c382b35bc0c55c24ae3379c12056d40e8">3c50e21</a> Merge branch &#x27;master&#x27; into feat/typescript-defs</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/acb6b633c2fed69f87d673fdd3426382ad54bca3">acb6b63</a> Update CODEOWNERS</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/edb13efcb665d7fd27348842ad89692d8b526a27">edb13ef</a> Publish 18.0.3 [ci skip]</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/970682df99e6743e4b4008e90068eeff9d12650f">970682d</a> DeviceRegistry to support all handle types (#2560)</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/d390b4eb19d25d42e59a48d51a4e2e5f5c2ef255">d390b4e</a> Use latest DetoxSync (#2570)</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/66a2cae5cb8d5864386a2348986d40c0e7dad933">66a2cae</a> Publish 18.0.2 [ci skip]</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/71a16fb9795b8a83c4fa5e41e4ae32f94a868bd4">71a16fb</a> Revert &quot;Latest DetoxSync&quot;</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/df513366da72b1539df8e21d4f1ca3b91e463b5b">df51336</a> Publish 18.0.1 [ci skip]</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/f77bc17a3af1d59453421b78f38c1a0264a471a0">f77bc17</a> Latest DetoxSync</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/802a13e468a32c50454b7d1eec3d8f0b3b1c8f26">802a13e</a> Merge pull request #2566 from jksaunders/master</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/eb8cec28e44fc3f970a969917a2c47964530e142">eb8cec2</a> Typo fix: mainting -&gt; maintaining</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/273189a429c7f37f23578c108e8c840af4018487">273189a</a> chore(examples): move Jest project to TS</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/2a7e10f479dfa7430cd198481d490f4e4b63b214">2a7e10f</a> chore(examples): move mocha project to TS</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/f37c4d280608ed7247221b556eec0ccd6d323a67">f37c4d2</a> feat: move in TypeScript definitions</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/042793a5764ff4a549fdab2edff77340facb16f3">042793a</a> Warn about Genycloud instances leakage in case of abrupt terminations (#2555)</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/7a9a6e1ac82088d6e96fe86d41a9a119b02d9dbd">7a9a6e1</a> Publish 18.0.0 [ci skip]</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/acba841cd230936cd02fe599345df8fde18172a7">acba841</a> Merge pull request #2198 from wix/DetoxNext</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/3e400ac50acc917f7cb227a7b7429b7d40ecaa8d">3e400ac</a> Merge branch &#x27;master&#x27; into DetoxNext</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/8288951cd17ad40d853c78923dd191b129cd8b55">8288951</a> chore: update snapshot</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/f71d2471d85b28b95f451e8836cf4d980830dff4">f71d247</a> docs: add minimal docs for --capture-view-hierarchy</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/6774567a0eca1a765ca95a8b93d95ff1a1f52c83">6774567</a> feat(cli): --capture-view-hierarchy &lt;enabled|disabled&gt;</li>
      <li><a href="https://snyk.io/redirect/github/wix/Detox/commit/5e1c5653526160813773793a6fbe11054a4144ec">5e1c565</a> Update Guide.Migration.md</li>
    </ul>

   <a href="https://snyk.io/redirect/github/wix/Detox/compare/8fe90edb68d7fa12d362bbb8ff92fb4bd848a2ee...b52a7c89d29e6eb8ad293bbd424cc4edf40a4387">Compare</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/bluewallet/project/4d0df22a-0152-410a-8584-6df0d0a596d4?utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/bluewallet/project/4d0df22a-0152-410a-8584-6df0d0a596d4/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/bluewallet/project/4d0df22a-0152-410a-8584-6df0d0a596d4/settings/integration?pkg&#x3D;detox&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yxrvg6gvxdwae8hc5dtymk8kfg

[download apk](http://filestorage.bluewallet.io:1488/snyk-upgrade-d2a3e2c11a157ff6a0f52fd526e27454-1611986621.apk)

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Review by marcosrdz — APPROVED** [review]

**Comment by Overtorment** [comment]
weird. why PR was created under my username, and not snyykbot

**Comment by marcosrdz** [comment]
> weird. why PR was created under my username, and not snyykbot

It is slowly becoming more self aware. Its becoming more human

**Pull request merged**
