### PR TITLE
FIX: Restore icons on ListItem

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]
Lgtm, but some tests failed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4z6kasq5f3yrrustqcygolutri?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12256)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gyzcv3xufwaqjaizmuyudiffze?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12257)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
