### PR TITLE
FIX: Dim nonselected wallets on additional screens

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/extn8j1hjmp55u28yy330a3t3r

[download apk](http://filestorage.bluewallet.io:1488/1605465143.apk)

**Review by ncoelho — APPROVED** [review]

**Review by Overtorment — CHANGES_REQUESTED** [review]
conflict

**Comment by marcosrdz** [comment]
> conflict

Resolved.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/te4qbxxr2kyn66qj6p6wmm4c2c

[download apk](http://filestorage.bluewallet.io:1488/1605643063.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
