### PR TITLE
ADD: fiat input

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n99cqk9kjq8d2196za7qa93twg

[download apk](http://filestorage.bluewallet.io:1488/1591357888.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ydcn5qvv1cahpubaw5yckbg4uw

[download apk](http://filestorage.bluewallet.io:1488/1591375730.apk)

**Comment by Overtorment** [comment]
ready for text. lots of work went into this, surprisingly it was very tricky to make and account for all possibilities. please test carefully, and if something is not right - write precise steps to reproduce.

@marcosrdz can you pls review code thoroughly? there were lots of conflicts and Im afraid this PR has changes that are not supposed to be here.

i will post here a list of my own testcases on this feature. btw, maybe we should start writing testcases on our wiki?

**Comment by Overtorment** [comment]
test cases

* [ ] receive ln
* [ ] ln - send - scan invoice - with amount
* [ ] --// -- without amount (zero sat inv)
* [ ] lapp browser - tipping me
* [ ] deepling ln invoice - with amt
* [ ] --//-- without amt
* [ ] onchain - receive with amt
* [ ] onchain - send 
* [ ] onchain - batch send (all outs different units)
* [ ] onchain - deeplink with amt while wallets default unit is set to NON-btc (sat or fiat)
* [ ] onchain - scan bip21 qr

**Comment by limpbrains** [comment]
- Change currency to RUB. 
- Switch input to fiat, you can see *$* sign in front of the input, not ₽
- It is possible to enter any characters while input is fiat.
- Enter 1 RUB, press switch 3 times, you will have 100 RUB

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4wweezvk0j7k5nx68yvy9fud40

[download apk](http://filestorage.bluewallet.io:1488/1591630726.apk)

**Comment by Overtorment** [comment]
@limpbrains fixed all except any characters input - on real device virtual keyboard displays only numbers. can you pls take a look?

**Comment by limpbrains** [comment]
Well, you can attach keyboard to phone or tablet, right? Also, when input in BTC, I can't enter nothing but valid numbers, but when in RUB or SATS I can.

You still can copy-paste non number values to the input.

There is still a bug with factual amount of RUB. Enter "0.99", switch 2 times and you will get "099"

**Comment by limpbrains** [comment]
I can enter "0.0.1" as a value for fiat field, I think it should not be possible

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n93bfbtx7qwj96hxrq9aq1jpvg

[download apk](http://filestorage.bluewallet.io:1488/1591639215.apk)

**Comment by Overtorment** [comment]
fixed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/p9vbd7z324cpqwded0rzx35kn0

[download apk](http://filestorage.bluewallet.io:1488/1591699134.apk)

**Comment by ncoelho** [comment]
Centered the UI. 

Seems usable, the only weird thing are the dots and letters not being validated. But doesn't seem something to stop a release for.

**Comment by limpbrains** [comment]
> fixed

You still can enter non digits if the input is empty. Everything else is good

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/w50vmejqjqcjk248cepuuy71x0

[download apk](http://filestorage.bluewallet.io:1488/1591710799.apk)

**Pull request merged**
