### PR TITLE
FIX: Bech32 Wallet as default

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/z50uvyfwz5d5k0dnwy7gx2x0uw

**Comment by Overtorment** [comment]
I glanced and looks like the diff is bigger than it should be. 
And second, qr and textfield import fixes are missing. It should fallback to importing bip84 if no txs found (atm it fallbacks to bip49)

**Comment by marcosrdz** [comment]
> I glanced and looks like the diff is bigger than it should be.


I moved the wrapped wallet option to where the bech32 was. and vice verse. lint was complaining about setState being called with 3 parameters, instead of 2. I removed that third parameter.

> And second, qr and textfield import fixes are missing. It should fallback to importing bip84 if no txs found (atm it fallbacks to bip49)

Pulled from master.

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/87uztkgjb3p698379cpujw437g

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/9ax0dpxwncr1qpca42hehf73g0

**Comment by Overtorment** [comment]
?

**Comment by ncoelho** [comment]
?

**Pull request closed without merging**
