### PR TITLE
REF: Status Bar on android with native style

### PR DESCRIPTION
**Pull request by ncoelho**
Adds native style for android StatusBar in light and dark themes, on the initial screen and list screen.

Screenshot 2021-03-11 at 14 09 01

### CODE REVIEW

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rv0bf5x2c47knvx8u6jnk7fun8

[download apk](http://filestorage.bluewallet.io:1488/statusbarandroid-1615469144.apk)

**Comment by limpbrains** [comment]
@ncoelho you can run `npm run lint:fix` and it will auto format source files and show eslint errors if any exists.

**Review by limpbrains — APPROVED** [review]

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5d4xmt0mmz4dxum49r7kw1e2jc

[download apk](http://filestorage.bluewallet.io:1488/statusbarandroid-1615557693.apk)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
