### PR TITLE
REF: app-storage class

### PR DESCRIPTION
**Pull request by Overtorment**
not sure if this refactoring is worth merging, need your oppinion

* renamed AppStorage to BlueApp and moved to class folder. 
* made it Singleton
* old blueapp.ts removed, added `blue_modules/start-and-decrypt.ts` that has only one method - `startAndDecrypt()` - absolutely cannot refactor it, when i try to make it a method in BlueApp class typescript starts throwing weird errors  due to cyclic dependencies. but i recon its still cleaner, and if we evenrually fix cyclic dependencies it willbe easier to refactor `startAndDecrypt()` as well
* moved `initCurrencyDaemon();` to the same place where we connect

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/m4qqllqqu5ms5fobb6elutcwli?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1178)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nz4x6j32ogoxxdpjwezuqmbucm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1188)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7ezzqffqe5upsyzcqke2y5unym?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1190)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tausefq6yich4satqt6q3mv4ey?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1193)

**Comment by limpbrains** [comment]
I like BlueApp more than AppStorage

**Review by limpbrains — APPROVED** [review]

**Review by marcosrdz — APPROVED** [review]

**Pull request merged**
