### PR TITLE
ADD: Fetch txs when Push is received (Android)

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nxtxxmb2dn1xq09m0vnehb6vhr

[download apk](http://filestorage.bluewallet.io:1488/1608370147.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0b25e6ud9dd00b6dqnmxjncfwg

[download apk](http://filestorage.bluewallet.io:1488/1608398559.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/c9hgxw0u7cbn9vbtyk2qawxvj8

[download apk](http://filestorage.bluewallet.io:1488/1608422113.apk)

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ktncgpywgepgem1mxk5yaxuq00

[download apk](http://filestorage.bluewallet.io:1488/1608482356.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9ze17mcxwggcnrkjbbgf8a5bb4

[download apk](http://filestorage.bluewallet.io:1488/1608720001.apk)

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
