### PR TITLE
OPS: Refactor Main Lists

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5mwkaadjhzhrz44w12dpfj4cgw

[download apk](http://filestorage.bluewallet.io:1488/1589680224.apk)

**Comment by Overtorment** [comment]
image

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/y4y1a88zm88765z2akn83e431m

[download apk](http://filestorage.bluewallet.io:1488/1589718497.apk)

**Comment by Overtorment** [comment]
all travis e2e tests failed. either run detox locally or you can go to travis, click `./tests/e2e/upload-artifacts.sh` and download videos from the run to see whats happening there.

**Comment by Overtorment** [comment]
And btw this is technically not OPS, it’s REF

**Comment by marcosrdz** [comment]
> And btw this is technically not OPS, it’s REF

Ooopsss

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mxphgtb48vjek8d87xdwg6twpw

[download apk](http://filestorage.bluewallet.io:1488/1589733511.apk)

**Pull request merged**
