### PR TITLE
FIX: Notification toggle was stopped by an undefined object

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bgdgx7hy6czx73rh3q6l2fwceu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1812)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5xar5olkyvu3nlm6ksrr7mgcwu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1813)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
