### PR TITLE
ADD: Handle fiat rate from alternate sources

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cc9j1rt3kyw9vdqwtyhr3g45n4

[download apk](http://filestorage.bluewallet.io:1488/1605840044.apk)

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1b2tcj1014981v24g0au49muyr

[download apk](http://filestorage.bluewallet.io:1488/1605927580.apk)

**Comment by marcosrdz** [comment]
Ok so both the app and widgets can now read from alternate sources. We just gotta confirm the key/value we need to read  for VES and ARS

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5gvb33zrxjctq8664e2q4yenug

[download apk](http://filestorage.bluewallet.io:1488/1605932812.apk)

**Comment by marcosrdz** [comment]
I used https://yadio.io/calc.html to compare data. seems to be working.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tkqk22xq64jucz7jjw15jtp4mc

[download apk](http://filestorage.bluewallet.io:1488/1605935422.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kmrpj9qeqgdpxhyddk9ab2xevc

[download apk](http://filestorage.bluewallet.io:1488/1606004087.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7yjkzbhg1durj8r0jjkq145n8w

[download apk](http://filestorage.bluewallet.io:1488/1606004900.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6pqv9txext8dxxat8kc9pfnfer

[download apk](http://filestorage.bluewallet.io:1488/1606007407.apk)

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
