### PR TITLE
FIX: Updating en.json to correct minor errors and add consistency 

### PR DESCRIPTION
**Pull request by mcsaeid**

### CODE REVIEW

**Comment by mcsaeid** [comment]
I’m not sure how to proceed. Lacking coding knowledge.

**Comment by marcosrdz** [comment]
Please sync up with upstream master

**Comment by mcsaeid** [comment]
I synced my fork just now if that is what you meant.

**Review by Overtorment — APPROVED** [review]
LGTM!
@limpbrains all good on your side?

**Comment by limpbrains** [comment]
Let me guess: chatgpt?

**Review by limpbrains — APPROVED** [review]

**Comment by marcosrdz** [comment]
E2e failed. Might need to update the .spec files to match ur correction @mcsaeid

**Comment by mcsaeid** [comment]
> E2e failed. Might need to update the .spec files to match ur correction

I went through all three files and made sure they matched the revisions in en.json. Let me know if that fixes it. Otherwise, please advise.

> Let me guess: chatgpt?

If you mean the improvements, I did them all manually.

**Pull request merged**
