### PR TITLE
FIX: Bottom inset hook no longer needed with new SafeArea

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/h7hblf4vyvrclfqdpiybdhf5oi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/86)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rdmvolvnigy7xcom47grr7ol5q?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/89)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/to2pryysqvlf4i76skszsaqrd4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/91)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
