### PR TITLE
feat: Entropy refactor

### LINKED ISSUE #6344: Generate seed with 12 words using entropy
I have try generate a seed using 12 words with entropy and got a issue that I cant do that, because its on hard code to generate only 24 words size

image
image
image

### PR DESCRIPTION
**Pull request by limpbrains**
- convert provideEntropy to typescript
- allow 12 or 24 words 

[entropy.webm](https://github.com/BlueWallet/BlueWallet/assets/155891/a7a25152-a347-4789-ae30-e7ddbec91e7f)

closes #6344

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/h6io5tuqlo5ibe24l6rx25wlaq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1145)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ov7q24u7kxun63takt357emvia?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1177)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/oajhuuw34d3xxtds6hdri25dry?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1194)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uf7vlbn7mfjecin4uj6ru2ylly?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1257)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cyst2nyl74vejbjlxjkvws5uim?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1324)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tzxf23utxsvpz5hehiclr3qymi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1326)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bmdckqiaj64uyei3esmwpfglce?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1334)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ylexb3yovalvkbb3hxfshcxylq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1820)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/olt5rc77s3ljv7iktgqg5vgmdu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1821)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/p3copdxz7y4hli25s7kqpopiju?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1822)

**Review by marcosrdz — CHANGES_REQUESTED** [review]
Please Rename file to ProvideEntropy.tsx to follow React component standards

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cjng2wyxqavfb52vti3w7oq6oy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1823)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
