### PR TITLE
Lazy

### PR DESCRIPTION
**Pull request by marcosrdz**
Gotta go stack by stack...the goal? dont mount the whole app on boot.

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wy5ochgduod6utnkloj23oedcy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1482)

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/32bjcfmzbf6x3nlabk5y3r4xn4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1484)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/futtrqdq4r274br6sck7jwyfsa?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1485)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/q4peqasx24w4rwulfidjar2zj4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1486)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zlh2kg754mea5m6g4cebclcevy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1488)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cf3npnhbjo4znm3bh4k3d4sl5y?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1494)

**Comment by Overtorment** [comment]
@marcosrdz tests failed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/eiciy4dbrqfj4o6l7o4ovk7f4q?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1498)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yijcd7wlh37qfdmjrxeeywwb54?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1511)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j4yk33kjo3zmf5a2mv5fgakj6m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1513)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qtntv7kcmuoaq6tgjfmjbi5xbe?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1515)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rwodovcc3gu6irayddu6hju73y?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1520)

**Pull request merged**
