### PR TITLE
FIX: Double app icon

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/c6j47sun25jkr33jl37we6cl3a?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/337)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Comment by bereanbitcoiner** [comment]
Duplicate icon issue still affecting Android 14.
https://appetize.io/app/c6j47sun25jkr33jl37we6cl3a?device=pixel6&osVersion=14.0

**Comment by marcosrdz** [comment]
> Duplicate icon issue still affecting Android 14. https://appetize.io/app/c6j47sun25jkr33jl37we6cl3a?device=pixel6&osVersion=14.0

The top shelf is most Most Used/Recent apps. You can see there are other apps in there that show up at the bottom too. The bug has been fixed with this PR

**Comment by marcosrdz** [comment]
> Duplicate icon issue still affecting Android 14. https://appetize.io/app/c6j47sun25jkr33jl37we6cl3a?device=pixel6&osVersion=14.0

Screenshot 2024-02-05 at 10 53 06 AM

**Pull request merged**
