### PR TITLE
REF: Aligned buttons on MultiSig flow

### PR DESCRIPTION
**Pull request by ncoelho**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0v6g4ja9wr7kg0m84rptz459v4

[download apk](http://filestorage.bluewallet.io:1488/1604577549.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qdxaek1hxr43pbd5h6hh03dvjc

[download apk](http://filestorage.bluewallet.io:1488/1604594887.apk)

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jef0vxzzkh9v6n0p5uqjyeuea4

[download apk](http://filestorage.bluewallet.io:1488/1604600335.apk)

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
