### PR TITLE
REF: Splash Screen

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gxnojpr26a7k5rdzwyijbdl7ee?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/232)

**Review by Overtorment — APPROVED** [review]
RIP boot animation

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/sgg4hamb553ngfkhcadtakvyky?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/233)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kxtf4giiyedbxhhjcplivynyzm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/234)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
