### PR TITLE
REF: New button design

### PR DESCRIPTION
**Pull request by marcosrdz**
**Based on latest Figma design** 

Screenshot 2024-04-14 at 8 14 33 PM
Screenshot 2024-04-14 at 8 14 37 PM

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e4eruw5zw2t2nv7p23r7gidmh4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1182)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Review by Overtorment — APPROVED** [review]
lgtm

**Review by limpbrains — APPROVED** [review]
looks weird :)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
