### PR TITLE
FIX: import single-sig wallet descriptor (closes #5637)

### LINKED ISSUE #5637: BUG: Scan of singlesig descriptor QR from Sparrow Wallet not working
This descriptor QR export from @SparrowWallet is not imported:

image

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6d6hjv2vwpfbsjkjoi7d5yjb5y?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11485)

**Comment by marcosrdz** [comment]
E2e failed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/od7ljrjhpbcesrgtclksczrbge?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11487)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
