### PR TITLE
REF: react hooks

### PR DESCRIPTION
**Pull request by Overtorment**
@marcosrdz can you take it from here?
used this guide https://medium.com/sparkswap/hundreds-of-lightning-users-are-at-risk-of-losing-funds-3-things-you-need-to-keep-your-btc-safe-ad5d3272d19b
but I failed to fix some hooks

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mtv07x41adnajydeqt6ycy1mkm

[download apk](http://filestorage.bluewallet.io:1488/1584533365.apk)

**Comment by Overtorment** [comment]
@marcosrdz ^^^

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hx7afbj1tnmarezpyvwxaryu9c

[download apk](http://filestorage.bluewallet.io:1488/1585663190.apk)

**Comment by Overtorment** [comment]
linting still fails

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/g2kyq2k1enxrxxm0ke9d4aew4m

[download apk](http://filestorage.bluewallet.io:1488/1585846570.apk)

**Pull request merged**
