### PR TITLE
REF: switch dep to in-org

### PR DESCRIPTION
**Pull request by Overtorment**
* deleted `package-lock.json` - its not needed anymore..?
* switched `@lodev09/react-native-true-sheet` to forked one.  on forked one i pushed the built folder forcefully, so no `npm prepare` needed

### CODE REVIEW

**Review by limpbrains — APPROVED** [review]

**Comment by limpbrains** [comment]
Can't believe I forgot to remove the old lock file 😅  
Probably messed up during rebase.

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Comment by Overtorment** [comment]
Unbelievable. You, @limpbrains, must be a pride of [subject hometown here]!

**Comment by Overtorment** [comment]
there will be a cake

image

**Pull request merged**
