### PR TITLE
REF: enable hermes (andr); bump & fix reanimated

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by Overtorment** [comment]
@marcosrdz plz enable hermes for ios

**Comment by Overtorment** [comment]
https://reactnative.dev/docs/hermes

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3u4gxv3ywdzdjf4mh2vyg0kzyr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9865)

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
