### PR TITLE
ADD: Do not show notification settings if device does not support it.

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uupdqt6456750k54c7p2jzaj8r

[download apk](http://filestorage.bluewallet.io:1488/notifcapable-1611373066.apk)

**Review by Overtorment — APPROVED** [review]

**Review by Overtorment — CHANGES_REQUESTED** [review]
```
 FAIL  tests/integration/notifications.test.js
  ● Test suite failed to run

    TypeError: (0 , _reactNativeDeviceInfo.hasGmsSync) is not a function

      30 |   };
      31 | 
    > 32 |   Notifications.isNotificationsCapable = hasGmsSync() || hasHmsSync() || Platform.OS !== 'android';
         |                                                                                ^
      33 |   /**
      34 |    * Calls `configure`, which tries to obtain push token, save it, and registers all associated with
      35 |    * notifications callbacks

      at new Notifications (blue_modules/notifications.js:32:80)
      at Object.<anonymous> (tests/integration/notifications.test.js:4:34)

Test Suites: 1 failed, 13 passed, 14 total
```

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/73etrwc2nvmnx6gy4gx948du64

[download apk](http://filestorage.bluewallet.io:1488/notifcapable-1611591075.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
