### PR TITLE
[WIP] BIP-47 feature implementation

### LINKED ISSUE #2883: Bip47 & Reusable Payment Codes version 3 & 4
Since we are getting closer to TOR Support, it would be great to get additional support for privacy enhancing features.
Colloquial, PayNyms.
These are specified in Bip47  as implemented by Samourai and enhanced in https://github.com/OpenBitcoinPrivacyProject/rfc/blob/master/obpp-05.mediawiki
Having more wallets support this, would benefit the ecosystem in general.

### PR DESCRIPTION
**Pull request by spsina**
According to the [BIP47 document](https://github.com/OpenBitcoinPrivacyProject/rfc/blob/master/obpp-05.mediawiki), the following core functionality is required:

- Generate payment code from seed
- Initialize a payment code from base58 payment code
- Derive notification addresses
- Derive public keys from a payment code and a notification private key
- Derive public keys from a payment code and a notification public key
- Derive P2PKH addresses from a payment code and notification private key
- Derive P2Pkh addresses from a payment code and notification public key

Fortunately,[ Dojo full node source code ](https://code.samourai.io/dojo)has implemented all the above functionally. Specifically in these projects [bip-47-tool](https://code.samourai.io/dojo/bip47-tool) and [bip47-js](https://code.samourai.io/dojo/bip47-js).
We could directly make use of bip47-js functions and use the bip47-tool project to double-check our implementation. We may implement any other behavioral functionality that we may need independently.

We will be able to derive BIP-47 compatible addresses from BIP-39 Mnemonic Seeds which should be enough to enable portability among other wallets like SamuraiWallet.

Paynyms which are implemented by SamuraiWallet will not be implemented here. Instead, users will be able to simply share their unique “Payment Code”. If paynym-like behavior is desired, a separate public directory needs to be developed.

We are a team of 3, working together for around 4 years and doing research and contribution to blockchain projects for around a year
Our team consists of an experienced designer (https://dribbble.com/Beigi) an experienced Frontend and React Native developer (https://github.com/alimahdiyar) and a backend developer(https://github.com/spsina/)

fixes #2883

### CODE REVIEW

**Comment by decentralizedb** [comment]
> According to the [BIP47 document](https://github.com/OpenBitcoinPrivacyProject/rfc/blob/master/obpp-05.mediawiki), the following core functionality is required:
> 
> * Generate payment code from seed
> * Initialize a payment code from base58 payment code
> * Derive notification addresses
> * Derive public keys from a payment code and a notification private key
> * Derive public keys from a payment code and a notification public key
> * Derive P2PKH addresses from a payment code and notification private key
> * Derive P2Pkh addresses from a payment code and notification public key
> 
> Fortunately,[ Dojo full node source code ](https://code.samourai.io/dojo)has implemented all the above functionally. Specifically in these projects [bip-47-tool](https://code.samourai.io/dojo/bip47-tool) and [bip47-js](https://code.samourai.io/dojo/bip47-js). We could directly make use of bip47-js functions and use the bip47-tool project to double-check our implementation. We may implement any other behavioral functionality that we may need independently.
> 
> We will be able to derive BIP-47 compatible addresses from BIP-39 Mnemonic Seeds which should be enough to enable portability among other wallets like SamuraiWallet.
> 
> Paynyms which are implemented by SamuraiWallet will not be implemented here. Instead, users will be able to simply share their unique “Payment Code”. If paynym-like behavior is desired, a separate public directory needs to be developed.
> 
> We are a team of 3, working together for around 4 years and doing research and contribution to blockchain projects for around a year Our team consists of an experienced designer (https://dribbble.com/Beigi) an experienced Frontend and React Native developer (https://github.com/alimahdiyar) and a backend developer(https://github.com/spsina/)
> 
> fixes #2883

One question.
It's not clear if this implementation could be compatible and interact with the Samourai implementation (and what I think Sparrow is also doing)?

**Comment by librepgp** [comment]
The Samourai wallet is already capable of scanning a Payment Code directly (without the Nym)

**Comment by spsina** [comment]
> One question.
It's not clear if this implementation could be compatible and interact with the Samourai implementation (and what I think Sparrow is also doing)?

the goal is to be able to interact with all the wallets that implement [BIP47](https://github.com/OpenBitcoinPrivacyProject/rfc/blob/master/obpp-05.mediawiki)

**Comment by apemithrandir** [comment]
Is it possible to incorporate the http://paynym.is directory?

**Comment by alimahdiyar** [comment]
> Is it possible to incorporate the http://paynym.is directory?

As discussed in the group, paynym is not included in Bip47 and also, not included in this PR.

**Comment by jhumphr3y** [comment]
Paynym is just a directory of existing payment codes. If you don't want to include the directory I guess whatever, people will just have to look them up, but by default those payment codes are bip47 compatible

**Comment by mcsaeid** [comment]
LaurentMT
Follow the thread [here](twitter.com/LaurentMT/status/1495822668637122571).

**Comment by pointbiz** [comment]
What about a feature to have a local address book of payment codes with user added labels so you can have a handy list of your contacts (exchanges, friends) payment codes?

**Comment by pointbiz** [comment]
Can Electrum protocol scan for version 3 payment codes (Pubkeys in a bare multisig)?

**Comment by spsina** [comment]
> What about a feature to have a local address book of payment codes with user added labels so you can have a handy list of your contacts (exchanges, friends) payment codes?

The overall design will still be similar to how paynyms work. the client can even set custom names for payment codes that it knows about.

**Comment by apemithrandir** [comment]
FYI [Sparrow Wallet](https://github.com/sparrowwallet/) have implemented a working PayNym implementation in their desktop wallet since version 1.6.0. No bounty for [Craig Raw](https://github.com/craigraw) but his contribution will hopefully be acknowledged via some after the fact donations.

With Sparrow Wallet we now have PayNym access on Android, Windows, MacOS and Linux. Would great to keep the momentum going and see BlueWallet provide iOS the same access.

**Comment by spsina** [comment]
Quick update: I'm developing core bip-47 utility functions in a separate repo. We will use that module here once done, and it's almost done.
you can follow the progress here: [BIP47](https://github.com/spsina/BIP47)

**Comment by alimahdiyar** [comment]
Hi
We studied the Bip47 proposal completely and discussed the implementation.

Here's what we think about the flow for creating "Stealth Wallet" for Bip47 and its homepage:

https://www.figma.com/file/L5nYqhcFNcRqvbiM4Y5I2d/BlueWallet---clone?node-id=1309%3A10351

Please share with us if you have any opinion on this

**Comment by yoshimo** [comment]
> Please share with us if you have any opinion on this

The more subwallets we create that the user has visible on his home screen the less usable it becomes.
Samourai just has one and has the different derivation paths in the background. Ricochet, Toxic Change, mixed stuff, and so on.
I think one wallet for each set of seed words with all related derivation paths would be more userfriendly.

**Comment by decentralizedb** [comment]
> The more subwallets we create that the user has visible on his home screen the less usable it becomes.
> Samourai just has one and has the different derivation paths in the background. Ricochet, Toxic Change, mixed stuff, and so on.
> I think one wallet for each set of seed words with all related derivation paths would be more userfriendly.

I think along the same way. More wallets are less usable and less interesting for users.
I think it is better that the privacy options are by default, with the option for users, if they want not to use it, working with other types of implementations such as Segwit addresses or others.

**Comment by librepgp** [comment]
> Please share with us if you have any opinion on this

The stealth wallet design is superb.

It will be interesting to see the 'receive' and 'send' screen from this bip47 stealth wallet.

**Comment by pointbiz** [comment]
> Hi We studied the Bip47 proposal completely and discussed the implementation.
> 
> Here's what we think about the flow for creating "Stealth Wallet" for Bip47 and its homepage:
> 
> https://www.figma.com/file/L5nYqhcFNcRqvbiM4Y5I2d/BlueWallet---clone?node-id=1309%3A10351
> 
> Please share with us if you have any opinion on this

This seems like the right approach according to bip standards. Wallets with mixed address derivations (BIP44, 49, 84) are not following the standard as each seed should lead to a single derivation path in the context of 44, 49, 84.

BIP47 has different scanning the blockchains costs and techniques. So, Stealth Wallet should be something you setup new and intentionally even if that decreases network effect. This feature should not burden the non stealth wallets IMHO.

If version 4 is used that would mean the new stealth wallets derivation under BIP47 path and BIP84 P2WPKH. That's my understanding of the BIP.

**Comment by beigiz** [comment]
@yoshimo @decentralizedb @librepgp @pointbiz Thanks for your feedback!
I'm the UIUX designer of this feature. 
The idea of creating a new wallet for BIP47 (aka stealth wallet) was because I thought (based on what others inform me) we have restrictions to implement it as a Mode. However, I designed another approach for the scenario, which we can implement this feature on standard wallets (called Stealth Mode). It's a Mode that users can toggle and enter. Note that it's incomplete, and I need to add the follower/following section later.

you can see it here:
https://www.figma.com/file/L5nYqhcFNcRqvbiM4Y5I2d/BlueWallet---clone?node-id=1309%3A10351

We make sure which way we can implement this feature and choose one of the two approaches.

**Comment by beigiz** [comment]
@yoshimo @decentralizedb @librepgp @pointbiz Thanks for your feedback!
I'm the UIUX designer of this feature.
The idea of creating a new wallet for BIP47 (aka stealth wallet) was because I thought (based on what others inform me) we have restrictions to implement it as a Mode. However, I designed another approach for the scenario, which we can implement this feature on standard wallets (called Stealth Mode). It's a Mode that users can toggle and enter. Note that it's incomplete, and I need to add the follower/following section later.

you can see it here:
https://www.figma.com/file/L5nYqhcFNcRqvbiM4Y5I2d/BlueWallet---clone?node-id=1309%3A10351

We check if having Stealth as a mode is implementable or not and choose one of the two approaches accordingly.

**Comment by pajasevi** [comment]
@spsina What do you mean by "safely"? What was the issue?

**Comment by decentralizedb** [comment]
> @spsina What do you mean by "safely"? What was the issue?

Yeah, could you comment on more details? What's the problem?

**Comment by apemithrandir** [comment]
@spsina was it a technical issue or were the team at BlueWallet unwilling to integrate the Bip47 features?
The bounty was quite large on this, it is unfortunate to see you and anyone else who spent time on this not get anything.

**Comment by spsina** [comment]
@alimahdiyar can provide more details.

**Comment by alimahdiyar** [comment]
I was trying to integrate the BIP47 feature in the wallet classes but there were a lot of hacks in there. We were not sure that if we change some pieces of code, the other pieces will still work fine. I think the maintainers should refactor the code before adding any other features.

**Comment by librepgp** [comment]
That's a shame. Thank you still for trying it out.

I'll try to figure out this feature by myself then.

**Comment by decentralizedb** [comment]
> I was trying to integrate the BIP47 feature in the wallet classes but there were a lot of hacks in there. We were not sure that if we change some pieces of code, the other pieces will still work fine. I think the maintainers should refactor the code before adding any other features. @pajasevi @decentralizedb @apemithrandir

I guess the maintainers are aware of the code issues?
Have they commented if they plan to do something? I guess they won't do anything and that's why you are closing the PR

As @librepgp  said, it's a shame.

I think we should continue to insist on BW for this integration.
Thank you!

**Comment by alimahdiyar** [comment]
> > I was trying to integrate the BIP47 feature in the wallet classes but there were a lot of hacks in there. We were not sure that if we change some pieces of code, the other pieces will still work fine. I think the maintainers should refactor the code before adding any other features. @pajasevi @decentralizedb @apemithrandir
> 
> I guess the maintainers are aware of the code issues? Have they commented if they plan to do something? I guess they won't do anything and that's why you are closing the PR
> 
> As @librepgp said, it's a shame.
> 
> I think we should continue to insist on BW for this integration. Thank you!

Well, I think refactoring this code won't be easy at all. There are many TODOs in the code's comments for that purpose. And the code base isn't completely migrated to Typescript. There are so many if statements to handle different wallet types (instead of separating the different parts into distinct functions and components)
Architecting the code base for BIP47 is hard by itself. And with problems in this source code, we found it even harder to do.

**Comment by ncoelho** [comment]
This sounds like an excuse. There's 0 problems on the codebase, it is extremely clean and easy to ready. If you can't implement it, it's ok, no one is judging you. But you choose the wrong codebase to complain about...

**Comment by alimahdiyar** [comment]
> This sounds like an excuse. There's 0 problems on the codebase, it is extremely clean and easy to read. If you can't implement it, it's ok, no one is judging you. But you choose the wrong codebase to complain about...

Well, we don't care about judgments. I explained the problems that we faced and I think maintainers should try refactoring and making the source better, rather than defending. I think it's even good to set a bounty for refactoring.
Also, we closed the issue and published the library so that someone else might try to implement this.
Good luck

**Pull request closed without merging**
