### PR TITLE
Update fiatUnits.json

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by Overtorment** [comment]
looks like you changed coindesk to coingecko without checking that new api has same keys

**Comment by Overtorment** [comment]
in case of JPY, it has same key but key in response is in lowercase for some reason. fixin it

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ihxlaub76f25w724aqcpbwyyre?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11167)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
