### PR TITLE
Phrazzld rm safebluearea custom styles

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by ncoelho** [comment]
This branch has a weird loading on the transaction view. 

https://user-images.githubusercontent.com/1238429/111619427-db36e300-87e5-11eb-9c1a-d94fa457262f.mov

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uq53tjygr8ht5nr3ngx3beek7c

[download apk](http://filestorage.bluewallet.io:1488/phrazzld-rm-safebluearea-custom-styles-1616068191.apk)

**Comment by limpbrains** [comment]
> This branch has a weird loading on the transaction view.
> Screen.Recording.2021-03-18.at.12.30.55.mov

This is not related to the current branch. Same thing happens on master

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ahy89q1hzuj2j3j7krezq42n9w

[download apk](http://filestorage.bluewallet.io:1488/phrazzld-rm-safebluearea-custom-styles-1616160927.apk)

**Pull request closed without merging**
