### PR TITLE
Viewinvoicehooks

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/v23gcf4p02gg7btjmkjmx1kwur

[download apk](http://filestorage.bluewallet.io:1488/1606193935.apk)

**Review by Overtorment — APPROVED** [review]
eslint bitchin, but overal lgtm

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7y8g4q3c323d3cq7j89vcztyng

[download apk](http://filestorage.bluewallet.io:1488/1606270782.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/emrc86fnud2uhd347kd7azqpd4

[download apk](http://filestorage.bluewallet.io:1488/1606321723.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1hy7k55wngvx62qhtehgc01rcw

[download apk](http://filestorage.bluewallet.io:1488/1606443979.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tuv83h61807bd3tatx74xedndr

[download apk](http://filestorage.bluewallet.io:1488/1606499746.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/meqxjfbh1yuj3qrhzy0z1hteng

[download apk](http://filestorage.bluewallet.io:1488/1606510864.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pbuvnwzr2aa28zw2kez1xtknv4

[download apk](http://filestorage.bluewallet.io:1488/1606533502.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yrexcpybntnczqg8vyaqhcdb60

[download apk](http://filestorage.bluewallet.io:1488/1606535317.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1zwfrvza34dpe3ex8j0cvg3uc8

[download apk](http://filestorage.bluewallet.io:1488/1606540982.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0a6dqf1659z9c3h8wh0m829m64

[download apk](http://filestorage.bluewallet.io:1488/1606576598.apk)

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
