### PR TITLE
REF: Remove useRef for transactions list

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/p1nwq2daxa8c28dvuyyadekrqm

[download apk](http://filestorage.bluewallet.io:1488/refwallet-1612416815.apk)

**Review by Overtorment — APPROVED** [review]
lgtm but needs some testing

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kv69bfyufa2ey9vn1u9f7z8adw

[download apk](http://filestorage.bluewallet.io:1488/refwallet-1613840891.apk)

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
