### PR TITLE
FIX: correctly work with addresses funded by coinbase transactions

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ok4pibe7arxntyoch2yi6k347e?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12302)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pnt5neeubup47gwy7mcyktcqyu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/12303)

**Review by marcosrdz — APPROVED** [review]

**Review by limpbrains — APPROVED** [review]

**Comment by limpbrains** [comment]
Will BW be able to spend such output? ( If I remember correctly, it is only doable after 100 blocks)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Comment by Overtorment** [comment]
> Will BW be able to spend such output? ( If I remember correctly, it is only doable after 100 blocks)

Good question. BW is not aware of such delay, so worst case scenario user just waits and tries again

**Pull request merged**
