### PR TITLE
OPS: Update packages for xcode 12

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0265q4xz8bhxphcczvjdgt4chw

[download apk](http://filestorage.bluewallet.io:1488/1600388101.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9tjyzgyju8m7m4tz4v46d89yuc

[download apk](http://filestorage.bluewallet.io:1488/1602197369.apk)

**Comment by marcosrdz** [comment]
@Overtorment  updated packages that reported fixing xcode 12 build issues.

**Comment by marcosrdz** [comment]
LN Webview injection works.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j8pg48ngqe2tudxqcq46gxxmbw

[download apk](http://filestorage.bluewallet.io:1488/1602204298.apk)

**Pull request merged**
