### PR TITLE
REF: WidgetCommunication to TSX

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/q2yf3jw3lrnhkgp3gospshic7m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1102)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uhlen75twti4njchylzjyhkrpi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1103)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tb2wi3zxztx2ha673cmbwgl6ma?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1106)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — CHANGES_REQUESTED** [review]
conflict due to recent BlueElectrum refactoring

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/oagqyuqtgxfrs7r33fbcvaoik4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1116)

**Pull request merged**
