### PR TITLE
FIX: Reduced batchsize to prevent "undefined" error when retrieving transactions

### PR DESCRIPTION
**Pull request by mgurzenski**
This batchsize change allowed me to retrieve transactions for the following 2 wallet addresses without receiving an undefined exception.
34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo
18rnfoQgGo1HqvVQaAN4QnxjYE7Sez9eca

### CODE REVIEW

**Comment by Overtorment** [comment]
What exactly was throwing undefined?

**Comment by Overtorment** [comment]
And have you tried values between 40 and 60?

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/abudc4dyutfnpf6pd2zzdmpquw

[download apk](http://filestorage.bluewallet.io:1488/1589927770.apk)

**Comment by mgurzenski** [comment]
> What exactly was throwing undefined?

When legacy-wallets.fetchTransactions() is looping through the values returned by BlueElectrum.multiGetTransactionByTxid() into the "txdatas" variable, some values are undefined when the batchsize is 61. 

image

**Comment by mgurzenski** [comment]
> And have you tried values between 40 and 60?

49 was the largest batchsize that worked for one of my test wallets. My thought was to set it to 40 to give a decent buffer.

**Comment by Overtorment** [comment]
Im guessing the issue is the same as I had once, batch reply from electrum is too big.
this is very rare case, so lets keep batchsize as big as possible, until next time we will have to revise it. 

ps. huge transactions are usually batched payouts from exchanges, and my precious value of 61 already accounted for some of the biggest txs Ive seen.

**Comment by mgurzenski** [comment]
> Im guessing the issue is the same as I had once, batch reply from electrum is too big.
> this is very rare case, so lets keep batchsize as big as possible, until next time we will have to revise it.
> 
> ps. huge transactions are usually batched payouts from exchanges, and my precious value of 61 already accounted for some of the biggest txs Ive seen.

That makes sense. Thanks for the background!

**Comment by Overtorment** [comment]
thanks for the pr!

**Pull request merged**
