### PR TITLE
REF: UnlockWith handle all scenarios of auth

### PR DESCRIPTION
**Pull request by marcosrdz**
Be more explicit about the UI state options and dont assume a default. 

Fix iOS keychain swipe on forgotten encryption password

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zsqfalvbsd6vcfgj3wm2skmkie?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/548)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bau77ju3oxctzd5lftsvwz7bnm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/559)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Review by Overtorment — APPROVED** [review]

**Comment by Overtorment** [comment]
ios build failed..?

**Comment by marcosrdz** [comment]
> ios build failed..?

Need to update the runner used

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ysjm6pwbk3yq3nwm3jrxp5qlpy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/564)

**Review by limpbrains — APPROVED** [review]

**Pull request merged**
