### PR TITLE
REF: useStorage useCallback and useMemo

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/orsudbalsgjyshtaq7aj6bbszy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1563)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/lwwdeauopktztt6yhu4wdhizn4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1568)

**Review by limpbrains — APPROVED** [review]

**Review by Overtorment — CHANGES_REQUESTED** [review]
not it feels a bit too much.

whats the point of those useCallbacks?

i dont want to remember to  type `.current` for all the properties  like `txMetadata.current`

**Comment by marcosrdz** [comment]
> not it feels a bit too much.
> 
> 
> 
> whats the point of those useCallbacks?
> 
> 
> 
> i dont want to remember to  type `.current` for all the properties  like `txMetadata.current`
So if it called again and the items in the depends array havent changed it'll return the last obtained value instead of refetching

**Comment by marcosrdz** [comment]
> not it feels a bit too much.
> 
> whats the point of those useCallbacks?
> 
> i dont want to remember to type `.current` for all the properties like `txMetadata.current`

Addressed the .current issue

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/snlphnopule3m6ghgxinymbxae?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1573)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5hfa4tpxawczrgppr3vjrbukxe?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1683)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
