### PR TITLE
FIX: Don't render sidebar if not on large device

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e2v48zqgb6701vf18ja9hcydpg

[download apk](http://filestorage.bluewallet.io:1488/1601520839.apk)

**Review by ncoelho — APPROVED** [review]

**Comment by ncoelho** [comment]
LGTM

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/njauy3fq442v0za37pg7qcamjr

[download apk](http://filestorage.bluewallet.io:1488/1601936094.apk)

**Review by Overtorment — APPROVED** [review]
lgtm

**Pull request merged**
