### PR TITLE
OPS: Package fixes

### PR DESCRIPTION
**Pull request by marcosrdz**
fixes that merit update

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e6pwakx3eanwqp00myyencyq18?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/packageup-1624395695.apk)

**Review by Overtorment — CHANGES_REQUESTED** [review]
tests failed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5t1xccnvnjbuv2jb3edt10bmy0?device=pixel4

[download apk](http://206.189.62.190:1488/packageup-1624462862.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/t0n5f19r7z3jgvty46fpfzg76r?device=pixel4

[download apk](http://206.189.62.190:1488/packageup-1624466807.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by Overtorment** [comment]
fixes wot m8?

**Comment by marcosrdz** [comment]
Sentry. The one in prod had a bug in promise return

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
