### PR TITLE
New Local Trader area on Main view

### PR DESCRIPTION
**Pull request by ncoelho**
This PR does 4 things in the 4 different commits:
1 - Cleaner add wallet panel payout and replaces "create" with "add"
2 - Local Trader on the main view
3 - Onchain marketplace goes to wallet details
4 - Sell fiat button goes to the List header

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/98netrr9816fakndq2ufbxyjn4

[download apk](http://filestorage.bluewallet.io:1488/1587045305.apk)

**Comment by Overtorment** [comment]
@ncoelho conflicts

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6tffgn4p6h11r0c7c4w1bfvwu0

[download apk](http://filestorage.bluewallet.io:1488/1587394639.apk)

**Comment by ncoelho** [comment]
@Overtorment fixed

**Comment by Overtorment** [comment]
@ncoelho conflicts

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tyj8w2p22a0y889guqwfeffzz0

[download apk](http://filestorage.bluewallet.io:1488/1588093928.apk)

**Pull request merged**
