### PR TITLE
REF: Use tooltip menu for SendDetails on Android

### PR DESCRIPTION
**Pull request by marcosrdz**
Needs a release with this merged:
https://github.com/react-native-menu/menu/pull/872

## Summary by CodeRabbit

- **New Features**
	- Enhanced menu state handling for improved flexibility.
	- Updated transaction handling for better user experience in the SendDetails component.
	- Introduced optimized event handling for improved performance and responsiveness.

- **Bug Fixes**
	- Improved responsiveness to updates in wallet state.

- **Chores**
	- Removed unused localization key to simplify the user interface.
	- Updated package dependency to a specific commit for potential enhancements.
	- Refactored UI test interactions to improve clarity and maintainability.

### CODE REVIEW

**Comment by limpbrains** [comment]
Deepscan error

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by marcosrdz** [comment]
> Deepscan error

Fixed

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
