### PR TITLE
DEL: Remove inappbrowser package.

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9wkdr3mr2a4xumq1xg7yty5dkc?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/inappbrowser-1622267943.apk)

**Review by limpbrains — APPROVED** [review]

**Review by Overtorment — APPROVED** [review]
lgtm but conflicts. 
would need to test it first to make sure apple pay works.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gw3d9m4k3nfjmwdmhu0q3r8ue4?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/inappbrowser-1622314539.apk)

**Comment by marcosrdz** [comment]
Conflicts resolved

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7ncqjg3yvxw3z5hdkgtgdmrpvg?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/inappbrowser-1622325494.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cwqnj6uggq6uhf21vhpejgm4t8?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/inappbrowser-1622341777.apk)

**Pull request merged**
