### PR TITLE
OPS: Unable to create aab (android bundle) #4235

### PR DESCRIPTION
**Pull request by marcosrdz**
Screen Shot 2022-02-20 at 1 53 07 PM

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/m8hy9fa6eu9tuxqmkrxhw79910?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9612)

**Review by Overtorment — APPROVED** [review]
noice!

**Comment by Overtorment** [comment]
@marcosrdz do you want to automate android builds on GA? I feel like this is a right time for this, so maybe we can ditch appcenter (at least for android builds).
only issue might arise with keystore file that we cant commit to public repo

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
