### PR TITLE
Nfc [WIP]

### PR DESCRIPTION
**Pull request by marcosrdz**
WIP

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/marm5fb2uc9qhgjgy65rkbd86r

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/gyh7674gmnvj57fe050ytp8zx4

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/jkxm24gjex35a0a1g6zbkbbxxr

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/gp72zm55802vt85zcq78xgvvrc

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/1yy6bhq66pkazmzdkw8nd2vcqg

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/u3e1camz15b6q68kjyrqj99yqm

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/ur746g1dqjhubfv50vm6tb8rhm

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/w9nt9uuyrxg18nn24n77g6gexw

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/v8x3cu1rpdb9dqv54duw41rc3g

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/5nnb6n2e8k1rjxmtffdg4wg128

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/ra1dyfyqamewfnj3g0y9jkfdhg

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/pupequzwtdh6q8kr7nr6pedbe0

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/jqgby2dp0kyccdn8t6crpcu7zw

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/5p949dfdqk2cfw0pphndj00008

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/g8jg5d4tcyhykwfpt17e2y0egc

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/dbrz8jmdparfgug7h482857jp4

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/k6ff5npyt06m87a97fb96486nw

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/9e64ag80pndx88dmz2nq3yq0p8

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/mwx509yy5g7zkfqj8wzrejyf1r

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/2gdy73tcwmckqg0kcnf3akv240

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/2k414bvgz4z14p1wwha8b0r1x0

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/2ejhhebp7gjfdvcykjk6kewcwc

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/hjan27h0q1pumrxtzjv15bd9q0

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/37fkr9dk8uy4q6vcrw438dtnw0

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wawm1gaf7jm9b3wcq0mm60uprg

[download apk](http://filestorage.bluewallet.io:1488/1577157640.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0wvkwcn357ydqmgweq0tx5fdr8

[download apk](http://filestorage.bluewallet.io:1488/1577329903.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/53e246anpeyc7n3m2mtr32p93r

[download apk](http://filestorage.bluewallet.io:1488/1577413517.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6939jm1v268hp48nfrad8cz200

[download apk](http://filestorage.bluewallet.io:1488/1577417868.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/um389ecxmahgq6rypmerzufuy8

[download apk](http://filestorage.bluewallet.io:1488/1577423618.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yhvjjg7ckzcg4ryn589tejqv34

[download apk](http://filestorage.bluewallet.io:1488/1577473466.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k8w8c5k0v20ka31m1vx0fkxj2w

[download apk](http://filestorage.bluewallet.io:1488/1593746285.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/m9vfkq6mfmzdt5t0qyrenvaf18

[download apk](http://filestorage.bluewallet.io:1488/1593963100.apk)

**Comment by Overtorment** [comment]
before I read throught tons of diffs, what are we trying to achieve here?

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x4pv5mpzwx1wgek0qyn6kwj2vg

[download apk](http://filestorage.bluewallet.io:1488/1596412075.apk)

**Comment by Overtorment** [comment]
cleanup

**Pull request closed without merging**
