### PR TITLE
FIX: Tooltip was in ocassions missing styles

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z4355y6zsldiiuq3p6lb7jeekm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1747)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dm6el447xoztxgczc35jqcoqf4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1762)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/l4yhu3vwbf3s5bok72ihz2hbna?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1763)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
