### PR TITLE
TST: fix java version for ci e2e

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Review by marcosrdz — APPROVED** [review]
Gah damn

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z4tsujxnl6r4cia4cdcmrqjgwy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1319)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4h3tfwd63nhv5hhg566qkjnniy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1320)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rjja6da3inn2whqirlhymv47oi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1325)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cmj72gzcvcj4lxnejciwjhtdqa?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1327)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qg45cpaf4cmpid52gcvhjvirfy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1328)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/plenhdgbt6ccyw7jgazm53p6hm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1329)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qb4vcp5xkyvckv2czvtgi4hh2q?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1330)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/lzvk2fc7rmchvflmlselb4ko4m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1333)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/faraffdxadlppl5cddq234hoqa?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1336)

**Pull request closed without merging**
