### PR TITLE
DEL: Update Info.plist

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5p3pccchjewefxldp3ussiewyi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11736)

**Review by Overtorment — CHANGES_REQUESTED** [review]
iOS build failed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2xr7b46fnwdaqcm7kwj6fgoegi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11738)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
