### PR TITLE
OPS: Special characters broke file path

### PR DESCRIPTION
**Pull request by marcosrdz**
## Summary by CodeRabbit

- **New Features**
	- Enhanced APK naming logic to ensure valid characters in filenames.
	- Added conditional changelog generation for iOS uploads based on branch name.

- **Bug Fixes**
	- Improved error handling for keystore preparation and file conversion processes.

- **Chores**
	- Updated build workflow for better artifact handling and branch name sanitization.

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]

**Review by Overtorment — CHANGES_REQUESTED** [review]
Build apk failed

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
