### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qy7mxuk991xe9ch4q8pn0ba574

[download apk](http://filestorage.bluewallet.io:1488/1583438006.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vbzjxzntpmfpk1j3pa3kty1a2c

[download apk](http://filestorage.bluewallet.io:1488/1583512106.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uh8vwqfyabpe07tkx2wt5pp1hm

[download apk](http://filestorage.bluewallet.io:1488/1583518808.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jn00zfhyam7nkf484dyv64wy04

[download apk](http://filestorage.bluewallet.io:1488/1583683318.apk)

**Comment by Overtorment** [comment]
@marcosrdz wouldnt it be better to update podfile in a separate PR to master, so it could get merged asap?

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/p0uj24qun0pexa6f8zc94k6wmw

[download apk](http://filestorage.bluewallet.io:1488/1583721361.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/adgbq5xkn1qmk7z8h9479xbkeg

[download apk](http://filestorage.bluewallet.io:1488/1583721861.apk)

**Comment by Overtorment** [comment]
@marcosrdz after your commit it is impossible to choose side. when you tap dropdown screen grays out.

image

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n2c6zpjedewpmf0djk45ep8x6c

[download apk](http://filestorage.bluewallet.io:1488/1583937340.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8t2mmvn8pued52n99dcwb869gc

[download apk](http://filestorage.bluewallet.io:1488/1584989833.apk)

**Comment by Overtorment** [comment]
@ncoelho @marcosrdz I intend to merge, need your blessing. we can brush up later

**Comment by ncoelho** [comment]
Give me a day to check this properly please :)

**Comment by Overtorment** [comment]
@ncoelho verdict?

**Pull request merged**
