### PR TITLE
FIX: Verify object type for watch connectivity

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/zzd0a4pcufmuuw5y2fr30kth7r

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/35wkv3rmxvzd44jxp00r1f85j8

**Comment by Overtorment** [comment]
needs conflict fix and probably rebasing. I think i see things in diff im not supposed to see

**Comment by marcosrdz** [comment]
CLosing. outdated.

**Pull request closed without merging**
