### PR TITLE
FIX: Modal wouldnt cover status bar on android

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jwf4t63mc99darm14jrxzmr6yw?device=pixel4

[download apk](http://206.189.62.190:1488/statusbar-1624988540.apk)

**Review by Overtorment — CHANGES_REQUESTED** [review]
e2e failed, otherwise lgtm

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/93vnkd2yu0qeh1c4ubth3j9kb4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7156)

**Comment by marcosrdz** [comment]
Package contains Android bug when using that prop. Closing until fixed.

**Pull request closed without merging**
