### PR TITLE
FIX: Address layout on multisig #2193

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/027z7vw8rpeq448nb571gtcdvr

[download apk](http://filestorage.bluewallet.io:1488/1606702984.apk)

**Comment by ncoelho** [comment]
@marcosrdz I believe we should do 2 things:|
- Just break the text and let it grow
- Center it

Screenshot 2020-11-30 at 11 27 21

**Comment by marcosrdz** [comment]
> @marcosrdz I believe we should do 2 things:|
> 
> - Just break the text and let it grow
> 
> - Center it
> 
> 
> 
> Screenshot 2020-11-30 at 11 27 21
> 
> 
> 
> 

What device is this?

**Comment by ncoelho** [comment]
> > @marcosrdz I believe we should do 2 things:|
> > 
> > * Just break the text and let it grow
> > * Center it
> > 
> > Screenshot 2020-11-30 at 11 27 21
> 
> What device is this?

11 pro

**Review by Overtorment — APPROVED** [review]

**Review by ncoelho — APPROVED** [review]

**Pull request merged**
