### PR TITLE
Scanbtn

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/r41wy86hh6jda2g9jgcdcechzr

[download apk](http://filestorage.bluewallet.io:1488/1589998835.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hyy8hu0kwpr00ab5c8dfn7b01g

[download apk](http://filestorage.bluewallet.io:1488/1590000898.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/49wp2y5nebjm79q4chrt2f8zv4

[download apk](http://filestorage.bluewallet.io:1488/1590061305.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5bhv3499re7uk8wcpne1z6hyqr

[download apk](http://filestorage.bluewallet.io:1488/1590063626.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/juem22f2rj2xb63ke9px1ttmzc

[download apk](http://filestorage.bluewallet.io:1488/1590064345.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/d72kwrpfgb1bpc8b8pxeur5ha8

[download apk](http://filestorage.bluewallet.io:1488/1590067920.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qjc7h4wf5xq1rxhuc96t6jp8z8

[download apk](http://filestorage.bluewallet.io:1488/1590069807.apk)

**Comment by Overtorment** [comment]
on android scan screen throws warning 
image

**Comment by marcosrdz** [comment]
> on android scan screen throws warning 
> 
> image
> 
> 

Removed those params since we no longer send props that way

**Comment by marcosrdz** [comment]
> youve lost ` testID="WalletsList"` thats why all travis tests failed.
> 
> and the warning.
> 
> otherwise lgtm

Placed it back into the carousel

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fvneu8qy6pdyzrwuduutdznz1w

[download apk](http://filestorage.bluewallet.io:1488/1590076710.apk)

**Pull request merged**
