### PR TITLE
REF: Refactor Batch UI to use FlatList

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f84fhkkev6hw20d9rpe46prdpw

[download apk](http://filestorage.bluewallet.io:1488/1600582555.apk)

**Comment by Overtorment** [comment]
first, write an e2e test for batch send, then refactor

**Comment by ncoelho** [comment]
conflits

**Comment by marcosrdz** [comment]
> conflits

Resolved

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1aun1b7p4cjnv79xwjfk4jq9ng

[download apk](http://filestorage.bluewallet.io:1488/1604972166.apk)

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8b1095gxfnbdk8h37xt1xxquac

[download apk](http://filestorage.bluewallet.io:1488/1605012484.apk)

**Comment by Overtorment** [comment]
merged, but @marcosrdz you still owe me some e2e tests

**Pull request merged**
