### PR TITLE
fix: eslint simple-import-sort plugin 💅💅💅  v2

### PR DESCRIPTION
**Pull request by limpbrains**
Same as #6321 but without adding new pluging to package.json

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bwdxmwtb744yylkp3kuqrzytou?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1676)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mt2cmarea6ifhcwdi6urlqflxy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1677)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j3hfkfvhwct3b6whxfx3p5eo3y?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1679)

**Comment by Overtorment** [comment]
kek

**Comment by limpbrains** [comment]
giphy2

**Review by Overtorment — APPROVED** [review]
lgtm. lets fix the conflict and merge

ps. maybe create npm script that installs the formatting dep, runs the formatter & uninstalls it? so we could run it from time to time

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
