### PR TITLE
manual rebase of changes from PR #772

### PR DESCRIPTION
**Pull request by fiatjaf**
I took the changes from https://github.com/BlueWallet/BlueWallet/pull/772 and applied them to current `master`.

### CODE REVIEW

**Comment by Overtorment** [comment]
strike! all tests are red

**Comment by Overtorment** [comment]
well, almost strike

**Comment by fiatjaf** [comment]
how can I fix this?

```
Execution failed for task ':app:bundleReleaseJsAndAssets'.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
```

**Comment by Overtorment** [comment]
you should not worry about build since you're working only in javascript space.
I haven't looked into diff yet, but if you're changing something in java/ios or build - dont.

**Comment by fiatjaf** [comment]
I am not changing something in java/ios or build, that's why I'm very puzzled.

**Comment by Overtorment** [comment]
build failed because of syntax errors:

image

**Comment by fiatjaf** [comment]
How can update `package-lock.json`? CircleCI is failing because it is using the cached `node_modules/` from days ago. I tried `npm shrinkwrap` but it produces a file with tons of differences. Apparently npm has installed slightly different versions of all dependencies on my computer, which shouldn't happen, right? What is wrong?

Also, "LGTM analysis" is failing for reasons I can't understand.

**Comment by limpbrains** [comment]
> How can update `package-lock.json`? 

When you add new dependencies using `npm install` package-lock.json will be changed. You need add to commit it to PR. This will trigger circleci to recreate cache. I don't see package-lock.json in your PR.

**Comment by limpbrains** [comment]
Please run `npm run lint:fix` locally, this will format sources add fix some lint issues, like missed semicolons

**Comment by fiatjaf** [comment]
Oh, the automatic generation of `package-lock.json` was disabled locally.

eslint is complaining here (and in Travis CI too, see logs) of added semicolons instead of semicolons missing. It also complains of a ton of things that were in the codebase already.

When I ran `npm run lint:fix` it changed every single file and made thousands of modifications.

**Comment by fiatjaf** [comment]
2020-07-07-091627_612x751_scrot

Maybe you have global eslint rules being mixed with the repo rules that yield the correct result -- and since I don't have these global rules results are different here?

**Comment by limpbrains** [comment]
> Maybe you have global eslint rules being mixed with the repo rules that yield the correct result -- and since I don't have these global rules results are different here?

This is strange, I don't have any. Are you on Windows ? I'm on mac 

If you add package-lock.json to PR, it will force circleci to rebuild the cache, I hope this will help.

**Comment by fiatjaf** [comment]
I'm on Linux and I have global eslint rules -- but that doesn't seem to be the problem since I removed them and the issue remained.

**Comment by fiatjaf** [comment]
Look, it's not a problem of my computer: https://github.com/BlueWallet/BlueWallet/pull/1329/checks?check_run_id=847564499#step:7:21

**Comment by limpbrains** [comment]
I've created local PR #1338 this will build apk and run more test

**Comment by limpbrains** [comment]
@fiatjaf I'm trying to test it.
After successful payment, I've got error `props.navigation.dismiss is not a function` on `lnurlPaySuccess.js:150` 
navigation.dissmiss() deprecated in ReactNavigation5 https://reactnavigation.org/docs/upgrading-from-4.x/#dismiss

**Comment by limpbrains** [comment]
I'm also have error when press "Repeat payment"

**Comment by fiatjaf** [comment]
Oops, I forgot to test that "repeat payment" funcionality.

**Comment by fiatjaf** [comment]
Ok, it should be fixed now.

**Comment by limpbrains** [comment]
lnulr-pay, Repeat payment works fine, but regular lightning invoice payment is broken. When I'm clicking on invoice link BW opens send form, but value is 0 and invoice field empty. Scan qr doesn't work and I can't paste invoice value.

It works fine on master

**Comment by limpbrains** [comment]
lnurl-withdraw worked on https://lightning.gifts/ but not on https://lnurl.bigsun.xyz , I don't know if it is their fault or not.

**Comment by fiatjaf** [comment]
I think it's fine. lnurl.bigsun.xyz is fake. It doesn't pay you anything.

Of course I broke something again. Sorry about that.

**Comment by fiatjaf** [comment]
Ok. Again I will say this is good. This time I tested all Lightning functions multiple times.

**Comment by ncoelho** [comment]
Re-running builds, android was failing.

**Comment by fiatjaf** [comment]
@Overtorment please!

**Comment by fiatjaf** [comment]
lnurl-pay support merged in #1374

**Pull request closed without merging**
