### PR TITLE
Add Payjoin support

### PR DESCRIPTION
**Pull request by Kukks**
Payjoin specification: https://github.com/btcpayserver/btcpayserver-doc/pull/469
Payjoin c# client reference: https://github.com/btcpayserver/btcpayserver/blob/03458efea4846e458c73041110ae96a94fd8bc15/BTCPayServer/Services/PayjoinClient.cs#L65

High-level explanation:
* Decode a BIP21
* Check if `pj` option is provided ( it should be a url)
* Create and finalize PSBT that pays BIP21
* Clean PSBT of any confidential data, like xpub information
* Send to url and receive a success status response with a psbt in the body
* validate psbt 
* sign psbt
* broadcast

This is my first time dealing with React and BitcoinJS, so please bear with me :)

### CODE REVIEW

**Comment by Kukks** [comment]
I'm getting a bit stuck with the differences between the PSBT libs we use (NBitcoin C# vs Bitcoinjs) :) 
Maybe someone can do the dirty work of porting over the psbt validation we do

**Comment by Kukks** [comment]
cc @lukechilds taking up your offer for BitcoinJS assistance :) 

also cc @junderw

**Comment by junderw** [comment]
Some quick fixes.

https://github.com/Kukks/BlueWallet/pull/1

Is it safe to assume all outputs will include bip32Derivation, redeemScript (if P2SH), and witnessScript (if P2WSH)???

I also used prettier to format it better. (Not sure if it matches the style of the rest of the repo though.)

**Comment by Kukks** [comment]
> 
> 
> Some quick fixes.
> 
> [Kukks#1](https://github.com/Kukks/BlueWallet/pull/1)
> 
> Is it safe to assume all outputs will include bip32Derivation, redeemScript (if P2SH), and witnessScript (if P2WSH)???
> 
> I also used prettier to format it better. (Not sure if it matches the style of the rest of the repo though.)

merged

Both server and client will be cleaning out any potentially privacy crushing data in the PSBT, so the `bip32Derivation` would be removed.

**Comment by Overtorment** [comment]
both travis and circleci builds failed. needs some love

**Comment by junderw** [comment]
We're going to work on this as a library first and they work on this PR by adding the dependency.

So hold on a while.

**Comment by Kukks** [comment]
Superseded by #1085

**Pull request closed without merging**
