### PR TITLE
ADD: Privacy settings for iOS 14 widgets

### PR DESCRIPTION
**Pull request by marcosrdz**
Simulator Screen Shot - iPhone 11 Pro - 2020-12-18 at 17 01 44

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e9g0jyyk1y1gmquww66bt2duk4

[download apk](http://filestorage.bluewallet.io:1488/1608329712.apk)

**Review by ncoelho — APPROVED** [review]

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/g2dj5m4tckqj4bm0a7n0mpf5kw

[download apk](http://filestorage.bluewallet.io:1488/1608420523.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/78f530myekau1xwppry0v0xu5m

[download apk](http://filestorage.bluewallet.io:1488/1608658341.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nhhdmdrzuw03612jad9bte5gzc

[download apk](http://filestorage.bluewallet.io:1488/1608839716.apk)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
