### PR TITLE
REF: DrawerList to TSX

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/sxb5wsazysai7xmr7ujgfjpxza?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/811)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nzhjfq2cx4kubvyv2hi2u3tt4e?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/812)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/77k3d34g3u5m73i6kpa4o5oclu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/813)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n6ytd4mbayx3xjtbdeidw3jrg4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/814)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by limpbrains** [comment]
Not necessarily, but I suggest we name interfaces with an `I` prefix and types with a `T`.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/33clwpxm7rvamjzrlcww6pksbe?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/822)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
