### PR TITLE
DEL: removed sentry crash analytics

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Review by marcosrdz — APPROVED** [review]

**Comment by limpbrains** [comment]
Why remove it? I thought it is useful for debugging.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vpvn87pj8409f8rewbp9r7qbfr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7845)

**Comment by Overtorment** [comment]
@marcosrdz you might need to do your pod magic here

**Comment by marcosrdz** [comment]
> @marcosrdz you might need to do your pod magic here

Already did

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/24we2b27uctzw3u1v9vj38q73g?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7849)

**Comment by Overtorment** [comment]
Gona replace with bugsnag. Tired of sentry, it’s weird

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
