### PR TITLE
ADD: Detox UI Test

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by Overtorment** [comment]
Test this build in browser:

(ﾉ◕ヮ◕)ﾉ*:・ﾟ✧ https://appetize.io/app/57urn7ne90w5qmdxu4vydqnq7w

(posted automatically)

**Comment by Overtorment** [comment]
Test this build in browser:

(ﾉ◕ヮ◕)ﾉ*:・ﾟ✧ https://appetize.io/app/k093negauzj3z46qgzwu4z64pg

(posted automatically)

**Comment by Overtorment** [comment]
Test this build in browser:

(ﾉ◕ヮ◕)ﾉ*:・ﾟ✧ https://appetize.io/app/rwmp6fu2yvm7huetu24e2wgtzw

(posted automatically)

**Comment by Overtorment** [comment]
Test this build in browser:

(ﾉ◕ヮ◕)ﾉ*:・ﾟ✧ 

(posted automatically)

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/a40ypary1qpfxgrnh66d9atham

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/45pcfzpujbrv6vwwxbyy6rgqd0

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/auhj1th55ue4j5mdz2y14621g8

**Comment by Overtorment** [comment]
merged in another PR

**Pull request closed without merging**
