### PR TITLE
REF: Foundation for watchOS app

### PR DESCRIPTION
**Pull request by marcosrdz**
Smaller PR

## Release Notes

- **New Features**
	- Introduced a `KeychainHelper` class for secure data storage in the iOS Keychain.
	- Added new wallet and transaction type enumerations for improved type safety and clarity.
	- Enhanced error handling and logging for wallet data transmission to the Apple Watch.
	- Implemented a new `WalletGradient` struct to manage wallet color gradients more effectively.
	- Added support for watchOS functionality with updated Info.plist configurations.
	- Enhanced the `WatchDataSource` class for better data handling and session management.
	- Added a new method for formatting transaction amounts based on Bitcoin units.

- **Bug Fixes**
	- Resolved issues with wallet identifier handling, transitioning to UUID for better type safety.

- **Refactor**
	- Streamlined various classes and methods for improved readability and maintainability, including updates to wallet and transaction handling logic.
	- Refactored the `Transaction` and `Wallet` entities to use structs, enhancing functionality and type safety.
	- Simplified the `ReceiveInterfaceController` and `SpecifyInterfaceController` logic for wallet type checks.

- **Documentation**
	- Updated internal documentation to reflect changes in wallet and transaction types, as well as Keychain usage.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Comment by marcosrdz** [comment]
> lgtm, but i have a question: is it possible to cover at least some parts of swift code with unit tests and make them run on ci?

Yup. Ill be writing XCTest and XCUITesr

**Pull request merged**
