### PR TITLE
OPS: Upgrade RNE 

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ye7zuz0jv8cjjctybbt56h3k04

[download apk](http://filestorage.bluewallet.io:1488/1588435299.apk)

**Comment by ncoelho** [comment]
Mnemonic screen is broken

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9aff86vbqudeym0u8d0tedz50g

[download apk](http://filestorage.bluewallet.io:1488/1588467381.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ew3ujqmb36mh0ev042aw7cjx6m

[download apk](http://filestorage.bluewallet.io:1488/1588468901.apk)

**Comment by Overtorment** [comment]
image




wallet
s
😂

please have some compassion for poor android users

**Comment by marcosrdz** [comment]
> image
> 
> wallet
> s
> 😂
> 
> please have some compassion for poor android users

Fixed

**Comment by marcosrdz** [comment]
> Mnemonic screen is broken

Fixed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/puwe6nmv79ekyz3t9ht7fd4j24

[download apk](http://filestorage.bluewallet.io:1488/1588518596.apk)

**Pull request merged**
