### PR TITLE
OPS: Update package

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ypp6acm16hb9q94k0er6rfndam?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9579)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7cfew0x11n43gbqr9bez6r3q7w?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9582)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm.
restarted e2e

**Comment by Overtorment** [comment]
@marcosrdz i remind you that its your responsibility to keep an eye on your prs and make sure they get merged. 
i have just restarted e2e tests in hope it will pass this time and glados will merge it.

**Comment by marcosrdz** [comment]
Package broken based on recent github issues. Closing.

**Pull request closed without merging**
