### PR TITLE
FIX:  Wrong android effect transition #1914

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zkvukd68y330mtpbwcv9ftum68

[download apk](http://filestorage.bluewallet.io:1488/1600919260.apk)

**Comment by EhsanSarshar** [comment]
@marcosrdz would you mind to create a patch. for temporary work around, until this is merged

**Comment by EhsanSarshar** [comment]
The issue also exist for scaleFromCenter and fadeFromBottom

**Comment by marcosrdz** [comment]
> The issue also exist for scaleFromCenter and fadeFromBottom


Is it replicable with the APK in this PR? It shows the expected transition on my android emulator and on the appetize link

**Comment by marcosrdz** [comment]
> The issue also exist for scaleFromCenter and fadeFromBottom

Make sure you set the screen options on your root stack. You can see the passed screenOptions in this PR.

**Review by Overtorment — APPROVED** [review]
Lgtm. Waiting for @ncoelho or should we merge?

**Review by ncoelho — APPROVED** [review]

**Comment by ncoelho** [comment]
Looks good!

**Pull request merged**
