### PR TITLE
Capitalization – Part Two

### PR DESCRIPTION
**Pull request by mcsaeid**
For more information on capitalization, please refer to “Capitalization – Part One.”

### CODE REVIEW

**Review by marcosrdz — APPROVED** [review]

**Review by Overtorment — APPROVED** [review]

**Review by ncoelho — APPROVED** [review]

**Comment by Overtorment** [comment]
pls fix conflicts

**Comment by mcsaeid** [comment]
Will do.

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by Overtorment** [comment]
merged in https://github.com/BlueWallet/BlueWallet/pull/2318

**Pull request merged**
