### PR TITLE
ADD: languages sync CZ, FI, zh_CN, PL fastlane files

### PR DESCRIPTION
**Pull request by limpbrains**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xnxktbjgc0103jjmd51z0bqjfg

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-loc-sync13-1614259771.apk)

**Comment by Overtorment** [comment]
conflict. redo the pr..?

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zqw4xu7t7133vtx60bp4efr8bg

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-loc-sync13-1614330731.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
