### PR TITLE
OPS: Package update

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]
Tests failed

**Comment by marcosrdz** [comment]
> 

Server issues (electrum and gradle). Ill wait a bit and rerun the tests.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ndaq9mz8uk9dtbtv29jra39acw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9365)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
