### PR TITLE
FIX: for legacy-wallet.fetchTransactions() to not crash when vout for transaction is missing addresses.

### PR DESCRIPTION
**Pull request by mgurzenski**
Was unable to view transactions for the following bitcoin address without this fix - [1PVfrmbn1vSMoFZB2Ga7nDuXLFDyJZHrHK](https://www.blockchain.com/btc/address/1PVfrmbn1vSMoFZB2Ga7nDuXLFDyJZHrHK)

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z3u7x030xcwv7ju5f8q6b0d7wg

[download apk](http://filestorage.bluewallet.io:1488/1589884359.apk)

**Comment by Overtorment** [comment]
thanks!

**Comment by Overtorment** [comment]
I did code search and applied same fix for HD wallets. would be nice if you could take a look
https://github.com/BlueWallet/BlueWallet/pull/1099

**Comment by mgurzenski** [comment]
> I did code search and applied same fix for HD wallets. would be nice if you could take a look
> #1099

Looks Good!

**Pull request merged**
