### PR TITLE
REF: Use existing nav ref for scanQR helper #6601

### PR DESCRIPTION
**Pull request by marcosrdz**
Closed previous PR as changing the parameter lead to chaos.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pbwfan5m6otvfxo7wsznc6cc4i?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1752)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hdzi4c4gh276zftjz4wreanyum?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1753)

**Review by Overtorment — APPROVED** [review]
beautiful

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
