### PR TITLE
REF: attempt to cleanuop & speedup android native

### PR DESCRIPTION
**Pull request by Overtorment**
as per install docs, we dont need those lines..?

https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6jasq73khw5mycqvbiwte2nwi4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10784)

**Comment by marcosrdz** [comment]
I dont remember which packages require reanimated but I do remember the app crashing without it

**Comment by Overtorment** [comment]
@marcosrdz reanimated is still there, i just removed extra lines from `android/` because apparently they were needed for some old reanimated versions, but now integration guide doesnt mention them at all. everything seems to be working fine

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
