### PR TITLE
ADD: HodlHodl login & accept offer (you can buy only for now)

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] 

[download apk](http://filestorage.bluewallet.io:1488/1589556841.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zqbuw7y1v8qn87kjmme9xaweh8

[download apk](http://filestorage.bluewallet.io:1488/1589658848.apk)

**Comment by Overtorment** [comment]
@ncoelho  this needs your input.
screens to accept offer are done, but are not styled.

clicking offer:

image

image


image

after offer was accepted, a new contract is created and user can go to 'My contracts' screen:


image

and tap a specific contract in the list:


image

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5k69yhcmq1ar4avzpyz0ur29w0

[download apk](http://filestorage.bluewallet.io:1488/1589802630.apk)

**Comment by Overtorment** [comment]
forgot to mentiuon. this is data I get from API we can potentially render. 
offer (before you accept it), and contract (this is what is created once you accept offer)

```


OFFER
=================

    { id: 'qSPw0kUnRSbdMyX3',
      version: '210f6tjb',
      asset_code: 'BTC',
      searchable: false,
      country: 'United Kingdom',
      country_code: 'GB',
      working_now: true,
      side: 'sell',
      title: 'Selling coins for the glory os Satan',
      description: null,
      currency_code: 'USD',
      price: '14881.00',
      min_amount: '10.00',
      max_amount: '666.00',
      first_trade_limit: null,
      fee: { author_fee_rate: '0.00522500' },
      balance: null,
      payment_window_minutes: 900,
      confirmations: 1,
      payment_method_instructions:
       [ { id: '3877',
           version: '210f6tjb',
           payment_method_id: '337',
           payment_method_type: 'Bank wire',
           payment_method_name: 'Any national bank' } ],
      trader:
       { login: 'Overtorment',
         avatar_url:
          'https://hodlhodl.com/assets/default_avatar-f5b0258802df64cd87d94b95a1faed32b1b464bfb9b1cef2a10f6c30ddc91158.svg',
         online_status: 'online',
         rating: '1.00',
         trades_count: 1,
         url: 'http://accounts.hodlhodl.com/accounts/Overtorment',
         verified: false,
         verified_by: null,
         strong_hodler: false,
         country: 'United Kingdom',
         country_code: 'GB',
         average_payment_time_minutes: null,
         average_release_time_minutes: 0,
         days_since_last_trade: 160 } }











contract
===========


    { contract:
       { id: 'hhWRIz1UZFdDRurr',
         your_role: 'buyer',
         can_be_canceled: true,
         offer_id: 'qSPw0kUnRSbdMyX3',
         price: '14881.00',
         value: '74.60',
         currency_code: 'USD',
         volume: '0.00502619',
         asset_code: 'BTC',
         comment: 'I accept your offer',
         release_address: 'bc1q4gk98vhqzpf2lmw8hfsktljzhxm47fwswegmwz',
         confirmations: 1,
         payment_window_seconds_left: 900,
         status: 'pending',
         dispute_status: null,
         payment_method_instruction: { payment_method_id: '337', details: 'any bank' },
         volume_breakdown:
          { goes_to_buyer: '0.00499993',
            exchange_fee: '0.00002626',
            exchange_fee_in_fiat: '0.20',
            transaction_fee: '0.00033232' },
         country: 'United Kingdom',
         country_code: 'GB',
         created_at: '2020-05-12T19:10:27Z',
         counterparty:
          { login: 'Overtorment',
            avatar_url:
             'https://hodlhodl.com/assets/default_avatar-f5b0258802df64cd87d94b95a1faed32b1b464bfb9b1cef2a10f6c30ddc91158.svg',
            online_status: 'online',
            rating: '1.00',
            trades_count: 1,
            url: 'http://accounts.hodlhodl.com/accounts/Overtorment',
            verified: false,
            verified_by: null,
            strong_hodler: false,
            country: 'United Kingdom',
            country_code: 'GB',
            average_payment_time_minutes: null,
            average_release_time_minutes: 0,
            days_since_last_trade: 160 },
         escrow:
          { address: '34n3rBtPA16BQYWycphnhK7C9DoucWb527',
            witness_script:
             '522103dc0edfea797214be15a69148bfb1dffa1c8295c05300b7632143a77d918b4a0821031fec42b60942633616aff7e245796b5caae6bf59ef5ba688b0a59f33f08b2896210351fd6e52d38a37b9834909e3f8345c471346e1f5990ec00dafcc53e238d3c7c553ae',
            index: 10298,
            you_confirmed: false,
            counterparty_confirmed: false,
            confirmations: 0,
            amount_deposited: '0.00000000',
            amount_released: null,
            deposit_transaction_id: null,
            release_transaction_id: null } } }

```

**Comment by ncoelho** [comment]
Current proposal, seems solid to start with.

Screenshot 2020-05-20 at 15 15 55

**Comment by Overtorment** [comment]
image

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kfb143kgm3p8c31hw7twg6cttw

[download apk](http://filestorage.bluewallet.io:1488/1590592279.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/19nf22fg0qmvm4xnncgvvp9174

[download apk](http://filestorage.bluewallet.io:1488/1590593253.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2btcke9b0uka4eu2y6633wm7b4

[download apk](http://filestorage.bluewallet.io:1488/1590680251.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nf2rzu788b9w9ck8j9vhunr5u0

[download apk](http://filestorage.bluewallet.io:1488/1590682019.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mtkbuzacbtemrv2qyapbqhe5rm

[download apk](http://filestorage.bluewallet.io:1488/1590689089.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3e0vqjyga1yhwx57cd7ecuhkrc

[download apk](http://filestorage.bluewallet.io:1488/1590690681.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zauv442wu0r47n8f380fbnecd4

[download apk](http://filestorage.bluewallet.io:1488/1590719639.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/azugd630pceavyqbnhb8dfg4cw

[download apk](http://filestorage.bluewallet.io:1488/1590742827.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7uhkxyvh5khec5k3d0k603409c

[download apk](http://filestorage.bluewallet.io:1488/1590744100.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ngehbz3adkpc11yhvk2p5pqbrm

[download apk](http://filestorage.bluewallet.io:1488/1590750368.apk)

**Comment by Overtorment** [comment]
closing in favor of https://github.com/BlueWallet/BlueWallet/pull/1162

**Pull request closed without merging**
