### PR TITLE
ADD: when creating multisig, input cosigner as xpub

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/evgv5dzm7m39qckz62zxr176j4

[download apk](http://filestorage.bluewallet.io:1488/1606322711.apk)

**Review by marcosrdz — APPROVED** [review]

**Comment by ncoelho** [comment]
Input not appearing on iOS

Screenshot 2020-11-25 at 18 02 25

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3hea1ptea8drdxd7nnu0mw7tm4

[download apk](http://filestorage.bluewallet.io:1488/1606325481.apk)

**Comment by Overtorment** [comment]
should be fixed now

**Comment by ncoelho** [comment]
tACK

worked beautiful from a MS created on electrum :))

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
