### PR TITLE
DEL: Remove contextMenuHidden

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3pgyu73vm1uqb3kz4vjpzhm6kg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9064)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Comment by limpbrains** [comment]
@marcosrdz This PR breaks Import screen. I can't enter space import input.
What is this filter for? Also it doesn't apply for paste from clipboard.

https://user-images.githubusercontent.com/155891/141670700-fd6a60a5-7c84-4be9-b38d-a9bb880e8c90.mp4

**Comment by marcosrdz** [comment]
> @marcosrdz This PR breaks Import screen. I can't enter Space in seed input. What is this filter for? Also it doesn't apply for paste from clipboard.
> 
>  Simulator.Screen.Recording.-.iPhone.12.-.2021-11-14.at.09.48.02.mp4

#4211

**Pull request merged**
