### PR TITLE
Update and rename en.js to vn.js

### PR DESCRIPTION
**Pull request by vuongvoviet**
Thêm tiếng Việt

Add Vietnamese

### CODE REVIEW

**Comment by ncoelho** [comment]
Hi @vuongvoviet do you plan to finish this PR or can I close it? Let me know if you need help.

**Comment by vuongvoviet** [comment]
I want to add Vietnamese but i can not edit the vn.js.

Pls help me on this case



Vào Thứ Sáu, 20 tháng 9, 2019, Nuno Coelho <notifications@github.com> đã
viết:

**Comment by ncoelho** [comment]
Ok, then let's go by parts.

1- Download Github Desktop, it is easier to manage things from there
2- Clone bluewallet repo, File > clone repository
3- Choose the branch, goto Current Branch menu > Pull requests > your pull request
4- Go to the files on your local copy and edit the file loc/vi_VN.js
5- after done, on github desktop on bottom left, write a commit message and click commit
6- Top menu push to origin/branch

**Comment by vuongvoviet** [comment]
tks for your supports

I have just pushed the commit on GitHub
repos 25c195c926706283acfd410093bedd79f1bd1cb6

Hope Bluewallet have Vietnamese soon

Best regards;

Vuong

Vào Th 6, 20 thg 9, 2019 vào lúc 22:15 Nuno Coelho <
notifications@github.com> đã viết:

**Pull request merged**
