### PR TITLE
ADD: Update Outdated Rate

### PR DESCRIPTION
**Pull request by marcosrdz**
In case the rate API is down or last update was long ago. 

Simulator Screen Shot - iPhone 13 - 2021-10-27 at 00 12 24

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hwhfb3u0tujhw347d7b3ac6nr8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8971)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/b16uqw5hz0dvhjeqw7w2g8m30r?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8981)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
