### PR TITLE
Feature: Ability to show wallet XPUB in options

### LINKED ISSUE #135: Export xpub
Ability to export on xpub format

2290a75b-87d8-4f56-b3d0-9304600aa292

### PR DESCRIPTION
**Pull request by pajasevi**
Added option to show wallet XPUB (YPUB) for HD wallets. Nothing fancy.

Closes #135 

simulator screen shot - iphone x - 2018-12-27 at 16 37 58
simulator screen shot - iphone x - 2018-12-27 at 16 38 08

### CODE REVIEW

**Comment by pajasevi** [comment]
DIscussion: Should user be able to copy the XPUB by tapping on it?

**Comment by ncoelho** [comment]
I would say it should... 👍

**Comment by pajasevi** [comment]
@ncoelho Done! :)

**Comment by Overtorment** [comment]
Well done!

**Pull request merged**
