### PR TITLE
REF: Search moved to Reorder screen

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nwxed66kolpondzytfdsh3slxy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/240)

**Review by Overtorment — APPROVED** [review]
Lgtm

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3vekzom5a2c7thxygxvej7k36m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/247)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kyw75hh4lp7hit4wovsn76ocim?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/248)

**Pull request merged**
