### PR TITLE
FIX:  bolt11 links are opening the app but not the invoice itself #1352

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/c7yw2n9b5bnmmatnnm2h135d5g

[download apk](http://filestorage.bluewallet.io:1488/1595119807.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x0hg2v6ypqhuwtz3ywqbbtg10c

[download apk](http://filestorage.bluewallet.io:1488/1595286170.apk)

**Comment by Overtorment** [comment]
still fail

**Comment by marcosrdz** [comment]
Found a much adequate way to handle this in React Nav's built in linking mechanism. Closing this PR to go with said route.

**Pull request closed without merging**
