### PR TITLE
fix 947 KeyboardAvoiding for android

### PR DESCRIPTION
**Pull request by ncoelho**
waiting for an android build to proper test on android...

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vqxrc9bgrwazmnpfj72un15h9g

[download apk](http://filestorage.bluewallet.io:1488/1586022592.apk)

**Comment by ncoelho** [comment]
No good... needs a scrollview

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bexjvfnzbka3ge46jpb24a15f4

[download apk](http://filestorage.bluewallet.io:1488/1586025480.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hk3335v95ey9zak97bxzqz1ddg

[download apk](http://filestorage.bluewallet.io:1488/1586033118.apk)

**Comment by ncoelho** [comment]
tested on android, seems to work

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8zdmc7rzv73y4x983zqw7kpf90

[download apk](http://filestorage.bluewallet.io:1488/1586033996.apk)

**Comment by Overtorment** [comment]
stupid deepscan barks at the file that wasn't changed

**Comment by ncoelho** [comment]
@Overtorment is there anything I can do on this one?

**Comment by ncoelho** [comment]
Opening a new one https://github.com/BlueWallet/BlueWallet/pull/960

**Pull request closed without merging**
