### PR TITLE
FIX: lndhub backup QR doesnt have a "@%server%" suffix #3379

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/quz5qd6x0d1euzwvvqgbm73104?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7283)

**Review by Overtorment — CHANGES_REQUESTED** [review]
thats not it. 
the string with backup is displayed correctly.
besides, this fix would always put in backup string server, even the default one? (`lndhub.io`)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/968b1rv6dvxqk7znnyz76zj6gg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7288)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
