### PR TITLE
FIX: secure keystore keys should not leave device

### LINKED ISSUE #5259: Secret keystore should not be synced to iCloud
Secure items stored in keychain should not be synced to iCloud nor migrated to new devices, as most security-concerned users would be concerned about their keys leaving their devices, even if encrypted.

As this is fundamental to Bluewallet's cores, as shown in the readme:
image

From `react-native-secure-key-store` docs:
image

### PR DESCRIPTION
**Pull request by AbdelrahmanManz**
closes #5259

### CODE REVIEW

**Comment by Overtorment** [comment]
good catch! 
@marcosrdz @limpbrains thoughts..?

**Review by marcosrdz — APPROVED** [review]

**Comment by limpbrains** [comment]
@AbdelrahmanManz Awesome job!

**Review by limpbrains — APPROVED** [review]

**Comment by marcosrdz** [comment]
> I hope it wont break someone's usecase

Perhaps those upgrading their device and using a backup to restore on a new device

**Comment by Overtorment** [comment]
> > I hope it wont break someone's usecase
> 
> Perhaps those upgrading their device and using a backup to restore on a new device

@ncoelho would need some market research on this, what is best

**Pull request merged**
