### PR TITLE
REF: bump bitcoinjs to v6.0.0

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by Overtorment** [comment]
theoretically this should bring us p2tr send support

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ddunvb7pqcebg8vb405cp4ncbc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9142)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/16bqabh3ex7jwu3m40q92zkbp8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9145)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
