### PR TITLE
REF: Reuse Success screen

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/raev652g6arjfc5nm068qvq6aw

[download apk](http://filestorage.bluewallet.io:1488/1606031662.apk)

**Comment by ncoelho** [comment]
Is it still missing somewhere, like PSBT...?

**Comment by marcosrdz** [comment]
> Is it still missing somewhere, like PSBT...?

I think its missing on psbt multisig. Normal psbt has it after it got refactored to hook

**Comment by marcosrdz** [comment]
> Is it still missing somewhere, like PSBT...?

lndViewInvoice and broadcast.js

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/auhjqmc7eumg46ruyapww7v0h8

[download apk](http://filestorage.bluewallet.io:1488/1606103071.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by ncoelho** [comment]
I tap "done" on the paid invoice confirmation screen, and nothing happens

**Comment by ncoelho** [comment]
Transactions.js did not automatically update after sending a transaction

**Comment by ncoelho** [comment]
Did a RBF and can't see the transaction on the wallet

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
