### PR TITLE
OPS: Lower mindsdk

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2727ejqd8tjkke281yh3uhcxem?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7294)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/red5x9xqkwy888n0zm5jb25t0g?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7305)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7e3nw0rm0afhjcqqjfy3w0rrq8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7307)

**Comment by Overtorment** [comment]
All alright, what's all this then?

**Comment by marcosrdz** [comment]
This is a separate branch to offer a build without Tor for older devices.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7wtjvth5znbjbubfzepz9hqzzc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7326)

**Pull request closed without merging**
