### PR TITLE
OPS: Update packages

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by marcosrdz** [comment]
async storage change package name. 
amplitudejs updated to reflect the new package name
image picker updated with catalyst support.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cwk21k5u4euyubp71yar10fk1m

[download apk](http://filestorage.bluewallet.io:1488/1608090321.apk)

**Review by Overtorment — CHANGES_REQUESTED** [review]
tests failed. probably asyncstorage needs mock to be fixed

**Comment by marcosrdz** [comment]
> tests failed. probably asyncstorage needs mock to be fixed

done

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/83efevg2bc7vag2uqn6d5ug8jg

[download apk](http://filestorage.bluewallet.io:1488/1608146395.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hrztq40gv952daq41mfqw4b6gr

[download apk](http://filestorage.bluewallet.io:1488/1608253438.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ke1d37zu44pry3rcnpptf2vf58

[download apk](http://filestorage.bluewallet.io:1488/1608311328.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
