### PR TITLE
TST: batch send test

### LINKED ISSUE #1904: e2e: test bip84 batch send
can be part of `can import BIP84 mnemonic, fetch balance & transactions, then create a transaction` test as it already tests sendMax

### PR DESCRIPTION
**Pull request by limpbrains**
closes #1904

https://user-images.githubusercontent.com/155891/109118198-12205880-7754-11eb-8a80-5e7a3c337fca.mov

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9ver9dpy7jtgazxygjee7rrb64

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sendmany-test-1614239951.apk)

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f41fau0vd2gqzujzayrfw6zcv4

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-sendmany-test-1614264526.apk)

**Review by Overtorment — APPROVED** [review]
noice

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
