### PR TITLE
DEL: Remove outdated code for unsupported macOS

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hjf2nnb2rgwlawkjo4j3erl3c4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10889)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bjlsorlwc76cvweg3jioistb7a?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10890)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dpkirnhkzqnihm7spsh6xehhsy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10891)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
