### PR TITLE
FIX: Security screen froze on load

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]

**Comment by Overtorment** [comment]
do you want it merged? 
I added WIP label just for any case

**Comment by marcosrdz** [comment]
Fuck it. Yeah. Lets go

**Comment by Overtorment** [comment]
did e2e pass at least.?

**Comment by marcosrdz** [comment]
> did e2e pass at least.?

didn't get enough time for it to even start. however, this change is not going to have any difference for Android as its simply a removal of useCallback

**Pull request merged**
