### PR TITLE
OPS: Update Package

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by limpbrains** [comment]
I've tried to upgrade it a few months back. We should not just replace a package but also try to remove hacks from blue_modules/net.js because react-native-tcp-socket v6 now supports almost everything

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4bb73gs2phbx3uyymtyfh5s2aa?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/305)

**Comment by Overtorment** [comment]
I'll fix it if e2e fails

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by marcosrdz** [comment]
@Overtorment e2e

**Comment by Overtorment** [comment]
I'll work on it

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by marcosrdz** [comment]
@Overtorment    Conflicts

**Comment by Overtorment** [comment]
made all the changes to support latest  `react-native-tcp-socket`
had to update our own dep https://github.com/BlueWallet/rn-electrum-client

**Comment by Overtorment** [comment]
@marcosrdz can you pls resolve conflict? its not obvious which hashes should be used in podfile lock

**Comment by marcosrdz** [comment]
> @marcosrdz can you pls resolve conflict? its not obvious which hashes should be used in podfile lock

Done

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u7nmauosf6umzsy5kytdjvuyzi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/362)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e535vbymos3biswttjdb2xseeq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/363)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7fvcfr2twqa67jclgyesrrsj7y?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/373)

**Pull request merged**
