### PR TITLE
FIX: Notes were not persistent

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mudar23k4ssa272rlea5zxtqgy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1761)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nfi5wprzmnlc2mh3reqqfkh4km?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1767)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cgmih5zrxw2bjdtwvd3hd5fwai?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1772)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yexuuvtwe2i6bmlwksi2hxicom?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1774)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/eoa6o23pnvlxi5rzag2a2ksnry?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1775)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
