### PR TITLE
ADD: Shortcuts on Scan button long press

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/b34mz8c6dnpk2eefcd0bec24vw

[download apk](http://filestorage.bluewallet.io:1488/1590263327.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uw8cathzrbyq2eq8ff0na5heg0

[download apk](http://filestorage.bluewallet.io:1488/1590338945.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5eqbdc5z7wu1v51teuxf5ddknw

[download apk](http://filestorage.bluewallet.io:1488/1590367453.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/afq398ad8ebfqbay91mf8j1k48

[download apk](http://filestorage.bluewallet.io:1488/1590369145.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/q45vpvpxhza6cd1dax18dgp688

[download apk](http://filestorage.bluewallet.io:1488/1590411550.apk)

**Comment by Overtorment** [comment]
longpress scan qr fail Peek 2020-05-25 14-03

qr in saved photos didnt work for me

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f8rx7g3zve0nwycye97ra2n1e8

[download apk](http://filestorage.bluewallet.io:1488/1590427122.apk)

**Pull request merged**
