### PR TITLE
FIX: buggy BIP47 add to contacts

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Review by marcosrdz — CHANGES_REQUESTED** [review]
Test failed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pkozwoepwsky5vozz4jrvfcnau?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1851)

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wy325dammp6l2ulz3eq2mqv5ce?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1853)

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
