### PR TITLE
REF: Alert to TS

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uiuq4vfs7xmrmnbdz7u2nmhdaa?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/99)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qdgwyawbekbgda7jeblhb56tjm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/106)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/reimi7kjquqp3cxzg5gcarvdoy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/107)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
