### PR TITLE
REF: Fix header on MultiSig setup2

### PR DESCRIPTION
**Pull request by ncoelho**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7ec4w6zx2310mey6znxz1yku7w

[download apk](http://filestorage.bluewallet.io:1488/1604588240.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rar3c1jh9wdn7f0kjczqpurcm0

[download apk](http://filestorage.bluewallet.io:1488/1604593855.apk)

**Review by Overtorment — APPROVED** [review]

**Review by Overtorment — CHANGES_REQUESTED** [review]
linting required.
also, what header are we talking about? i dont see any

image

**Comment by ncoelho** [comment]
It was the safearea, not the header. Closes https://github.com/BlueWallet/BlueWallet/issues/2060

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j89a2hg0m5wj3pt3ktp51daqz0

[download apk](http://filestorage.bluewallet.io:1488/1604599577.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/32j139dkfrn7qcm5hnwce84nd8

[download apk](http://filestorage.bluewallet.io:1488/1604603816.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/q3krv260aveq3dkpfdkuhkhda4

[download apk](http://filestorage.bluewallet.io:1488/1604604617.apk)

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/m3k2b6w64fmuztxmrh3fx85v20

[download apk](http://filestorage.bluewallet.io:1488/1604633134.apk)

**Comment by marcosrdz** [comment]
@ncoelho  conflict.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ce3th0d6ap1942r4jrj6uxcuac

[download apk](http://filestorage.bluewallet.io:1488/1604654835.apk)

**Pull request merged**
