### PR TITLE
REF: silent-payments minor refactor

### PR DESCRIPTION
**Pull request by Overtorment**
* simplified code a bit
* locked SP dep

### CODE REVIEW

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/m5zsaj25iiu5ahcfpdkpmleo4u?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1810)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/lbzmpx6yikvwng7yacwlskofsu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1815)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
