### PR TITLE
Ref lnurlpay to ts

### PR DESCRIPTION
**Pull request by Overtorment**
## Summary by CodeRabbit

- **New Features**
	- Enhanced type safety and clarity in the `Lnurl` class and `LnurlPay` component with new TypeScript type annotations and interfaces.
	- Introduced structured error handling and improved state management in the `LnurlPay` component.

- **Bug Fixes**
	- Refined logic for handling optional fields and payloads in both `Lnurl` and `LnurlPay`, ensuring more predictable behavior.

- **Style**
	- Simplified conditional rendering logic and improved code formatting in various components for better readability.

### CODE REVIEW

**Review by marcosrdz — CHANGES_REQUESTED** [review]
Lint

**Comment by marcosrdz** [comment]
@Overtorment  deepscan shows valid potential crash pointd

**Comment by Overtorment** [comment]
i fixed deepscan, new deepscan issues we can ignore

**Review by marcosrdz — APPROVED** [review]

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
