### PR TITLE
REF: Moved Wallet classes to subfolder and converted filenames to kabob case. Closes #972

### LINKED ISSUE #972: Refactor classes
Wallets go to a separate folder.
Camelcase filenames change to snake case

### PR DESCRIPTION
**Pull request by mgurzenski**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nfjgk406g9z693wbhzpb5a5q5w

[download apk](http://filestorage.bluewallet.io:1488/1590351197.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/19rv8mwvmkkbty0xtae4ba8xt4

[download apk](http://filestorage.bluewallet.io:1488/1590398956.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3cchzcf666dj6dc0ht5vrwbwqr

[download apk](http://filestorage.bluewallet.io:1488/1590401839.apk)

**Comment by Overtorment** [comment]
lets run all tests here https://github.com/BlueWallet/BlueWallet/pull/1132

ps. i need to teach glados to not build master

**Comment by mgurzenski** [comment]
Closing this PR. will open new PR that resolves linting issues.

**Pull request closed without merging**
