### PR TITLE
FIX: Electrum ports settings were missing keyboard type

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/055h4zfjk4pttf90gmvh1q4zx0

[download apk](http://filestorage.bluewallet.io:1488/kbtype-1619393388.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nyvz4c5pcjp8murtb2ztcbr5j4

[download apk](http://filestorage.bluewallet.io:1488/kbtype-1619488190.apk)

**Review by ncoelho — APPROVED** [review]

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ndkra8x3az16funtv2ykz348hc?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/kbtype-1619604690.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/0f6k3yzzm68y6yyj4je2deetrg?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/kbtype-1619620620.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k3hfpw8kpp1n44bt5uzxn6bram?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/kbtype-1619623262.apk)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
