### PR TITLE
FIX: incorrect fees occasionally (for some electrum servers); better …

### PR DESCRIPTION
**Pull request by Overtorment**
…fee estimation

### CODE REVIEW

**Review by marcosrdz — APPROVED** [review]

**Comment by Overtorment** [comment]
@ncoelho in this PR i add +5 sat/vb for fast estimate, and +2 for medium estimate.
that strategy worked well for my personal txs. wdyt ?

**Comment by marcosrdz** [comment]
DeepScan brought up valid points @Overtorment

**Comment by Overtorment** [comment]
deepscan is being useful once, for a change

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6rcpmm4eu7uj42aagurm5pqumy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11574)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/y5zpaqlicfptfmbgstrv26jhhi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11576)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
