### PR TITLE
Add Nobitex exchange for IRT currency

### PR DESCRIPTION
**Pull request by cybertech1981**
Please add Nobitex exchange, because many Iranians use this exchange and it is almost a price reference for digital currencies of this exchange in Iran and The volume of exchanges is more than Exir exchange.

### CODE REVIEW

**Comment by limpbrains** [comment]
cc @mcsaeid

**Review by limpbrains — CHANGES_REQUESTED** [review]
If you want to replace Exir with Nobitex, that Exir should be removed completely

**Comment by mcsaeid** [comment]
> cc @mcsaeid

I am okay with the change. The aforementioned exchange is bigger, I believe.

**Comment by cybertech1981** [comment]
> If you want to replace Exir with Nobitex, that Exir should be removed completely

**Comment by cybertech1981** [comment]
> > cc @mcsaeid
> 
> I am okay with the change. The aforementioned exchange is bigger, I believe.

Thank You 🙏🙏

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Pull request closed without merging**
