### PR TITLE
Limpbrains migrate to react navigation5

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by limpbrains** [comment]
Curious, why are you creating another PR ? Do you have another set of tests for local branch PR ?

**Comment by Overtorment** [comment]
@limpbrains yeah, more tests run this way, since I'm a member of this repo, environment secrets are passed in my PRs

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/h2m171hgwq48rmrk081x7qzy48

[download apk](http://filestorage.bluewallet.io:1488/1590777013.apk)

**Comment by Overtorment** [comment]
success.  @marcosrdz can you glance at diff and give your blessing? @ncoelho can you run through appetizer one last time to make sure there are no major issues? we can fix minor issues later in master

**Comment by Overtorment** [comment]
I intend to merge this PR

**Comment by ncoelho** [comment]
Gonna report as I keep testing:

1- there’s a wrong behavior on lightning wallet creation. Should not have
the title and should not allow to go back.

**Comment by Overtorment** [comment]
another bug caught thanks to e2e tests:

image

**Comment by limpbrains** [comment]
> there’s a wrong behavior on lightning wallet creation

I've fixed it in my PR
https://github.com/BlueWallet/BlueWallet/pull/1145/commits/2b4e5ab260b024ab29c5e9e8b214cf8be04f16dc

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/m6a0pkabp958n0qjp99cmqr1n4

[download apk](http://filestorage.bluewallet.io:1488/1590782035.apk)

**Comment by ncoelho** [comment]
Can still go back on ln wallet creation and screen just hans on loading after

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n6ykzyz78m4mm0fjzx62t818x0

[download apk](http://filestorage.bluewallet.io:1488/1590782649.apk)

**Pull request merged**
