### PR TITLE
REF: new wallets now generate 12 words mnemonic seed instead of 24, s…

### LINKED ISSUE #2122: Switch to 12 word mnemonics by default?

### PR DESCRIPTION
**Pull request by Overtorment**
…ame security, but easier to manage (closes #2122)

### CODE REVIEW

**Comment by Overtorment** [comment]
@limpbrains we now request  16 bytes of entropy instead of 32, **but not for a case of provideEntropy**. I didnt test, but I was afraid that something might break there if there will be only 16 bytes of entropy. plus, if we keep 256 bits there (24 words) theres less chance user will shoot himself in the foot.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ajy3epe7hd6x91jpywqdfdmudw

[download apk](http://filestorage.bluewallet.io:1488/1605195409.apk)

**Comment by limpbrains** [comment]
@Overtorment ok, it can be useful if you still want 24 words.

**Review by limpbrains — APPROVED** [review]

**Review by marcosrdz — APPROVED** [review]

**Comment by Overtorment** [comment]
@junderw can you pls quickly glance and give your blessing?

**Review by junderw — APPROVED** [review]
It lowers wordcount to 12.

utACK

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
