### PR TITLE
ref-storage-in-realm-db

### PR DESCRIPTION
**Pull request by Overtorment**
I researched on all available databases for RN and chose realm for now, because its not sql-based (its document oriented) and built in encryption

so I rewrote storing data, and heavy data is now offloaded to realm, so we are not encrypting megabytes of data in JS process, it is offloaded to native realm process where it is encrypted and then flushed to disk
so, wallet with 1k txs taking 10MB now works very well, our saveToDisk() procedure takes 1sec max
we call saveToDisk every time some data changed, like, if we fetched new txs from electrum
bad news: realm here is used in a goofy way. because realm requires strict schema definition, and we have very complex internal representation of transactions (tree-like) and it differs from wallet type to wallet type
so heavy transaction data is serialized and placed in realm, and then read back during cold boot, like some key-value nosql. so all transactions are stored in RAM during runtime (as before). cool realm features like lazy load are not used. OTOT, there is no faster storage than RAM in runtime unless you need querying (which we dont)
so Id say we are good untill we enounter some beast who has 10k+ transactions in a wallet. then we will have to re-evaluate, and who knows, maybe it wil still perform decent
so Im gona test this build for a while to see if there are issues
note: basic wallet data & secrets are still stored in keystore (which will survive if ios app deleted/reinstalled), but realm keeps its stuff in files in app documents dir. so if anything happens - wallets will survive, they will just have empty transactions, which is solved with plain pull-to-refresh

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j7p6qh60yy19m2344g53zjg89g

[download apk](http://filestorage.bluewallet.io:1488/1598523078.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/a6421pr4bm544zg90hxaw7w094

[download apk](http://filestorage.bluewallet.io:1488/1598538326.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pp0dendt1er8ttmnxr4r9t0kk0

[download apk](http://filestorage.bluewallet.io:1488/1598615842.apk)

**Review by limpbrains — APPROVED** [review]
Look like you are open/close realm db each time you call `saveToDisk` 
Would it be faster to open realm db on app start and close on app close ?

**Comment by Overtorment** [comment]
> Look like you are open/close realm db each time you call `saveToDisk`
> Would it be faster to open realm db on app start and close on app close ?

docs say `Remember to use the close() method on opened realms when you are done with them.` and `Remember to close the realm when finished`.

how do you even catch app close if app can be killed by iOS when its out of memory, or user can kill the app manually

**Comment by marcosrdz** [comment]
> > Look like you are open/close realm db each time you call `saveToDisk`
> 
> > Would it be faster to open realm db on app start and close on app close ?
> 
> 
> 
> docs say `Remember to use the close() method on opened realms when you are done with them.` and `Remember to close the realm when finished`.
> 
> 
> 
> how do you even catch app close if app can be killed by iOS when its out of memory, or user can kill the app manually

This would require Native code

**Comment by limpbrains** [comment]
Ok!

**Pull request merged**
