### PR TITLE
feat: add Northern Luri language

### PR DESCRIPTION
**Pull request by limpbrains**
sync other language files

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vv5wat6cezjhsg3vqc74zm2azm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/679)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mgrswzwnwqkmgkhteex34ijiha?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/680)

**Comment by marcosrdz** [comment]
It says its still a draft. Should i still review?

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nmzqcgegxj74zh73apd6hpmykm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/688)

**Review by hosseinabaspanah — CHANGES_REQUESTED** [review]
The Latin name is Northern Luri, not Northern Lori

Edit if possible...

The rest of the items are correct, only the name of the language should be changed from Northern Lori to Northern Luri...

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Comment by limpbrains** [comment]
> It says its still a draft. Should i still review?

@marcosrdz now it is 100% ready

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Review by marcosrdz — APPROVED** [review]

**Comment by limpbrains** [comment]
@marcosrdz merge it

**Pull request merged**
