### PR TITLE
REF: Hooks TX Details

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3xddy95xz9carmrhynd4c2mz0w?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8161)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bf5r0w2ep9y9aw22avxcv19qu4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8162)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/v5qdakc940mx3cqx5t540k1ntm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8164)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1mvk8rq9604aedp3u4z6pyd5h4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8168)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xw6hvurphvqx6dfy153d2pmyqg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8174)

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
