### PR TITLE
ADD: Expand Alert component to add custom title

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yyr3eqnewsrmgpw3k3sjy3wkde?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/394)

**Review by Overtorment — CHANGES_REQUESTED** [review]
E2E failed

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jezgnpatnhqdusr3cghgjt7xza?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/409)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — CHANGES_REQUESTED** [review]
a good example of  'weeks of coding can save you hours of planning':

* dont rename `alert` to `presentAlert`
* dont change func signature, instead add second optional  parameter `title`
*  diff reduces from 47 files to 1 file, easy to read, line ownership in `git blame` is not hijacked
* ...
* profit!


embrace it and become a 10x engineer you were born to be

**Comment by marcosrdz** [comment]
> a good example of  'weeks of coding can save you hours of planning':
> 
> 
> 
> * dont rename `alert` to `presentAlert`
> 
> * dont change func signature, instead add second optional  parameter `title`
> 
> *  diff reduces from 47 files to 1 file, easy to read, line ownership in `git blame` is not hijacked
> 
> * ...
> 
> * profit!
> 
> 
> 
> 
> 
> embrace it and become a 10x engineer you were born to be

I disagree with some points. Some files have both a message and a title, using this approach makes the autocomplete suggestions work far better and u can skip a title without having to pass a value. 

I changed alert to presentAlert to avoid conflicts with the JS alert.

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Review by limpbrains — APPROVED** [review]
LGTM

**Review by Overtorment — APPROVED** [review]
ok, LGTM.
fix conflicts and LFG!

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rcqax4dk32rzx42vdbhfjsloiq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/462)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
