### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by Overtorment** [comment]
`$APPCENTER_OUTPUT_DIRECTORY/BlueWallet.ipa`

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/9pye2f7u7j55h49vcbc3fky4jg

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/3t4cjyq9636qvy4473byegp4br

**Comment by GladosBlueWallet** [comment]
🎶This was a triumph🎶. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/yt360zk3ye2qjhyzqua6k6uea8

[APK] http://filestorage.bluewallet.io:1488/1576539952.apk

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xcv6m7d2xv70amrfea2hkxr92r

[download apk](http://filestorage.bluewallet.io:1488/1577143992.apk)

**Pull request merged**
