### PR TITLE
FIX: PSBT with HW wallets flow (closes #1822)

### LINKED ISSUE #1822: PSBT flow - import transaction
Importing transaction from send screen to keep the PSBT sending flow, brings the user back to the send screen without any populated data.

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2tg9pjckhu22648pq4ur4fkhdr

[download apk](http://filestorage.bluewallet.io:1488/1600278789.apk)

**Comment by Overtorment** [comment]
@marcosrdz can you take a look? opening signed PSBT file on ios does nothing, while om android it works ok 
(if you have imported transaction, i.e. transaction signing is in progress)

tried to open from dropbox and files (build in ios)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5ye8jn2qmvg1bbteu3kzb3z7hc

[download apk](http://filestorage.bluewallet.io:1488/1600319677.apk)

**Comment by Overtorment** [comment]
@ncoelho @marcosrdz will merge after your blessing

**Review by ncoelho — APPROVED** [review]

**Comment by ncoelho** [comment]
Tested, worked

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/506v0qdmag20nedkhrzxc2d6c4

[download apk](http://filestorage.bluewallet.io:1488/1600359479.apk)

**Comment by stepansnigirev** [comment]
Tested with Specter-DIY, works with both animated and static QR codes.

**Review by marcosrdz — APPROVED** [review]

**Pull request merged**
