### PR TITLE
ADD: Script to quickly test deeplinks locally

### PR DESCRIPTION
**Pull request by marcosrdz**
Screenshot 2024-11-05 at 3 27 48 PM

makes the debugging / manual test process much faster 

## Summary by CodeRabbit

- **New Features**
	- Introduced a script for sending deep links to iOS simulators and Android emulators, enhancing user interaction with Bitcoin and Lightning Network links.
	- Added a user-friendly selection interface for choosing deep links and devices, improving the overall experience.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
nice, good thinking!
btw do we have e2e tests for deeplinks? i think we had some...
makes sense to expand on those

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
