### PR TITLE
FIX: Widgets do not work any longer on iOS and macOS #7380

### PR DESCRIPTION
**Pull request by marcosrdz**
## Release Notes

- **New Features**
	- Enhanced localization support for market widget functionalities.
	- Introduced a new `HostManager` for managing network hosts and retry logic.

- **Improvements**
	- Updated deployment target for the WidgetsExtension to support newer iOS features.
	- Refactored market data fetching methods to utilize Swift's async/await syntax for improved readability and error handling.
	- Added retry mechanisms for fetching market data in widgets.

- **Bug Fixes**
	- Improved error handling and logging for network connections.

- **Chores**
	- Minor updates to code structure and organization for better maintainability.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
