### PR TITLE
FIX: allow user to choose wallet type when importing empty WIF

### LINKED ISSUE #4559: Allow user to choose address format when importing WIF
If wallet has no money it will be imported as legacy. We need give user an option to choose wallet type in this case. Or in the case when funds found on different address types

### PR DESCRIPTION
**Pull request by limpbrains**
closes #4559

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/k3bqv1566ny02a67uu8h1evj0w?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9694)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Review by Overtorment — APPROVED** [review]

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
