### PR TITLE
FIX: upgrade eslint and related packages

### PR DESCRIPTION
**Pull request by limpbrains**
WIP. Waiting for eslint-config-standard with eslint 8 support

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qc4qt3whd9vcq2557bj09pj86c?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9271)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zz6uq1e7jgnrzpnm0b34058urg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9331)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/y8wuh0gb39gb4x5ajkzb8xtubr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9332)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2f0vvej3hnv20rqwu7wryxptvw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9504)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ejc2zwg6xuja7wmkh3bgbe6qe8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9695)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/m724u1t45r9u61gw11vua02tk4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9696)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4uj34tuy77r5ke23zp447m51f4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9697)

**Comment by Overtorment** [comment]
still WIP?

**Comment by limpbrains** [comment]
Yes, eslint-config-standard has not been released yet

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qfgcvxgd0j32m267765emx1hd4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9866)

**Comment by limpbrains** [comment]
waiting for:
- eslint-plugin-react-native
- eslint-config-standard-react

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wrujbwy18mctcxxnwv0yk5qnp8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9867)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pjxhk4dmn6yatifufwzfbi2hha?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10182)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xpt77cu3psxdtp4ohrlv4hdoqa?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10183)

**Comment by Overtorment** [comment]
@limpbrains still WIP?

**Comment by limpbrains** [comment]
> @limpbrains still WIP?

still waiting for:
- eslint-plugin-react-native
- eslint-config-standard-react

I can replace them with github links, but I don't know how reliable that would be

**Comment by Overtorment** [comment]
whats the issue? fixes for those are in their master branches, but not cut to releases and not released to npm..?

**Comment by limpbrains** [comment]
Exectly

**Comment by limpbrains** [comment]
Now it is ready!

**Comment by Overtorment** [comment]
nice! ill fix android build in master first

**Comment by Overtorment** [comment]
poured fresh master

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zuhxeks2dud75iypmwfio67iha?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10694)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Comment by limpbrains** [comment]
Awesome!

**Pull request merged**
