### PR TITLE
REF: Moved AddressInput tooltips to types

### PR DESCRIPTION
**Pull request by marcosrdz**
## Release Notes

- **New Features**
  - Enhanced address validation with haptic feedback in the Address Input component.
  - Streamlined privacy settings in the Settings Privacy component for improved user experience.
  - Introduction of new tooltip actions for better functionality in various components.

- **Bug Fixes**
  - Resolved issues with action handling in the Send Details component.

- **Localization Updates**
  - Updated terminology across multiple languages for clarity, particularly changing "Show in Block Explorer" to "View in Browser."

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — CHANGES_REQUESTED** [review]
conflicts.
also, 50 files changed?? i fukken tired of diffs this large

**Comment by marcosrdz** [comment]
> conflicts. also, 50 files changed?? i fukken tired of diffs this large

Vast majority is loc key change since the word translation is very different from its original key

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
