### PR TITLE
Fiatinpt

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1w5bqph8bb916ey2u1jta8u4n8

[download apk](http://filestorage.bluewallet.io:1488/1590433438.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bb4ju55e6uj02fqzjvhj2f02qc

[download apk](http://filestorage.bluewallet.io:1488/1590434920.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vx3znrb26fwm3g6g4acmprpv5g

[download apk](http://filestorage.bluewallet.io:1488/1590461338.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vjhvku8w0efp8hu86r23pvnkd4

[download apk](http://filestorage.bluewallet.io:1488/1590529167.apk)

**Comment by Overtorment** [comment]
is it ready for review? because travis tests fail because testID was lost
`testID={'BitcoinAmountInput'}`

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/md9r6bptkhbrjpuq26fz0nwv48

[download apk](http://filestorage.bluewallet.io:1488/1590973411.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u18k1fwrx3p9gqrb0pkjzutpcg

[download apk](http://filestorage.bluewallet.io:1488/1590984182.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wh4xaakvx231eed095uax3vdzc

[download apk](http://filestorage.bluewallet.io:1488/1591021382.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jhyg6vhfudna5q4bawgm33dgkw

[download apk](http://filestorage.bluewallet.io:1488/1591046484.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/erbq93983papr8vbb9wj06czw0

[download apk](http://filestorage.bluewallet.io:1488/1591056915.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/aztxjv0q20havr715u123g9kec

[download apk](http://filestorage.bluewallet.io:1488/1591058486.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pe72t6xfa520c62zxwrr7y0x7c

[download apk](http://filestorage.bluewallet.io:1488/1591072284.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pry5kh4nrtjcgjfzc4px8726g4

[download apk](http://filestorage.bluewallet.io:1488/1591100449.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/h3drvv80v1cckaqg090n2ucb88

[download apk](http://filestorage.bluewallet.io:1488/1591111798.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2nhj13jt58a8pde8ak4ev2khy0

[download apk](http://filestorage.bluewallet.io:1488/1591119387.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/b0a4m00h80cq051vye95c0acxc

[download apk](http://filestorage.bluewallet.io:1488/1591189483.apk)

**Comment by Overtorment** [comment]
closing in favor of https://github.com/BlueWallet/BlueWallet/pull/1190

**Pull request closed without merging**
