### PR TITLE
FIX: wallets are not refreshing when app boots; FIX: wallets are not …

### PR DESCRIPTION
**Pull request by Overtorment**
…refreshing when they are navigated to

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3m33cz1uruv21356kt72vcbay0

[download apk](http://filestorage.bluewallet.io:1488/1605281468.apk)

**Review by limpbrains — APPROVED** [review]
I wanted to do the same, but only for wallets with positive balance and 0 transactions - imported wallets

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Comment by Overtorment** [comment]
> ♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫
> 
> [android in browser] https://appetize.io/app/3m33cz1uruv21356kt72vcbay0
> 
> [download apk](http://filestorage.bluewallet.io:1488/1605281468.apk)

we had refetch logic, its just it was removed with contextify refactoring.

**Pull request merged**
