### PR TITLE
REF: currency rates loader, add LPB new rate source

### LINKED ISSUE #2245: Lebanese Pound - LBP API
The true LBP rate per 1 USD dollar is represented by "buy":

The price of 1 BTC in LBP would be ,  1 BTC = USD x LBP at the buy price.

https://fluus.me/wp-json/wcra/v1/lbprates/?secret_key=scQEXwNnL9d4tDrViepAWdZeqcx7WuQw

### PR DESCRIPTION
**Pull request by limpbrains**
- refactored rates loader, now each source has its own function with loads and validates data. Much easier.
- Lebanese Pound alternative source added as discussed in #2245

closes #2245

### CODE REVIEW

**Comment by marcosrdz** [comment]
Swift code for Widget needs to be updated

**Comment by limpbrains** [comment]
> Swift code for Widget needs to be updated

NOOOOOOoooooo

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/72nn71rc5e2n7np7n5p4mq0wbr

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-rates-1616773182.apk)

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/08k8hy608m4q5b1jpxuqk4b6nc

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-rates-1617031922.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/470g8tb6mpufpnq3f8tzyjz85w

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-rates-1617034001.apk)

**Comment by limpbrains** [comment]
@marcosrdz 
- widgets updated
- new currencies ANG and AWG
- decoding time updated for Yadio source fixed

please, review again

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n6p032mk05yeqjv38ajyntcznm

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-rates-1617036148.apk)

**Comment by limpbrains** [comment]
@pointbiz Is it correct representation of these currencies?
ANG - NAf. 100 000
AWG - Afl. 100 000

**Comment by pointbiz** [comment]
> @pointbiz Is it correct representation of these currencies?
> ANG - NAf. 100 000
> AWG - Afl. 100 000
One hundred thousand and one cent.
ANG - f 100.000,01
AWG - f 100.000,01

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9uk88mr3t5yu3wnhr95wr8k86g

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-rates-1617074734.apk)

**Comment by limpbrains** [comment]
> > @pointbiz Is it correct representation of these currencies?
> > ANG - NAf. 100 000
> > AWG - Afl. 100 000
> 
> One hundred thousand and one cent.
> ANG - f 100.000,01
> AWG - f 100.000,01
> 
> I called the central bank of Curacao. They said there's no correct format. That in English people use the American format and in Dutch people use the European format.
> 
> So, I'm suggesting the European format be used.

We are using system locales to render amount in local currencies. 
For ANG it's `en-SX` locale and amount is rendered as `NAf. 100,000.63`
For AWG it's `nl-AW` locale and amount is rendered as `Afl. 100.000,63`

🤷‍♂️

I can't force using of `f` as a currency symbol.

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Comment by pointbiz** [comment]
@marcosrdz 
@Overtorment 
Please post your donation addresses. I'd like to thank you.

**Comment by marcosrdz** [comment]
This refactor was done by @limpbrains

**Comment by marcosrdz** [comment]
bc1qvsgl36e985j82lxpvam2nw8xeq8pu2wq8eeryu

Thank you!

**Pull request merged**
