### PR TITLE
bad master fingerprint from coldcard - 00000000 #4641

### LINKED ISSUE #4641: bad master fingerprint from coldcard - 00000000
## Are you reporting a bug?

* M1 Macbook Air 2020 macOS Monterey 12.3.1 (21E258)
* Version 6.2.18 (701)
* OK
* userId:6C2C2A7D-E918-567D-A9D1-2687D42717C5

Coldcard firmware: 4.1.3

When importing electrum wallet json file from coldcard I get an invalid master fingerprint. importing the same json file to electrum client does work without any changes.

### PR DESCRIPTION
**Pull request by raytorres280**
fixes #4641 in event that root_fingerprint is a hex value. does reverse of what Number().toString() does by using parseInt() with radix.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by raytorres280** [comment]
do I need to fix something?

**Comment by raytorres280** [comment]
I made a mistake can you delete the branch and pr and I will reopen?

**Pull request closed without merging**
