### PR TITLE
OPS: upgrade android emu ver on CI for detox e2e

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/BlueWallet/issues/1436

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zh9xuc901pcugc72hxkrhptwtm

[download apk](http://filestorage.bluewallet.io:1488/1600948039.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6ykbgzgc2f191ym5ptfv261ht4

[download apk](http://filestorage.bluewallet.io:1488/1600958838.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pfqxmy4x1fjevw170h84kctgn8

[download apk](http://filestorage.bluewallet.io:1488/1600988567.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/v6jk7k50hw4rqmcj64486tmxcm

[download apk](http://filestorage.bluewallet.io:1488/1601036702.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xb5jarbce0x7xt43p2kyzyk594

[download apk](http://filestorage.bluewallet.io:1488/1601039687.apk)

**Comment by Overtorment** [comment]
fail. cant update it to 30 or 29

**Pull request closed without merging**
