### PR TITLE
 feat: offline import 

### LINKED ISSUE #7099: Cannot Import Secret/Private Key in Offline Mode
## Cannot Import Secret/Private Key in Offline Mode

* Samsung Galaxy A03 Core | Android 11
* 7.0.4 (build 1726095882)
* cannot run self tests in offline device with offline electrum mode on
* userId: 95c8730fcecbe9b6

Hey there, im currently trying to import a BIP 84 SK with 24 keys + passphrase, generated using IanColeman in a Offline notebook. But when I tried to import the "Account Extended Private Key" or a single SK from any Public Address in the offline Mobile device it throws the following error:

blue-wallet-issue (2)
blue-wallet-issue (1)

If you guys need any more information, just tell me! tysm

### PR DESCRIPTION
**Pull request by limpbrains**
Do not try to fetch txs and balances if BW is in Offline mode

closes #7099

https://github.com/user-attachments/assets/2430cc9c-9d26-4d9e-ad73-8980debd5c6a

## Release Notes

- **New Features**
	- Enhanced wallet import functionality to support offline mode.
	- Added user notification for offline mode limitations during wallet verification.
	- Improved flexibility in the wallet import process by allowing additional contextual data.
	- Introduced a new `handleSave` function for better wallet saving logic.

- **Bug Fixes**
	- Updated error handling to prevent application crashes when closing undefined clients.

- **Documentation**
	- Added new strings for user notifications regarding offline mode.

- **Style**
	- Improved code readability and maintainability through refactoring and type safety enhancements.

- **Tests**
	- Expanded test coverage for wallet import scenarios, including offline mode handling.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
bueno

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
