### PR TITLE
FIX: Unit wasnt defaulting to BTC

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ndgaypcmhwqh14pb7pnm4jguk4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8134)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/uhayfkwktuekq7cegvnap545g8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8135)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dxkgjta61zpg56emg9ndgk8wrc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8136)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
