### PR TITLE
FIX: Do not attempt to connect unless app is unlocked

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by Overtorment** [comment]
Do tests on it, my hunch is that in regular scenario, there will be no difference

**Comment by marcosrdz** [comment]
> Do tests on it, my hunch is that in regular scenario, there will be no difference

For some reason connect would do some UI hangups due to RN being single thread. moving it to past unlock instead of cold start removes this slight hangup. especially when using orbot

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fbg5heemjqetoyhlniouodwq6m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/754)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by Overtorment** [comment]
ok im convinced. good thing its only couple of lines change, should be easy to reverse if anything

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Comment by Overtorment** [comment]
weird that android build failed tho

**Pull request merged**
