### PR TITLE
FIX: Crash when try to import a wallet on mac version #7369

### PR DESCRIPTION
**Pull request by marcosrdz**
## Summary by CodeRabbit

- **New Features**
	- Enhanced screenshot restrictions based on the platform, ensuring mobile users face restrictions while desktop users do not.
  
- **Bug Fixes**
	- Improved handling of screenshot permissions to prevent unnecessary restrictions on desktop environments.

- **Documentation**
	- Added import statements for platform detection in multiple components to support conditional logic. 

- **Refactor**
	- Updated components to utilize the `isDesktop` variable for better control over platform-specific behavior.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
