### PR TITLE
FIX: bugsnag connection at startup #5688

### PR DESCRIPTION
**Pull request by marcosrdz**
iOS implemented. Android is WIP

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4n7ifs3l5zs2c3ar45w7xb6kle?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11686)

**Review by Overtorment — CHANGES_REQUESTED** [review]
weird. i thought i already fixed it o_O.
anyway, i think its easier to implement on js side. basically, dont fire `Bugsnag.start` untill we know that there is not  optOut flag is set

**Comment by Overtorment** [comment]
also, deepscan had a valid objection

**Comment by marcosrdz** [comment]
> weird. i thought i already fixed it o_O.
> 
> anyway, i think its easier to implement on js side. basically, dont fire `Bugsnag.start` untill we know that there is not  optOut flag is set
> 
> 
> 
> 
> 
> 

The native one is needed for startup crashes. JS side wouldnt catch those

**Comment by Overtorment** [comment]
i didnt get that.
im saying that its possible to opt out of bugsnag without  touching native code.

we already catch all the crashes we need ok.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x5ifppslls63y3nmwjm7mlklu4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11702)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ldtmkpfxgjumcrj27eqbs67vgm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11704)

**Comment by marcosrdz** [comment]
> i didnt get that.
> 
> im saying that its possible to opt out of bugsnag without  touching native code.
> 
> 
> 
> we already catch all the crashes we need ok.

If u look at appdelegate.mm and mainapplication.java ull see that bugsnag still starts regardless of optout. This implementation keeps the launch crash logs and also respects the value of do not track. We'd lose launch crash logs if we remove the native code.

**Comment by Overtorment** [comment]
trying js-only way here: https://github.com/BlueWallet/BlueWallet/pull/5921

**Pull request closed without merging**
