### PR TITLE
fix: SLIP39 1-of-1

### LINKED ISSUE #6417: SLIP39: Single threshold schemes not importing
## Are you reporting a bug?

Importing 1 of x SLIP39 shares fails. Shards generated from https://iancoleman.io/slip39/

1of1
```
object recover academic academic bedroom predator grief goat carbon dictate repair suitable pile kidney clogs shame receiver cluster sweater mild
```
1of2
```
column isolate academic easy august speak knit rhythm havoc junior civil aide shelter depict scholar item plan iris luck axis

column isolate away easy august speak knit rhythm havoc junior civil aide shelter depict scholar item plan grocery party order
```
1of3
```
viral extend academic leader center else mobile recall deliver justice revenue false exercise veteran style vegan glance timely enemy steady

viral extend away leader center else mobile recall deliver justice revenue false exercise veteran style vegan glance voice glen finance

viral extend category leader center else mobile recall deliver justice revenue false exercise veteran style vegan glance scandal artwork romp
```

Whereas 2of3, 3of3, 2of4, 3of4, 4of4 shards can successfully import.

Please provide:
### Mobile
* Asus Zenfone 8, Android 13
* BlueWallet app version 6.6.2

### Desktop 
* macOS, 13.6.5
* Version 6.6.2 (1703119050)

### PR DESCRIPTION
**Pull request by limpbrains**
closes #6417

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/33ralw36l7vyamun62rzvtz55i?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1804)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5yjhftglplkmj34bp3gu47nyse?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1805)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7gxlxzdtopkfv2z3mmhztdjn54?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1845)

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
