### PR TITLE
FIX: Tx list with elements upgrade

### PR DESCRIPTION
**Pull request by ncoelho**
To-do:

- [x] Remove Chevron
- [x] Icon to text space should be 8px
- [x] Icons are misaligned
- [ ] Amount doesn't fit the column
- [ ] Description is not being truncated

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ca3bppk1d4v2yfcjyvdq5bdhy4

[download apk](http://filestorage.bluewallet.io:1488/1588788532.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/613v046gbr32yu175y7kra9ncm

[download apk](http://filestorage.bluewallet.io:1488/1588789496.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qbm4k50r8nqb7jkwv0hd9hkkuc

[download apk](http://filestorage.bluewallet.io:1488/1588791395.apk)

**Comment by ncoelho** [comment]
Will check the other problems on a different PR

**Pull request merged**
