### PR TITLE
DEL: Artificial Splash delay

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/oznu3z4bqel3tg6dygibilrb54?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1585)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/i2bw3jotxlrruyrsw77kdgfofq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1586)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/477lfiqk5gjef7ywr7yncdsmwq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1587)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7q4mx7qymr7deits7t2jgnzgui?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1588)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
