### PR TITLE
Create macoscatalyst.yml

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bn6p3uzezxjq473r3pqef7jd3e?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11861)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/lriobcnkqntrubbjvtdnttgcte?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11862)

**Comment by Overtorment** [comment]
@marcosrdz still wip? getting closer at least, i hope?

**Comment by marcosrdz** [comment]
I learned a lot when doing the iOS counterpart. This will have to be re-created.

**Pull request closed without merging**
