### PR TITLE
Addbatch

### PR DESCRIPTION
**Pull request by marcosrdz**
https://user-images.githubusercontent.com/4793122/134713382-2cd6c8b2-af89-464b-8fdc-5b620154e69a.mp4

### CODE REVIEW

**Comment by Overtorment** [comment]
whats this for?

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/madq0292cdtezk9xweefk3ujjr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8465)

**Comment by marcosrdz** [comment]
> whats this for?

Ive had scenarios where i had multiple qrs i wanted to import for a batch tx without having to go one by one.

**Comment by Overtorment** [comment]
How would this work?

**Comment by marcosrdz** [comment]
forgot to attach the video when I created the PR. updated.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x36y31gtt3ef9a31ehzpmqxjt8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8472)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5qdytuf26eytvuc6ghn3pdg1pc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8503)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by Overtorment** [comment]
im not sold on this feature. i don't want to review & merge a bunch of code that only 2 users will enjoy

**Comment by marcosrdz** [comment]
its a feature enhancement. the processData code will also help with the desktop drag file feature that ill be implementing later.  and handoff when composing a tx and want to pass it over to the desktop.

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2xy1979wgabt4nunamc9h4n6ar?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8603)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/17uhrvhw1nv52kzz0xu345cme0?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8660)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n7gx3yje9mxxw65ha4kuy08mbw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8746)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/d3k77akwyaxqdptbpqd6eqhgtc?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8969)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4vvt9knmmbzg0z3tbvfjkqad0r?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8992)

**Pull request closed without merging**
