### PR TITLE
FIX: Disregarding curent denomination on send screen, scanning addres…

### LINKED ISSUE #2088: Disregarding curent denomination (sat/fiat) on send screen, scanning address always resets it to BTC
1. On sending wallet, tap send
2. On sending wallet, enter amount: 100,000 sats
3. On receiving wallet, tap receive to view QR
4. On sending wallet, tap scan and scan the QR
5. On sending wallet, amount is changed to: 100,000 BTC

Could be nasty!

### PR DESCRIPTION
**Pull request by Overtorment**
…s always resets it to BTC (closes #2088)

@ncoelho requires some testing. I dont remember why it was the way it was. maybe there was a reson for that.
pls test send and batch send

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f7faqxj65gevvkmw9au95r4r5r

[download apk](http://filestorage.bluewallet.io:1488/1606148688.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/24k5wwh1we4d1xemnu2yx1wrem

[download apk](http://filestorage.bluewallet.io:1488/1606175701.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gnja6fazkyb747rt1vavbebnxg

[download apk](http://filestorage.bluewallet.io:1488/1606238850.apk)

**Review by ncoelho — APPROVED** [review]

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
