### PR TITLE
REF: Add debounce in case theres frequent saveToDisk calls (such as c…

### PR DESCRIPTION
**Pull request by marcosrdz**
…hanging unit)

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/birrqghzckknnu3w6fquqklpki?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1931)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm but smth is not right, e2e failed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/adtsnpm2wva7p7jjmvrdeqcntm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1949)

**Comment by Overtorment** [comment]
debounce is not bouncy enough kek

**Comment by marcosrdz** [comment]
Closed. didn't get expected benefits

**Pull request closed without merging**
