### PR TITLE
FIX: Use numberformatter for properly displaying the wallet balance o…

### PR DESCRIPTION
**Pull request by marcosrdz**
…n widget

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/navqqt9pgfyygaztdcey5puyb0

[download apk](http://filestorage.bluewallet.io:1488/1605335820.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z7r4eaxf3xf2q58npnyz77p494

[download apk](http://filestorage.bluewallet.io:1488/1605369733.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rm4m5k68j3zkb9wd8xf80cbj24

[download apk](http://filestorage.bluewallet.io:1488/1605416788.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qv3gkkt4e4aucw1uupn2f3ab74

[download apk](http://filestorage.bluewallet.io:1488/1605458530.apk)

**Review by ncoelho — APPROVED** [review]

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
