### PR TITLE
Feature/broadcast page

### PR DESCRIPTION
**Pull request by dr3am3r**

### CODE REVIEW

**Comment by ncoelho** [comment]
Try to use the same header style we are using. See the view where the feature sits as an example

**Comment by Overtorment** [comment]
`/` in branch name breaks Glados.
here's the appetizer link: https://appetize.io/app/37c893hphpb9eb0ez9u67agz54

**Comment by dr3am3r** [comment]
> Try to use the same header style as the other views. See the view where the feature sits as an example

done

**Comment by Overtorment** [comment]
closed in favor of https://github.com/BlueWallet/BlueWallet/pull/1000

**Pull request closed without merging**
