### PR TITLE
ADD: show frozen amount on send screen, warn in case of send MAX or amount exeeds balance

### LINKED ISSUE #4054: User guidance in case of frozen coins
Users often forget that they have frozen coins. (I at least am such a candidate.)

If someone tries to send the maximum amount with frozen coins, only the unfrozen amount will be sent without prior warning. What remains is a residual balance and a big question mark.

**Message for use Full Balance:** "Are you sure you want to use your wallet's full balance for this transaction?"
**Cheap solution:** "Are you sure you want to use your wallet's full balance for this transaction? 
                                  Please note that frozen coins are excluded."

**If no unfrozen balance is left, this error appears:** "Not enough balance. Try sending smaller amount or decrease the fee"
**Cheap solution:** "Not enough balance. Try sending smaller amount or decrease the fee.  
                                  Please note that frozen coins are excluded."

Of course, it would be better to display this specific text additions only when coins are frozen. Or to display the concrete amount on the send mask instead. (Probably unattractive.)
A more optimal solution would be to permanently show the balance of unfrozen coins exactly only additionally when coins are frozen.

Wallet name (Medium)
0.004576365 (Large)
Not frozen: 0.000263012 (Very small - but balance can also be copied with the right mouse button.)
(Alternative: Available for TX:  0.000263012)

Could this save a few rare but complex tickets? 
I would find it nicer.

### PR DESCRIPTION
**Pull request by limpbrains**
Now you can see frozen amount on a send screen. If you tap on it, Coin control opens.
If you try to send MAX amount and you have frozen coins BW with show 
`Are you sure you want to use your wallet’s full balance for this transaction? Please note that frozen coins are excluded.`
same when amount exceeds balance
`The sending amount exceeds the available balance. Please note that the frozen coins are excluded.`

https://user-images.githubusercontent.com/155891/147222511-0e042bca-541c-4ec4-aacf-9aa1b938c74c.mp4

closes #4054

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kn2qrkvy90c7ev6e2ekbgfg58r?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9270)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/baw88tb75yf9vfhzjc9v9hqjh4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9272)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
