### PR TITLE
ADD: GHS and XAF

### PR DESCRIPTION
**Pull request by marcosrdz**
https://github.com/BlueWallet/BlueWallet/discussions/5221

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cjp7j47n4hm4kjsnmeamr74tim?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1770)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wf43nu3tvbometozamjjyz5w64?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1771)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yodopnig6nwpvbcdoxafchktbq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1779)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
