### PR TITLE
FIX: Can't enter settings on mac version #7368

### PR DESCRIPTION
**Pull request by marcosrdz**
## Release Notes

- **New Features**
	- Added a close button in the Import Wallet screen for easier navigation.
	- Enhanced user notifications with new actions for viewing addresses and transactions in the browser.

- **Improvements**
	- Improved event listener management in the menu actions to prevent memory leaks.
	- Refined user activity handling and menu management for better user interaction.

- **Bug Fixes**
	- Ensured proper cleanup of event listeners to maintain application performance.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
