### PR TITLE
REF: Moved Wallet classes to subfolder and converted filenames to kabob case. Closes #972

### LINKED ISSUE #972: Refactor classes
Wallets go to a separate folder.
Camelcase filenames change to snake case

### PR DESCRIPTION
**Pull request by mgurzenski**

### CODE REVIEW

**Comment by marcosrdz** [comment]
Thank you so much!

**Comment by Overtorment** [comment]
merged here 
https://github.com/BlueWallet/BlueWallet/pull/1146

**Comment by Overtorment** [comment]
thanks!

**Comment by mgurzenski** [comment]
This should close Issue #972, if you want to mark that closed also.

**Pull request merged**
