### PR TITLE
REF: Confirmation view elements alignment

### PR DESCRIPTION
**Pull request by ncoelho**
Aligns the fees and call to action to the bottom of the view.

Confirm | Confirm + payjoin
------------ | -------------
Screenshot 2021-04-21 at 10 45 10 | Screenshot 2021-04-21 at 10 44 20

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/h7q269xxer98ubvbam3qwftkw0

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1618998495.apk)

**Review by Overtorment — APPROVED** [review]
lgtm but tests fail. also linting wouldnt hurt

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/tv6f1h466pb3820m0bd80e44a4

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619019444.apk)

**Comment by marcosrdz** [comment]
E2E fails

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/umwf53f2y3wdtf7ucn8w5hdf7g

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619041790.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bxp0nyzyj6khnyvpm139k2fnnw

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619088310.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/re9j117q6td5ea0d15q14xbxtw

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619095962.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/890c2hjdujwaaa1fmvnzywtgfc

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619101200.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qtyab5krc57c4fkzb01b0r1em8

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619105789.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/av7et752jfpvnh0fze1en64mh4

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619169288.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3qp5uefdcey9wgfbqjcvqz4n9r

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619172299.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/g0ntyqkeb88bjhbuna34580mh4

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619177410.apk)

**Review by Overtorment — CHANGES_REQUESTED** [review]
fix e2e & rebase

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ze3bawby8zmkf440ydknk67h20

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619193168.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ekkwm295g3cvrzyeg69e73cub4

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619214081.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vnz8vx5bjd4y25tmejy7bd8hpg

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619260732.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nr46pp51p73hp4y1texfqc49mw

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619289144.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hkgp0znwcp1103m34w29z2rf28

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619487052.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hj84aty03rjk7y0rcuzauw6f0c

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619526588.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5t48qrvj9tryanevn4qgjn3v8m?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619645757.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7c7bpe8t0fzxugakw31ehfc20m?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619664442.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/83485d888ku1gff7f4c25q99zw?device=pixel4

[download apk](http://filestorage.bluewallet.io:1488/confirmview-1619687565.apk)

**Comment by Overtorment** [comment]
ok i reviewed the changes, and its a lot of changes, some of them quite serious. and you've only wanted to align some elements on the confirmation screen. this makes no sense. and i have no desire to dig deep into that to find out what is broken and why.
I suggest you ask @marcosrdz to do the alignment changes on the confirmation screen, nice and tudy, without touching a lot of code across 4 files.
closed & deleted.

**Pull request closed without merging**
