### PR TITLE
ADD: Use Full Balance and Multiple recipients

### LINKED ISSUE #2305: Use Full Balance and Multiple recipients
Right now it is impossible to use these features together. It should be possible to create a transaction with multiple outputs, one of which will be MAX, where all the remaining funds will be sent. It's like change output but you can define the address.

Without this you can't spend all funds from the wallet with multiple receivers in one transaction.

### PR DESCRIPTION
**Pull request by limpbrains**
closes #2305

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jrzjq6g2cqdau2xkby9byj4zx8

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-send-max-1615394060.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hmenypeyb8dx2b4x5j5z9k8ra0

[download apk](http://filestorage.bluewallet.io:1488/limpbrains-send-max-1615577935.apk)

**Review by Overtorment — APPROVED** [review]
lgtm

**Review by ncoelho — APPROVED** [review]

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
