### PR TITLE
ADD: Password/Passcode/Apple Watch unlock for iOS and macOS

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/by0vuqbj15bzzxwg168cre0djm

[download apk](http://filestorage.bluewallet.io:1488/1599539567.apk)

**Review by Overtorment — CHANGES_REQUESTED** [review]
lots of builds failed

**Comment by marcosrdz** [comment]
> lots of builds failed

fixed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/phma1pajn1zc59h55nw6r8jp6c

[download apk](http://filestorage.bluewallet.io:1488/1599610516.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/99kqwfm642xv449nednb54qzzm

[download apk](http://filestorage.bluewallet.io:1488/1599626218.apk)

**Pull request merged**
