### PR TITLE
OPS: Enable Hermes

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/1dwq361k15wvb3ctjwagwmn7kc

[download apk](http://filestorage.bluewallet.io:1488/1596236630.apk)

**Comment by Overtorment** [comment]
do you need help finding where Intl was disabled?

**Comment by marcosrdz** [comment]
> do you need help finding where Intl was disabled?

That would be awesome

**Comment by Overtorment** [comment]
```
$ git blame app/build.gradle | grep intl
744329ee1 (marcosrdz              2020-03-22 18:51:25 -0400 105)  * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
6e5457240 (Ivan Vershigora        2020-06-03 15:25:38 +0300 112) def jscFlavor = 'org.webkit:android-jsc-intl:+'

```

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vfparmem902r4g2bzkvjbapb10

[download apk](http://filestorage.bluewallet.io:1488/1596591659.apk)

**Comment by Overtorment** [comment]
you forgot to add intl to package.json (see 6e5457240)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/g77qmurztytcykuxz7ua1ebpa0

[download apk](http://filestorage.bluewallet.io:1488/1596857194.apk)

**Comment by Overtorment** [comment]
hodlhodl screen is not crashing, sot thats a win (it used to crash when we tried hermes last time, I assumed that's because my crappy modals usage).
But still, e2e crashes with `com.facebook.react.common.JavascriptException: ReferenceError: Property 'Intl' doesn't exist`. maybe you need to import it in some specific screen..?

**Comment by Overtorment** [comment]
cleanup

**Pull request closed without merging**
