### PR TITLE
FIX: Replace ',' with '.' instead of empty string.

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/v321f22bkxdhb1cbuuk500evc4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7733)

**Review by Overtorment — APPROVED** [review]

**Comment by Overtorment** [comment]
@marcosrdz can you describe what you tried to fix in this PR? for @brettl-03

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @brettl-03] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/brettl-03

**Comment by marcosrdz** [comment]
Currently, users with a keyboard that utilize "," as the decimal separator are unable to send amounts such as "1.05" because they dont have "." available. They only have "," forcing them to do either "1" or "2". This PR allows them to type "1,05" and it'll get replaced by "1.05" allowing them to provide specific decimal amounts.

**Comment by brettl-03** [comment]
Hey guys! So all looks good with the ',' being replaced with '.' when inputted, but I did want to note that there is one area within the app where this change currently isn't having an effect (explained below)

When you enter the "Buy Bitcoin" flow via the button, the comma ',' on the number keypad doesn't input anything/change to a decimal period. I understand this interface and part of the app appears to be provided by "MoonPay", so just wanted to confirm and double-check with you guys first if it's okay and expected that this change doesn't apply to this specific area? (Video showing scenario below)
cc. @marcosrdz @Overtorment 

https://user-images.githubusercontent.com/88056982/129272859-1e4e7cd1-2788-4deb-9cb1-f09278ecc39a.mov

**Comment by brettl-03** [comment]
Also, I see that the two attached issues related to this fix were both from iPhone devices, do we have any emulator to also test with iOS just to confirm it's absolutely fixed there as well, or are we okay with just the Android confirmation?

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @brettl-03] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/brettl-03

**Comment by Overtorment** [comment]
moonpay is actually a webview, and we cant control whats inside, its on their side.

checking android only is fine, in most cases. ios builds are trickier, you're not on our testfligh yet, so lets ignore that for now

**Review by brettl-03 — APPROVED** [review]
Test passes: When a comma ',' is used as an input, it is now being replaced with a period '.'

Tested on Android via Appetize and on my physical OnePlus 6 Android device

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Review by Hg6f9 — COMMENTED** [review]
Subject

**Pull request merged**
