### PR TITLE
Addwalletui

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by Overtorment** [comment]
cc @ncoelho 

image


image



image

**Comment by ncoelho** [comment]
This was already done. It’s on the acinq branch I think :/

**Comment by ncoelho** [comment]
It is looking a bit different from the implementation we worked on...

ezgif com-video-to-gif (4)

**Comment by Overtorment** [comment]
I had to resolve conflicts and lost some styling along the way. Not an issue, important that single-address wallets are hidden from normies

**Comment by Overtorment** [comment]
Acinq branch was split into ui improvements and acinq integration, the way it should be

**Comment by ncoelho** [comment]
Yes, the acinq branch was my confusion.

But we lost all the improvements done overtime on this PR... it come back
to the first iteration?

- We ended up to not put the advanced settings on settings. Because users
don’t have anyway to know what the advanced settings are. So we kept them
locally.
- The styling is important, it matches the wallets cards that we changed
the colors on a previous PR.
- The goal was to remove the segwit and hd references, they are there again.

We can do the changes again later, but at least the styling should be ok,
so it doesn’t look bad

**Comment by Overtorment** [comment]
Address reuse should be hidden as far away as possible from regular users, otherwise it wont pass b org review

**Comment by ncoelho** [comment]
Yes, I’m totally ok with that, can be fixed later.

**Pull request merged**
