### PR TITLE
ADD: Show alert if amount is less or equal 500 sats

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dpe4h4m665afe4608yygth4nbm

[download apk](http://filestorage.bluewallet.io:1488/1610402358.apk)

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/8xcj87ccb531pb89a5zbvzxq5m

[download apk](http://filestorage.bluewallet.io:1488/1610553068.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/puqqgpc0uc5wfva1dbxcvjed7m

[download apk](http://filestorage.bluewallet.io:1488/1610721633.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/f25um0v427cahzjuay3kjc6c60

[download apk](http://filestorage.bluewallet.io:1488/1610729506.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3vdpngmpm222ae5dnjb1mk6r7m

[download apk](http://filestorage.bluewallet.io:1488/1610745351.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9mbvvqkedqu0mq8ynx0zgcrax4

[download apk](http://filestorage.bluewallet.io:1488/lessthan500-1611022197.apk)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Comment by junderw** [comment]
FYI: Anything below 564 won't broadcast, but it's actually calculated based on the min_relay_tx_fee of the node receiving the broadcasted tx... 564 is calculated based on the default value of min_relay_tx_fee, and since min_relay_tx_fee dynamically creeps upward automatically by default when mempool is full, it is entirely possible that a 564 satoshi input which would barely broadcast normally can be rejected for being below the dust limit during times of congestion.

As long as this check isn't something that is being relied upon, I think it's fine... though I would have chosen 564 over 500.

**Pull request merged**
