### PR TITLE
fix: replace require with import

### PR DESCRIPTION
**Pull request by limpbrains**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qp4vkcllgvorqhz57l5zhitr2u?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1133)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/655yro5ojkj45wghyoi2vo7i5i?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1318)

**Review by marcosrdz — APPROVED** [review]

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2muj6a467zvkcmhb3lwgo64e4e?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1350)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
