### PR TITLE
FIX: #3496 Unable to Browse Past First Wallet (Among Other Issues) #3496

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/72u8j1bxd8vwrhau9049ya442r?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7609)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm but e2e failed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x6f023nb4cz1t0zp2e74683md4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/7627)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
