### PR TITLE
FIX: Reorder wallet is clunky to use. #4405

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zp4u0kcq4nu92phtz088gw1c6m?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9442)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/efjf2z8zdwbmqfbxghygjgftcm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9444)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jdzrfh6gg320chzb9dq0ugnkmg?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9446)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n1u48tfd1qfqcw380aab50mt68?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9449)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
