### PR TITLE
REF: Multisig stacks lazy

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/oizqwyz3pa5lawrig46y5kerku?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1548)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/yytcze5xnspnzdgxvyv6yemrpi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1549)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xnck46fzypbvfksmjgebbp5lni?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1550)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
