### PR TITLE
FIX: Apple Watch app not working #5470

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2tpqbwdpdh6ec7ddl3k5alnbim?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11762)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xu5vfxvcz3fy6g6rnnmiwy3ozu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11784)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kcgksuwj6bk6ow6diqml3bfn6u?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11787)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/lebnvx7bh24mlaj76ff4eqyhau?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11792)

**Review by Overtorment — APPROVED** [review]

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
