### PR TITLE
DOC: Update instructions to run the macOS app

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]
Why tests failed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/j2dt743sr3weqcqywknkuhgdgm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/200)

**Comment by marcosrdz** [comment]
> Why tests failed

Forgot we still have one file in there was requires lint ignore

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vzhsie7jwcehq2bkm7h3phumz4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/201)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ddm34n5kr5533wn36m3rdirbym?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/204)

**Pull request merged**
