### PR TITLE
REF: Use defaultSource as its faster for slower devices

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/hvkvtoapeiykeubdezkmh6cm5q?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/10529)

**Comment by Overtorment** [comment]
well, this is how it looks on android (appetize):

image

image

**Review by Overtorment — CHANGES_REQUESTED** [review]
broken on android

**Comment by marcosrdz** [comment]
> broken on android

Odd...ok. Will address

**Pull request closed without merging**
