### PR TITLE
ADD: ACINQ Strike Wallet

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/fmk0megyb5wxcg6zwp4jaywkhg

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/eaxnyqfyfur3akxy55tzpb17t4

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/t66wjdmz2emupx4hxj1hwjw9dr

**Comment by GladosBlueWallet** [comment]
This was a triumph. I'm making a note here: HUGE SUCCESS.

 [android] https://appetize.io/app/q5mzky0j5wg9p47ehb66ayb29c

**Comment by Overtorment** [comment]
cleanup

**Pull request closed without merging**
