### PR TITLE
Add missing accessibility labels

### PR DESCRIPTION
**Pull request by GBKS**
Various buttons around the application are missing accessibility labels. A user who can only interact with the app using a screen reader will not know what the buttons do.

I cannot get the application to build locally, so I cannot test my changes (will try again, but already wasted 2 hours). But I still want to see progress on this task, so I am starting anyways. The changes are really basic, just adding single attributes to elements in various components and screens, so it should not be a huge big issue. I'd appreciate it if someone else could help test.

To find issues, I am testing the app using a screen reader ([here's how I do that](https://www.youtube.com/watch?v=n9FvI5SfpoU&t=21s)), browsing the [old branch](https://github.com/BlueWallet/BlueWallet/issues/4742#issuecomment-1143992450) by @limpbrains, and searching the code.

I am not aiming for 100% with this PR, but I will consider it a success and will open it for review when a good majority of accessibility labels have been added.

Here are some screenshots with examples, with the missing button labels outlined in red (remember that a user will not be able to see the screen at all, they will only know what's in the grey tool tips).

image

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]
LGTM

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Comment by GBKS** [comment]
Thanks for the quick approval, but no rush. I left it intentionally as a draft as I want to keep working on it. I think there are a few more buttons that need labels.

If you have any tips, my local build still fails with the following:
`SwiftEmitModule normal arm64 Emitting\ module\ for\ rn_ldk (in target 'rn-ldk' from project 'Pods')`

`pod update` did not fix it for me.

**Comment by limpbrains** [comment]
On M1 you need to run xcode with roseta enabled
Right click xcode, get info, enable rosetta
I haven't tried it. @marcosrdz can help with it.

**Comment by GBKS** [comment]
Thanks for the tip, that did not work. I tried a bunch of different things, searched online for other fixes, but no luck.

**Review by marcosrdz — APPROVED** [review]

**Comment by marcosrdz** [comment]
LGTM. Thank you!

**Comment by Overtorment** [comment]
i personally develop on android emu.

@marcosrdz can you help @GBKS with running on apple sim?

**Comment by marcosrdz** [comment]
> Thanks for the tip, that did not work. I tried a bunch of different things, searched online for other fixes, but no luck.

@GBKS any chance you can share a screenshot of the build error (after quitting xcode, enabling rosetta on xcode, then reopening and rebuilding)?

**Comment by GBKS** [comment]
Thanks for the tip. I even restarted my computer to ensure that the change is properly applied.

Command line gives me this one:
image

Xcode gives me this one:
image

Thanks for your help.

**Comment by GBKS** [comment]
I pushed a bunch more fixes. This time I used the "[eslint-plugin-react-native-a11y](https://www.npmjs.com/package/eslint-plugin-react-native-a11y)" (via [this recommendation](https://github.com/BlueWallet/BlueWallet/issues/4742#issuecomment-1145975708)) plug-in to identify more problems and went through all the recommendations for buttons.

Sometimes the linter also recommends to add an accessibility hint, but I am not convinced it is always needed (the hint is in addition to the label, to describe what happens when interacting). This might have to be revisited on a case-by-base basis.

I ignored input fields (linter found about 25 issues), since I am not 100% sure about the best way to fix them (do we need label properties, or link to respective text labels on the page, or is the placeholder enough, or based on context, etc) and it might be better to tackle that in a separate PR and keep this one focused on buttons.

Small note about [line 398 in ScanQRCode.js](https://github.com/BlueWallet/BlueWallet/blob/94039fa0049e84d7222053a5320d2e340ce23db0/screen/send/ScanQRCode.js#L398), there's a note that reads `this is an invisible backdoor button`. This button is perfectly visible for people who rely on accessibility tools, it's only invisible for the good-vision crowd. Basically the opposite of the camera feed (and QR code at the moment), where low-vision peeps cannot see it, but the others can.

I still can't build the app, same issues as before. But I'll remove draft status now, as the PR includes a lot of changes now and should cover most simple button fixes. I'd appreciate your reviews, and ideally someone can also build the app and verify hands-on that elements can be properly identified now with the accessibility labels. We have [several videos linked to](https://bitcoin.design/guide/designing-products/accessibility/#usability-testing-resources) in the Bitcoin Design Guide that show how to set up your phone for testing and perform quick tests. It really doesn't take much time at all.

Let me know if I added the localization labels in all the right places. There are also some spots where I used labels from specific categories that may not have been appropriate. I'm happy to get your feedback and implement it.

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by Overtorment** [comment]
full test suite & builds run here: https://github.com/BlueWallet/BlueWallet/pull/5411

**Comment by GBKS** [comment]
Just merged master to resolve the conflict in `list.js`.

**Comment by Overtorment** [comment]
runnint builds & tests here:  https://github.com/BlueWallet/BlueWallet/pull/5424

**Comment by Overtorment** [comment]
looks like all tests in https://github.com/BlueWallet/BlueWallet/pull/5424 passed.
shall we merge?  @GBKS @marcosrdz

**Comment by marcosrdz** [comment]
> looks like all tests in #5424 passed.
> shall we merge? @GBKS @marcosrdz

Yup

**Pull request merged**
