### PR TITLE
OPS: Package

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u3m5672f15k2e66u4nzk7dmwd4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9819)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/02e81ng3gcfdq2rvc3ea95wdd8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9823)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xzbmxhd27wmwk3t23h9xwhd7j4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9841)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/e8mu8zxzc9e2qp5n5r9rarwfcm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9848)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bqrzy5ex6wyamhv0ekx29vvd7g?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/9849)

**Pull request merged**
