### PR TITLE
[Snyk] Upgrade realm from 6.1.4 to 10.1.2

### PR DESCRIPTION
**Pull request by Overtorment**
<h3>Snyk has created this PR to upgrade realm from 6.1.4 to 10.1.2.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

*Warning:* This is a major version upgrade, and may be a breaking change.
- The recommended version is **29 versions** ahead of your current version.
- The recommended version was released **a month ago**, on 2020-12-16.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>realm</b></summary>
    <ul>
      <li>
        <b>10.1.2</b> - <a href="https://snyk.io/redirect/github/realm/realm-js/releases/tag/v10.1.2">2020-12-16</a></br><h3>Enhancements</h3>
<ul>
<li>None.</li>
</ul>
<h3>Fixed</h3>
<ul>
<li>Fixed creating objects and assigning properties of BSON Decimal128 and ObjectId types, when running in React Native Chrome debugging mode. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/3452" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/3452/hovercard">#3452</a> &amp; <a href="https://snyk.io/redirect/github/realm/realm-js/issues/3454" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/3454/hovercard">#3454</a>, since v10.0.0)</li>
<li>Fixed a crash that would happen if the app did a network request after the app got refreshed during development and the Chrome debugging mode was disabled. NOTE: Because of <a href="https://snyk.io/redirect/github/realm/realm-js/issues/3206" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/3206/hovercard">#3206</a> the fix has not been implemented on Android. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/3457" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/3457/hovercard">#3457</a>, since v10.0.2)</li>
</ul>
<h3>Compatibility</h3>
<ul>
<li>MongoDB Realm Cloud.</li>
<li>APIs are backwards compatible with all previous releases of Realm JavaScript in the 10.x.y series.</li>
<li>File format: generates Realms with format v20 (reads and upgrades file format v5 or later for non-synced Realm, upgrades file format v10 for synced Realms).</li>
</ul>
<h3>Internal</h3>
<ul>
<li>CI integration updated to use Xcode 12.</li>
<li>Support for newest version of Object Store.</li>
<li>Push functionality test re-enabled.</li>
</ul>
      </li>
      <li>
        <b>10.1.1</b> - <a href="https://snyk.io/redirect/github/realm/realm-js/releases/tag/v10.1.1">2020-12-11</a></br><h3>Enhancements</h3>
<ul>
<li>None.</li>
</ul>
<h3>Fixed</h3>
<ul>
<li>Integrating changesets from the server would sometimes hit the assertion failure <code>n != realm::npos</code> inside <code>Table::create_object_with_primary_key()</code> (in JS: <code>Realm.create()</code>) when creating an object with a primary key which previously had been used and had incoming links. (<a href="https://snyk.io/redirect/github/realm/realm-core/pull/4180" data-hovercard-type="pull_request" data-hovercard-url="/realm/realm-core/pull/4180/hovercard">realm/realm-core#4180</a>, since v10.0.0)</li>
</ul>
<h3>Compatibility</h3>
<ul>
<li>MongoDB Realm Cloud.</li>
<li>APIs are backwards compatible with all previous releases of Realm JavaScript in the 10.x.y series.</li>
<li>File format: generates Realms with format v20 (reads and upgrades file format v5 or later for non-synced Realm, upgrades file format v10 for synced Realms).</li>
</ul>
      </li>
      <li>
        <b>10.1.0</b> - <a href="https://snyk.io/redirect/github/realm/realm-js/releases/tag/v10.1.0">2020-12-08</a></br><h3>Enhancements</h3>
<ul>
<li>Added support of OpenID Connect credential for the Google authentication provider. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/3383" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/3383/hovercard">#3383</a>)</li>
</ul>
<h3>Fixed</h3>
<ul>
<li>Fixing the construction of Realm instances declararing the schema, when running in the React Native Chrome debugging mode, by removing it. Note: This is not considered a breaking change, since this behaviour was never documented. (<a href="https://snyk.io/redirect/github/realm/realm-js/pull/3442" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/3442/hovercard">#3442</a>, since v10.0.0)</li>
<li>Fixed a bug that would prevent eventual consistency during conflict resolution. Affected clients would experience data divergence and potentially consistency errors as a result if they experienced conflict resolution between cycles of Create-Erase-Create for objects with same primary key.</li>
</ul>
<h3>Compatibility</h3>
<ul>
<li>MongoDB Realm Cloud.</li>
<li>APIs are backwards compatible with all previous releases of Realm JavaScript in the 10.x.y series.</li>
<li>File format: generates Realms with format v20 (reads and upgrades file format v5 or later for non-synced Realm, upgrades file format v10 for synced Realms).</li>
</ul>
<h3>Internal</h3>
<ul>
<li>Upgraded to Realm Sync from v10.1.3 to v10.1.4</li>
<li>The sync client now requires a server that speaks protocol version 2 (Cloud version 20201202 or newer).</li>
</ul>
      </li>
      <li>
        <b>10.0.2</b> - <a href="https://snyk.io/redirect/github/realm/realm-js/releases/tag/v10.0.2">2020-12-05</a></br><h3>Enhancements</h3>
<ul>
<li>None.</li>
</ul>
<h3>Fixed</h3>
<ul>
<li>Fixed an issue in <code>toJSON()</code>, in combination with primaryKeys, where data from another table could be returned. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/3331" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/3331/hovercard">#3331</a>, since v10.0.0)</li>
<li>Fixed an issue in <code>toJSON()</code> where <code>data</code> would output as <code>{}</code>, it now returns the data base64 encoded. (<a href="https://snyk.io/redirect/github/realm/realm-js/pull/3356" data-hovercard-type="pull_request" data-hovercard-url="/realm/realm-js/pull/3356/hovercard">#3356</a>, since v10.0.0)</li>
<li>Fixed a bug where setting <code>shouldCompactOnLaunch</code> would lead to a crash with the error <code>Fatal error in HandleScope::HandleScope</code> (on node.js). (since v1.0.0)</li>
<li>TS: <code>RealmInsertionModel&lt;T&gt;</code> used in <code>realm.create&lt;T&gt;(...)</code> now ignores functions on Class Models. (<a href="https://snyk.io/redirect/github/realm/realm-js/pull/3421" data-hovercard-type="pull_request" data-hovercard-url="/realm/realm-js/pull/3421/hovercard">#3421</a>, since v10.0.0)</li>
<li>Fixing the creation of an RPC session when running in React Native Chrome debugging mode. (<a href="https://snyk.io/redirect/github/realm/realm-js/pull/3411" data-hovercard-type="pull_request" data-hovercard-url="/realm/realm-js/pull/3411/hovercard">#3411</a>, <a href="https://snyk.io/redirect/github/realm/realm-js/issues/3358" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/3358/hovercard">#3358</a>, <a href="https://snyk.io/redirect/github/realm/realm-js/issues/3361" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/3361/hovercard">#3361</a>, since v10.0.0)</li>
<li>Fixed a crash in case insensitive query on indexed string properties when nothing matches. (<a href="https://snyk.io/redirect/github/realm/realm-cocoa/issues/6836" data-hovercard-type="issue" data-hovercard-url="/realm/realm-cocoa/issues/6836/hovercard">realm/realm-cocoa#6836</a>, since v6.0.0)</li>
<li>Fixed a bug where queries for the size of a list of primitive nullable <code>int</code>s returned size + 1. (<a href="https://snyk.io/redirect/github/realm/realm-core/pull/4016" data-hovercard-type="pull_request" data-hovercard-url="/realm/realm-core/pull/4016/hovercard">realm/realm-core#4016</a>, since v6.0.0)</li>
<li>Files upgraded on 32-bit devices could end up being inconsistent resulting in <code>Key not found</code> exception to be thrown. ([<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="652123688" data-permission-text="Title is private" data-url="https://github.com/realm/realm-java/issues/6992" data-hovercard-type="issue" data-hovercard-url="/realm/realm-java/issues/6992/hovercard" href="https://snyk.io/redirect/github/realm/realm-java/issues/6992">realm/realm-java#6992</a>)(https://snyk.io/redirect/github/<a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="652123688" data-permission-text="Title is private" data-url="https://github.com/realm/realm-java/issues/6992" data-hovercard-type="issue" data-hovercard-url="/realm/realm-java/issues/6992/hovercard" href="https://snyk.io/redirect/github/realm/realm-java/issues/6992">realm/realm-java/issues/6992</a>), since v6.0.5)</li>
</ul>
<h3>Compatibility</h3>
<ul>
<li>MongoDB Realm Cloud.</li>
<li>APIs are backwards compatible with all previous releases of Realm JavaScript in the 10.x.y series.</li>
<li>File format: generates Realms with format v20 (reads and upgrades file format v5 or later for non-synced Realm, upgrades file format v10 for synced Realms).</li>
</ul>
<h3>Internal</h3>
<ul>
<li>Upgraded to Realm Core from v10.0.0 to v10.1.3</li>
<li>Upgraded to Realm Sync from v10.0.0 to v10.1.3</li>
</ul>
      </li>
      <li>
        <b>10.0.1</b> - <a href="https://snyk.io/redirect/github/realm/realm-js/releases/tag/v10.0.1">2020-10-16</a></br><p>NOTE: Support for syncing with realm.cloud.io and/or Realm Object Server has been replaced with support for syncing with MongoDB Realm Cloud.</p>
<p>NOTE: This version uses the Realm file format to version 20. It is not possible to downgrade to earlier versions than v10.0.0-beta.13. Non-sync Realms will be upgraded automatically. Synced Realms can only be automatically upgraded if created with Realm JavaScript v10.0.0-beta.1 and above.</p>
<h3>Breaking changes</h3>
<ul>
<li>None</li>
</ul>
<h3>Enhancements</h3>
<ul>
<li>None</li>
</ul>
<h3>Fixed</h3>
<ul>
<li>Fixed RN Android error: couldn't find DSO to load: librealmreact.so caused by: dlopen failed: cannot locate symbol. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/3347" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/3347/hovercard">#3347</a>, since v10.0.0)</li>
<li>Fixed TS declaration for <code>app.allUsers</code> to <code>Record&lt;string, User&gt;</code> instead of an array of <code>User</code>. (<a href="https://snyk.io/redirect/github/realm/realm-js/pull/3346" data-hovercard-type="pull_request" data-hovercard-url="/realm/realm-js/pull/3346/hovercard">#3346</a>)</li>
</ul>
<h3>Compatibility</h3>
<ul>
<li>MongoDB Realm Cloud.</li>
<li>APIs are backwards compatible with all previous releases of Realm JavaScript in the 10.x.y series.</li>
<li>File format: generates Realms with format v20 (reads and upgrades file format v5 or later for non-synced Realm, upgrades file format v10 for synced Realms).</li>
</ul>
<h3>Internal</h3>
<ul>
<li>None</li>
</ul>
      </li>
      <li>
        <b>10.0.0</b> - <a href="https://snyk.io/redirect/github/realm/realm-js/releases/tag/v10.0.0">2020-10-14</a></br><p>NOTE: This is a unified release note covering all v10.0.0-alpha.X and v10.0.0-beta.X releases.</p>
<p>NOTE: Support for syncing with realm.cloud.io and/or Realm Object Server has been replaced with support for syncing with MongoDB Realm Cloud.</p>
<p>NOTE: This version uses the Realm file format version 20. It is not possible to downgrade to earlier versions than v10.0.0-beta.13. Non-sync Realms will be upgraded automatically. Synced Realms can only be automatically upgraded if created with Realm JavaScript v10.0.0-beta.1 and above.</p>
<p>NOTE: Deprecated methods have been removed.</p>
<h3>Breaking changes</h3>
<ul>
<li><code>Realm.Sync.User</code> has been replaced by <code>Realm.User</code>.</li>
<li><code>Realm.Sync.Adapter</code>, <code>Realm.Sync.addlistener()</code>, <code>Realm.Sync.localListenerRealms()</code>, <code>Realm.Sync.removeAllListeners()</code> and <code>Realm.Sync.removeListener()</code> have been removed. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/2732" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/2732/hovercard">#2732</a>)</li>
<li>Query-based Sync has been removed. This includes <code>Realm.Sync.Subscription</code>, <code>Realm.Results.subscribe()</code>, <code>Realm.subscriptions()</code>, <code>Realm.unsubscribe()</code>, <code>Realm.privileges()</code>. These APIs are not initially supported by MongoDB Realm. They will be re-introduced in a future release. <code>partitionValue</code> has been added to the <code>sync</code> configuration as a replacement. Please read section <a href="https://docs.mongodb.com/realm/sync/partitioning/" rel="nofollow">"Partition Atlas Data into Realms"</a> in documentation for further information.</li>
<li>Permissions has been removed. You need to configure permissions through MongoDB Realm.</li>
<li>Deprepated API has been removed: <code>Realm.openAsync()</code>, <code>Realm.Sync.setFeatureToken()</code>, <code>Realm.Sync.User.register()</code>, <code>Realm.Sync.User.registerWithProvider()</code>, <code>Realm.Sync.User.authenticate()</code>, <code>Realm.automaticSyncConfiguration()</code>.</li>
<li>Renamed configuration option <code>custom_http_headers</code> to <code>customHttpHeaders</code>.</li>
<li>Renamed <code>Realm.Sync</code> to <code>Realm.App.Sync</code> including all methods and properties.</li>
</ul>
<h3>Enhancements</h3>
<ul>
<li>Added support for compiling on a RaspberryPi. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/2798" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/2798/hovercard">#2798</a></li>
<li>Added support for the <code>Decimal128</code> data type. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/2674" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/2674/hovercard">#2674</a>)</li>
<li>Added support for the <code>ObjectId</code> data type. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/2675" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/2675/hovercard">#2675</a>)</li>
<li>Added support for embedded objects. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/2676" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/2676/hovercard">#2676</a>)</li>
<li>Added <code>Realm.App</code> with the following methods: <code>getApp()</code>, <code>logIn()</code>, <code>switchUser()</code>, and <code>removeUser()</code> and properties <code>id</code>, <code>emailPasswordAuth</code>, <code>currentUser</code>, <code>allUsers</code>. A <code>Realm.App</code> instance represents a <a href="https://docs.mongodb.com/realm/procedures/create-realm-app/" rel="nofollow">MongoDB Realm app</a>. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/2750" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/2750/hovercard">#2750</a> and <a href="https://snyk.io/redirect/github/realm/realm-js/issues/2809" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/2809/hovercard">#2809</a>)</li>
<li>Added <code>Realm.Credentials</code> which represents credentials for MongoDB Realm users. It has the following methods: <code>emailPassword()</code>, <code>facebook</code>, <code>anonymous()</code>, <code>apple()</code>, <code>google()</code>, <code>jwt()</code>, and <code>function()</code>. You must enable the credentials validation (<a href="https://docs.mongodb.com/realm/authentication/providers/" rel="nofollow">authentication providers</a>) at MongoDB Realm before deploying your app. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/2750" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/2750/hovercard">#2750</a> and <a href="https://snyk.io/redirect/github/realm/realm-js/issues/2809" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/2809/hovercard">#2809</a>)</li>
<li>Added auth providers <code>Realm.Auth.EmailPassword</code> and <code>Realm.Auth.APIKeys</code>. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/2750" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/2750/hovercard">#2750</a> and <a href="https://snyk.io/redirect/github/realm/realm-js/issues/2809" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/2809/hovercard">#2809</a>)</li>
<li>Added support for <code>customData</code> readonly property to <code>Realm.User</code> objects. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/2809" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/2809/hovercard">#2809</a>)</li>
<li>Added support for calling server functions from <code>Realm.User</code> objects. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/2809" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/2809/hovercard">#2809</a>)</li>
<li>Added MongoClient and Push functionality to <code>Realm.User</code>.</li>
<li>Added <code>watch()</code> to <code>MongoDBCollection</code> to enable streaming notifications of changes events from the database. Only supported in node.js for now.</li>
<li>TS declarations with stricter TS validation of input-models and return-types for <code>create&lt;T&gt;(...)</code>, <code>objects&lt;T&gt;(...)</code> &amp; <code>objectForPrimaryKey&lt;T&gt;(...)</code>. (<a href="https://snyk.io/redirect/github/realm/realm-js/pull/3044" data-hovercard-type="pull_request" data-hovercard-url="/realm/realm-js/pull/3044/hovercard">#3044</a> &amp; <a href="https://snyk.io/redirect/github/realm/realm-js/pull/3266" data-hovercard-type="pull_request" data-hovercard-url="/realm/realm-js/pull/3266/hovercard">#3266</a>)</li>
</ul>
<h3>Fixed</h3>
<ul>
<li>Realm.login() will not run after hot reloading in RN. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/3236" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/3236/hovercard">#3236</a>, since v10.0.0-beta.12)</li>
</ul>
<h3>Compatibility</h3>
<ul>
<li>MongoDB Realm Cloud.</li>
<li>APIs are backwards compatible with all previous releases of Realm JavaScript in the 10.x.y series.</li>
<li>File format: generates Realms with format v20 (reads and upgrades file format v5 or later for non-synced Realm, upgrades file format v10 for synced Realms).</li>
</ul>
<h3>Internal</h3>
<ul>
<li>Upgraded to Realm Core v10.0.0</li>
<li>Upgraded to Realm Sync v10.0.0</li>
</ul>
      </li>
      <li>
        <b>10.0.0-rc.2</b> - 2020-10-12
      </li>
      <li>
        <b>10.0.0-rc.1</b> - 2020-10-01
      </li>
      <li>
        <b>10.0.0-beta.13</b> - 2020-09-18
      </li>
      <li>
        <b>10.0.0-beta.12</b> - 2020-09-02
      </li>
      <li>
        <b>10.0.0-beta.11</b> - 2020-08-28
      </li>
      <li>
        <b>10.0.0-beta.10</b> - 2020-08-27
      </li>
      <li>
        <b>10.0.0-beta.9</b> - 2020-07-15
      </li>
      <li>
        <b>10.0.0-beta.8</b> - 2020-07-07
      </li>
      <li>
        <b>10.0.0-beta.7</b> - 2020-06-26
      </li>
      <li>
        <b>10.0.0-beta.6</b> - 2020-06-09
      </li>
      <li>
        <b>10.0.0-beta.5</b> - 2020-06-08
      </li>
      <li>
        <b>10.0.0-beta.4</b> - 2020-06-07
      </li>
      <li>
        <b>10.0.0-beta.3</b> - 2020-06-06
      </li>
      <li>
        <b>10.0.0-beta.2</b> - 2020-06-06
      </li>
      <li>
        <b>10.0.0-beta.1</b> - 2020-06-04
      </li>
      <li>
        <b>10.0.0-alpha.11</b> - 2020-06-02
      </li>
      <li>
        <b>10.0.0-alpha.10</b> - 2020-05-30
      </li>
      <li>
        <b>10.0.0-alpha.9</b> - 2020-05-22
      </li>
      <li>
        <b>10.0.0-alpha.8</b> - 2020-05-20
      </li>
      <li>
        <b>10.0.0-alpha.7</b> - 2020-05-19
      </li>
      <li>
        <b>10.0.0-alpha.6</b> - 2020-05-13
      </li>
      <li>
        <b>10.0.0-alpha.5</b> - 2020-05-11
      </li>
      <li>
        <b>6.1.5</b> - <a href="https://snyk.io/redirect/github/realm/realm-js/releases/tag/v6.1.5">2020-11-05</a></br><h3>Enhancements</h3>
<ul>
<li>None.</li>
</ul>
<h3>Fixed</h3>
<ul>
<li>Fixed a bug preventing caching of Realm instances. In certain cases, the Realm file would grow without any new objects added. (<a href="https://snyk.io/redirect/github/realm/realm-js/pull/3322" data-hovercard-type="pull_request" data-hovercard-url="/realm/realm-js/pull/3322/hovercard">#3322</a>, since v6.0.0).</li>
<li>Fixed an issue in <code>toJSON()</code>, in combination with primaryKeys, where data from another table could be returned. (<a href="https://snyk.io/redirect/github/realm/realm-js/issues/3331" data-hovercard-type="issue" data-hovercard-url="/realm/realm-js/issues/3331/hovercard">#3331</a>, since v6.1.0)</li>
<li>Fixed an issue in <code>toJSON()</code> where <code>data</code> would output as <code>{}</code>, it now returns the data base64 encoded. (<a href="https://snyk.io/redirect/github/realm/realm-js/pull/3356" data-hovercard-type="pull_request" data-hovercard-url="/realm/realm-js/pull/3356/hovercard">#3356</a>, since v6.1.0)</li>
<li>Fixed a crash in case insensitive query on indexed string properties when nothing matches. (<a href="https://snyk.io/redirect/github/realm/realm-cocoa/issues/6836" data-hovercard-type="issue" data-hovercard-url="/realm/realm-cocoa/issues/6836/hovercard">realm/realm-cocoa#6836</a>, since v6.0.0)</li>
<li>Fixed a bug where queries for the size of a list of primitive nullable <code>int</code>s returned size + 1. (<a href="https://snyk.io/redirect/github/realm/realm-core/pull/4016" data-hovercard-type="pull_request" data-hovercard-url="/realm/realm-core/pull/4016/hovercard">realm/realm-core#4016</a>, since v6.0.0)</li>
</ul>
<h3>Compatibility</h3>
<ul>
<li>Realm Object Server: 3.23.1 or later.</li>
<li>APIs are backwards compatible with all previous release of Realm JavaScript in the 6.x.y series.</li>
<li>File format: Generates Realms with format v11 (reads and upgrades previous file format).</li>
</ul>
<h3>Internal</h3>
<ul>
<li>Upgraded Realm Core from v6.1.4 to v6.2.0.</li>
<li>Upgraded Realm Sync from v5.0.29 to v5.0.30.</li>
</ul>
      </li>
      <li>
        <b>6.1.4</b> - 2020-10-08
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/realm/realm-js/releases">realm GitHub release notes</a>
  </details>
</details>

<details>
  <summary><b>Commit messages</b></summary>
  </br>
  <details>
    <summary>Package name: <b>realm</b></summary>
    <ul>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/da044f3780915035d13752317b43150908f53dd3">da044f3</a> Merge branch &#x27;master&#x27; of github.com:realm/realm-js</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/69cd4262c77463774d3d5e9e16660b95d496f8e5">69cd426</a> [10.1.2] Bump version</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/3caa407b808b8e65298b9408e2d9bf8cd1eebe91">3caa407</a> [10.1.2] Bump version</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/5fe569c3f0376c16400ea294792f1a9fc69ee4f2">5fe569c</a> Re-enable push test (#3478)</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/c6234c35e0277a9aec483d6e21cfd4fcd669186b">c6234c3</a> Fix debugging synced realms (which uses BSON types) (#3456)</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/858de9c6300c3f69200a35b1f1009aba51c97974">858de9c</a> Update package.json</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/563d8459855bf8c4d7af59135e58dcbead3365bc">563d845</a> Update package.json</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/2474f3571fafe17827c883af744845d149e2b63b">2474f35</a> Enable Xcode 12 support on CI (#3455)</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/c0ebe2f15efcd79d35c2b8168effc418728e03a2">c0ebe2f</a> Fix API doc for User.callFunction(). (#3471)</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/298534036b2137d0805c059430290369d29051c9">2985340</a> Adding changelog template</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/5565a8190070c61ab1e6ee392d88bd353a34f0e4">5565a81</a> [10.1.1] Bump version</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/d19ae037ba56c27e6df3205d9f60bd5f567ea3cc">d19ae03</a> Security audit (#3469)</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/484ac95f51f4a9bbda6f238fb215f0ace5b70e56">484ac95</a> Upgrade to Realm Core v10.1.4 and Realm Sync v10.1.5. (#3468)</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/fab8a7117fa97a2608a802dd35b7ab179c25fedf">fab8a71</a> Making change log entry more accurate.</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/4ae1790b33311a021b06e9d2508e0273a92034af">4ae1790</a> Adding changelog template</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/56d99610b72d72d022ea95843b7335562a8cd06b">56d9961</a> [v10.1.0] Bump version</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/c6617bb3ac9bf6cd07ba45f059b151154343456c">c6617bb</a> Update to Realm Sync v10.1.4 (#3449)</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/474295d43db4cb5fe0c8a0c39e10756fe672f754">474295d</a> Restoring CHANGELOG template</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/8abd7c59bef72fa95ed6bd61e3538bc7c299f797">8abd7c5</a> Renamed google-login test to avoid running it in node</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/5a83b6bb6d2276a5738d5c90f0fde145b547617f">5a83b6b</a> Releasing Realm Web v1.1.0</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/c2bc4f6ec67b768fb28effae4a18c1e45b0aa39a">c2bc4f6</a> Updated the instructions to publish</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/d1f1f28ed07a23a8c0929f617649a4e0dc7207ca">d1f1f28</a> Google OAuth OpenId Connect (#3440)</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/33fc9f05c2b5eff4ff62c7d9842fa04312dcda80">33fc9f0</a> Fixing _expandEmbeddedObjectSchemas must be of type &#x27;function&#x27; (#3446)</li>
      <li><a href="https://snyk.io/redirect/github/realm/realm-js/commit/58c4eb0e1b66a2f9825d07ab158e771b60b901c7">58c4eb0</a> Adding changelog template</li>
    </ul>

   <a href="https://snyk.io/redirect/github/realm/realm-js/compare/41eb5e64441c42b93a3c40c8a72e05a3fcd0580b...da044f3780915035d13752317b43150908f53dd3">Compare</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/bluewallet/project/4d0df22a-0152-410a-8584-6df0d0a596d4?utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/bluewallet/project/4d0df22a-0152-410a-8584-6df0d0a596d4/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/bluewallet/project/4d0df22a-0152-410a-8584-6df0d0a596d4/settings/integration?pkg&#x3D;realm&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/vuchnjxhpu5nd21vf7k0enky4w

[download apk](http://filestorage.bluewallet.io:1488/snyk-upgrade-a7d42e74f6443b83ad817b8016abb7b7-1612073019.apk)

**Comment by marcosrdz** [comment]
Gotta test this one out on macOS

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/t0nhxnxcpmqkv9kpb84uyna6t0

[download apk](http://filestorage.bluewallet.io:1488/snyk-upgrade-a7d42e74f6443b83ad817b8016abb7b7-1612884922.apk)

**Comment by Overtorment** [comment]
why did u approve this pr when you had to close it with explanation because you made the same or with newer version

**Pull request closed without merging**
