### PR TITLE
ADD: Long press Transaction Row to get shortcuts

### PR DESCRIPTION
**Pull request by marcosrdz**
Screen Shot 2021-02-24 at 10 09 04 PM

Tap and hold transaction row to have the option to:
copy amount, txid, note, expand note(number of lines), open in block explorer.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5bh918mk6t8r001n7am4bzb0yr

[download apk](http://filestorage.bluewallet.io:1488/tooltipadd-1614225475.apk)

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/76autdpm88a7x6xy0ckqm5c2am

[download apk](http://filestorage.bluewallet.io:1488/tooltipadd-1614238201.apk)

**Review by ncoelho — APPROVED** [review]

**Comment by mcsaeid** [comment]
I had been thinking about this exact feature for a few days, and I wanted to suggest it but thought to wait because of all the open issues and threads. I felt the need for this when every time I wanted to use the transaction amount, I had to write it manually instead of being able to copy it.

Amazing job, @marcosrdz.

Here are what I think makes sense to include, from left to right:
Copy Amount | Copy Transaction ID | Copy Transaction Link (Too many “copy”s, right? Read the other suggestion for a workaround)

The thing to note in the above suggestion, I believe, is that if the user wants to open a transaction in a block explorer, they have to go to the details by tapping on the transaction. These shortcuts, with the limited space that they have, could serve the more important and _less accessible_ features, like copying the amount or transaction ID (especially the latter because there is no indication or instruction in the details menu that the user _can_ copy the transaction ID; one would have to know where to look (or press) if you know what I mean).

What would be even more amazing:
Copy Details | Open Transaction in Block Explorer

Copy Details, by itself, would be expandable to have the amount, transaction ID, and transaction link inside.

**Comment by marcosrdz** [comment]
> I had been thinking about this exact feature for a few days, and I wanted to suggest it but thought to wait because of all the open issues and threads. I felt the need for this when every time I wanted to use the transaction amount, I had to write it manually instead of being able to copy it.
> 
> Amazing job, @marcosrdz.
> 
> Here are what I think makes sense to include, from left to right:
> Copy Amount | Copy Transaction ID | Copy Transaction Link (Too many “copy”s, right? Read the other suggestion for a workaround)
> 
> The thing to note in the above suggestion, I believe, is that if the user wants to open a transaction in a block explorer, they have to go to the details by tapping on the transaction. These shortcuts, with the limited space that they have, could serve the more important and _less accessible_ features, like copying the amount or transaction ID (especially the latter because there is no indication or instruction in the details menu that the user _can_ copy the transaction ID; one would have to know where to look (or press) if you know what I mean).
> 
> What would be even more amazing:
> Copy Details | Open Transaction in Block Explorer
> 
> Copy Details, by itself, would be expandable to have the amount, transaction ID, and transaction link inside.

The reason i kept them separate is for those who use another app to keep track of their bitcoin portfolio such as Crypto Pro. Having a single "Copy details" would require users to then go to a Notes app and manually remove extra text that doesnt appl to the field they are inserting their data into.

**Comment by mcsaeid** [comment]
I think I need to clarify. What I mean by _expandable_ is that when you click on the button, say, Copy Details, a whole new set of buttons will appear, just like in the two figures below.

Figure (1)

Figure (2)

In the latter, wouldn’t you say having all those buttons there—copy amount, copy transaction ID, copy transaction link, etc.—makes more sense? That is what I meant.

**Comment by marcosrdz** [comment]
> I think I need to clarify. What I mean by _expandable_ is that when you click on the button, say, Copy Details, a whole new set of buttons will appear, just like in the two figures below.
> 
> 
> 
> Figure (1)
> 
> 
> 
> Figure (2)
> 
> 
> 
> In the latter, wouldn’t you say having all those buttons there—copy amount, copy transaction ID, copy transaction link, etc.—makes more sense? That is what I meant.
> 
> 
> 
> The user, then, can copy, for instance, the transaction ID without having the need to use any other app (Notes and such).
> 
> 

Ah I see. That makes a lot of sense. @ncoelho  what do you think?

**Comment by mcsaeid** [comment]
One more thing you should add: Edit Label.

HT @Ziya-Sadr

**Comment by marcosrdz** [comment]
> One more thing you should add: Edit Label.
> 
> 
> 
> HT @Ziya-Sadr

What would "edit label" do?

**Comment by mcsaeid** [comment]
> What would "edit label" do?

Right, I forgot _label_ was an Electrum thing. Label here refers to the description or note (as BlueWallet calls it) that the user assigns to each transaction manually for better privacy/wallet management.

P.S. If you decide to go with Copy Details, here is what is interesting. Once clicked on, it can display the following: Amount | Transaction ID | Transaction Link |  etc. (whatever else makes sense to include) You can omit the word _Copy_. Next to **Copy Details**, you can have, as mentioned, Edit Note, and Open in Block Explorer (because _transaction_ is already being implied).

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x68170y62xumdc7ma760z9hzhr

[download apk](http://filestorage.bluewallet.io:1488/tooltipadd-1614292400.apk)

**Comment by marcosrdz** [comment]
> > What would "edit label" do?
> 
> Right, I forgot _label_ was an Electrum thing. Label here refers to the description or note (as BlueWallet calls it) that the user assigns to each transaction manually for better privacy/wallet management.
> 
> P.S. If you decide to go with Copy Details, here is what is interesting. Once clicked on, it can display the following: Amount | Transaction ID | Transaction Link | etc. (whatever else makes sense to include) You can omit the word _Copy_. Next to **Copy Details**, you can have, as mentioned, Edit Note, and Open in Block Explorer (because _transaction_ is already being implied).

Done.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/btwfw7tqq1g5t9p4u4c1hkch24

[download apk](http://filestorage.bluewallet.io:1488/tooltipadd-1614308158.apk)

**Comment by mcsaeid** [comment]
Perfect. I love it.

There is one small detail missing, in my opinion. When you copy the amount of an outgoing transaction, the minus sign is copied along with it. See the screenshots below.

Negation

On a side note, I am still pro “Copy Details” not only because it is more accurate but also because next to “View in Block Explorer,” it looks small and somewhat unbalanced. That is my personal opinion.

**Comment by mcsaeid** [comment]
I had forgotten about notes. I didn’t see it at first when I long-pressed the transaction; only “Copy” and “View in Block Explorer” appeared, so I thought maybe it was not implemented. Then I saw the new strings on Transifex. So, I went back to take a look.

Fig  1
**Fig. 1.** For more ease of use and accessibility, it would be great to see another action here called “Edit Note.” This is what I had been trying to communicate when mentioning labels and notes yesterday, but I know I could have been more detailed. It has perfect meaning to it. Whether or not you have already written a note, it gives you the ability to either add or edit the transaction note or so-called label.

When I didn’t see it, my initial thought was that you had to enter a note for something to show. So I did. Please see Fig. 2 and 3.

Fig  2
**Fig. 2.** A note has been added.

Fig  3
Fig. 3. Immediately after creating the note, when I long-pressed the transaction, there was a third action called “Expand Note,” which, you know because you created it haha. My point being, 1) It did not expand the note, as you can see the last state of the transaction and the note in the screenshot; 2) It went away, which makes sense because it did its job—expanding the note—but it actually did not.

**Pull request merged**
