### PR TITLE
OPS: Upgrade RN

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rdxgn6bpuh5xf1257jyr0htwx4

[download apk](http://filestorage.bluewallet.io:1488/1606790617.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by ncoelho** [comment]
Screenshot 2020-12-04 at 10 41 49

**Comment by marcosrdz** [comment]
> When opening an invoice
> 
> Screenshot 2020-12-04 at 10 41 49

Did you do an npm i after switching to this branch?

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/037xxmncubyqvxetbn3272ryuw

[download apk](http://filestorage.bluewallet.io:1488/1607093555.apk)

**Comment by ncoelho** [comment]
Tested again, after doing npm i the behaviour of the error changed from on opening the invoice to on closing the invoice. This is happening on unpaid and active invoices. 

Screenshot 2020-12-04 at 16 40 17
Screenshot 2020-12-04 at 16 40 12

**Review by Overtorment — APPROVED** [review]
so, is this red error a dealbreaker? because otherwise lgtm

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/grrcdad3kzrbxkh2nbnvdpbua4

[download apk](http://filestorage.bluewallet.io:1488/1608675163.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5kym020r0zjf1pgfy9m6aqe4br

[download apk](http://filestorage.bluewallet.io:1488/1610554483.apk)

**Comment by ncoelho** [comment]
what is the status of this one?

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
