### PR TITLE
Modal

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
E2E failed

**Comment by marcosrdz** [comment]
@Overtorment  importing ur:crypto-account fails on promise. can you take a look?

**Comment by Overtorment** [comment]
@marcosrdz conflict in scanqr helper

**Comment by marcosrdz** [comment]
> @marcosrdz conflict in scanqr helper
resolved

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
