### PR TITLE
FIX: Handoff was not working on cold start

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/84eyana6cjzmqg5rxg6xt1xazw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8507)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/etmaufx4gyrpruwtb82vcy768r?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8510)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ejr92b8nnycxt094cda9txf9dr?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8512)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/n7npe3t5j4gn0m6fhyjpgdk9r8?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8514)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x95d661g8w1pn2hgr3dw07cdbw?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/8515)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
