### PR TITLE
FIX: Please use 8 decimal places for Bitcoin amounts #6009

### PR DESCRIPTION
**Pull request by marcosrdz**
Simulator Screenshot - iPhone 15 - 2024-04-13 at 14 14 09

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/p7yazvl5ao346jl4p2zejv5dsa?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1176)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by limpbrains — CHANGES_REQUESTED** [review]
Tests

**Comment by Overtorment** [comment]
@ncoelho did not bless this. nor did I

**Pull request closed without merging**
