### PR TITLE
FIX: macOS AVCapture crash

### PR DESCRIPTION
**Pull request by marcosrdz**
NSInvalidArgumentException • AVCaptureSession
*** -[AVCaptureSession addInput:] Can't add a nil AVCaptureInput

When camera errored out

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dpcdt376wgks2l4yjrlp4ueg2q?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/816)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ntreqfye36dqi4ikzxh5aw5o4u?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/820)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/t5wdqbcgdf2o3eksnmzmaoiitm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/821)

**Comment by Overtorment** [comment]
still wip @marcosrdz ?

**Pull request closed without merging**
