### PR TITLE
FIX: Clipboard shortcut was broken

### PR DESCRIPTION
**Pull request by marcosrdz**
## Summary by CodeRabbit

- **New Features**
	- Improved URL handling for a more streamlined user experience.
	- Enhanced haptic feedback when processing valid URLs.
	- Added error alerts for failed QR code detection and invalid image URLs.

- **Bug Fixes**
	- Retained error logging for delivered notifications to ensure reliability.

- **Documentation**
	- Clarified functionality regarding clipboard alerts and notification processing.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — CHANGES_REQUESTED** [review]
* bunch of tests broke
* i dont get what is it supposed to fix. what are steps to reproduce?
* i think we have tests for deeplinking/etc, add another testcase there

**Comment by marcosrdz** [comment]
> * bunch of tests broke
> * i dont get what is it supposed to fix. what are steps to reproduce?
> * i think we have tests for deeplinking/etc, add another testcase there

Get a btc address in ur clipboard, then open bw, say yes to paste and then continue..send screen doesnt open

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm

**Pull request merged**
