### PR TITLE
FIX: itemList lost alignment

### PR DESCRIPTION
**Pull request by ncoelho**
Small fix for itemList that lost alignment on the right margin. Did an ugly fix with negative value, I'm assuming the padding/margin is coming from the reactnative element somewhere, dunno.
And single button case on transactions.js was also misaligned.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/w3vmy2mkkerx8dckurc52qzdxr

[download apk](http://filestorage.bluewallet.io:1488/1602611279.apk)

**Comment by limpbrains** [comment]
You can archive the same result by adding `paddingRight: 0` to the containerStyle on line 1624. 
```diff
  const containerStyle = useMemo(
    () => ({
      backgroundColor: 'transparent',
      borderBottomColor: colors.lightBorder,
      paddingTop: 16,
      paddingBottom: 16,
+     paddingRight: 0,
    }),
    [colors.lightBorder],
  );
```

**Comment by ncoelho** [comment]
Thanks, changed!

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/9f9mhw3kqkk9ugwjb64hge7mer

[download apk](http://filestorage.bluewallet.io:1488/1602664703.apk)

**Review by limpbrains — APPROVED** [review]

**Pull request merged**
