### PR TITLE
ADD: General Settings

### PR DESCRIPTION
**Pull request by marcosrdz**
Simulator Screen Shot - iPhone 8 Plus - 2020-03-28 at 22 07 09

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4jx86dgu3jf66n26ttevt1gc4m

[download apk](http://filestorage.bluewallet.io:1488/1585448140.apk)

**Comment by ncoelho** [comment]
Maybe move “on launch” to this general option. Wdyt?

**Comment by marcosrdz** [comment]
> Maybe move “on launch” to this general option. Wdyt?

Done.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/y0pax30111u491wnvhw1f536vg

[download apk](http://filestorage.bluewallet.io:1488/1585500898.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/kadkva39twd694vaqhd1r1nc70

[download apk](http://filestorage.bluewallet.io:1488/1585537118.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3vfdhkkdqcr74r01qg8y5e0uj4

[download apk](http://filestorage.bluewallet.io:1488/1585540224.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u6cky8p7btc85n43xj19vj4ver

[download apk](http://filestorage.bluewallet.io:1488/1585576875.apk)

**Comment by Overtorment** [comment]
@marcosrdz pls fix conflicts

**Comment by marcosrdz** [comment]
> @marcosrdz pls fix conflicts

Done

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mzzp876m5hmdrhbg04rhbj6qbw

[download apk](http://filestorage.bluewallet.io:1488/1585580628.apk)

**Pull request merged**
