### PR TITLE
DEL: PasscodeAuth

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/by9amggj2bcdgxzej3eu3dcbk8

[download apk](http://filestorage.bluewallet.io:1488/PasscodeAuth-1612373241.apk)

**Comment by Overtorment** [comment]
why are we deleting it?

**Comment by marcosrdz** [comment]
> why are we deleting it?

feature was added for the "keep wallets after app uninstall" feature. this feature was recently removed making this package irrelevant

**Comment by Overtorment** [comment]
So, if user completely forgets his password, there is no way to delete keychain? User won't ever be able to use bw again?

**Comment by marcosrdz** [comment]
By deleting the app. Like on Android

**Comment by Overtorment** [comment]
I thought we use this keystore feature that keeps data forever..?

**Pull request closed without merging**
