### PR TITLE
ADD: SSL connection to Widget calls

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/umc3tsrkhcs55xdzpqhnwy6mbi?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1087)

**Review by Overtorment — CHANGES_REQUESTED** [review]
How does it handle self-signed ssl certificates? A lot of electrums have them self signed. In js/rn we have explicit configuration to allow this

**Comment by marcosrdz** [comment]
@Overtorment  Self signed 

Line 55 on swifttcpclient

**Review by marcosrdz — COMMENTED** [review]
Line 55 on swifttcpclient

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
