### PR TITLE
Feature: Typescript support

### PR DESCRIPTION
**Pull request by pajasevi**
This PR adds support for TypeScript. As an example, i rewrote a few simple files.

### CODE REVIEW

**Comment by pajasevi** [comment]
Closes #141

**Comment by Overtorment** [comment]
What the workflow would be like? Do I need to run some compile command after I write some code and want to test it on emulator? Or before bundling for production build?

@marcosrdz your thoughts on this?

**Comment by Overtorment** [comment]
@marcosrdz  ^^^

**Comment by marcosrdz** [comment]
Let's go for it!

**Comment by skv-headless** [comment]
I know it is a long time but do you want to merge this PR? If @pajasevi is busy I can update it

**Comment by Overtorment** [comment]
@skv-headless please do, maybe its time to slowly start rewriting on TS

**Comment by Overtorment** [comment]
ts support added in https://github.com/BlueWallet/BlueWallet/pull/3403

**Pull request closed without merging**
