### PR TITLE
ADD: useDebounce hook

### PR DESCRIPTION
**Pull request by marcosrdz**
IMAGE 2024-05-25 13:22:22

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/2ju4fo6ypow64d7bbq3hs27vce?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1742)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/u5srx3u335ubwt6b7jp4b6aw2q?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1745)

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
