### PR TITLE
REF: Refactor Handoff component

### PR DESCRIPTION
**Pull request by marcosrdz**
Have it use useCallback and TS enum

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ltpyvguk3viefqrcevvpwsffra?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1872)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dfuja6d3mphf3yif24dq2viwmy?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1875)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/eckxlesuhbt6rujfhn2lmcnjqu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1906)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/b2vjvz63rb7obvi7b2qgalgcw4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1909)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
