### PR TITLE
FIX: Scan progress readability

### PR DESCRIPTION
**Pull request by marcosrdz**
Simulator Screen Shot - iPhone 11 Pro - 2020-12-14 at 16 25 36

### CODE REVIEW

**Comment by marcosrdz** [comment]
Background colors uses colors.brandingColor

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/r6nwv3dz3yzcnvaaz3gmwfp3g4

[download apk](http://filestorage.bluewallet.io:1488/1607982384.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/x2c9q3qvk3vyx74t98f8zb0rv4

[download apk](http://filestorage.bluewallet.io:1488/1607987864.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/6uw031trbr1h83afg9wc25jtqg

[download apk](http://filestorage.bluewallet.io:1488/1608330513.apk)

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
