### PR TITLE
REF: Reorganize Swift code as it was a bigger mess

### PR DESCRIPTION
**Pull request by marcosrdz**
Each class, struct and extension is now its own file

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/lfmspk3me66kegdxrg3topzrai?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1179)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xitu6oygufntwolqbbxdtz2tw4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1180)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/nyi7atqplaw2npyeroad2zl2li?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1183)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
