### PR TITLE
FIX: better tx list update when transactions actually changed (rel #5…

### PR DESCRIPTION
**Pull request by Overtorment**
…615)

### CODE REVIEW

**Comment by Overtorment** [comment]
with this fix tx list will definately update if you sent the transaction and returned to tx list screen

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/v2bqb4ayniq3needjladcdepiu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11626)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @marcosrdz] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/marcosrdz

**Review by limpbrains — APPROVED** [review]

**Pull request merged**
