### PR TITLE
Rec

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/wbc5kmzgz6vrtfixl3j7vv7ore?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1923)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/cx7rvttpla6zr3avi6n3qww2dm?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1924)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jnnra7zkrtyllikdq4slnryyqq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1925)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qe7mabtk3rbfuamldbpzdwnyce?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1926)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4t745lsc4nr7g2t4hymb2lebea?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1929)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jkzsasj3abif5patupynfs2eo4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1932)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Review by Overtorment — CHANGES_REQUESTED** [review]
e2e failed

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bk5hoo4t36k3vyzs4ephoyv5aa?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1950)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/rybddt5duc5woj5xmxc6ag4jz4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/1952)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Pull request merged**
