### PR TITLE
FIX: Stack name warning

### PR DESCRIPTION
**Pull request by marcosrdz**
Screenshot 2024-01-01 at 2 16 17 PM

First PR of 2024!

### CODE REVIEW

**Review by Overtorment — APPROVED** [review]

**Comment by Overtorment** [comment]
Happy new year 🥳

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/abdaajtubbestdhmzddtipmrpq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/44)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/ipjcogfybfnz2czvrjy7zt435u?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/45)

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
