### PR TITLE
OPS: Merge TestFlight YMLs

### PR DESCRIPTION
**Pull request by marcosrdz**
No need to have 2 separate YMLs

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/p4qtwvg7v4m7mmf4jnlrludpoe?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/956)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4b4dwvpfizcnmeqsdi7kqidfy4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/957)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/5get2kt4htolsxexaik36gakeu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/970)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/4egb32m5cevyvkop73qu7ongwq?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/973)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
