### PR TITLE
REF: IsItMyAddress to TSX

### PR DESCRIPTION
**Pull request by marcosrdz**
Simulator Screenshot - iPhone 16 Pro Max - 2024-10-12 at 20 28 43

## Summary by CodeRabbit

- **New Features**
	- Introduced a new component for checking Bitcoin address ownership, including address input, validation, and QR code scanning.
- **Changes**
	- Updated the import path for the `IsItMyAddress` component.
	- Modified the `walletID` property in the `ReceiveDetailsRoot` parameter to be optional.
	- Made the `address` property optional in the `IsItMyAddress` parameter structure.
	- Removed the old `IsItMyAddress` component from the project.
	- Enhanced alert functionality with a new parameter for cache management and improved button order based on the platform.
- **Tests**
	- Updated the test suite for the BlueWallet UI to improve wallet management and settings functionality.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
lgtm  but conflicts

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
