### PR TITLE
fix: use SafeAreaView from react-native-safe-area-context

### PR DESCRIPTION
**Pull request by limpbrains**
Replace SafeAreaView from RN with one from `react-native-safe-area-context`, that works fine on Android
Move SafeBlueArea to SafeArea component file

Before and After. Look at the Import button.

### CODE REVIEW

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by marcosrdz** [comment]
@limpbrains  how does it look on iOS? Does it clip the bottom of scroll views?

**Comment by limpbrains** [comment]
I'm not sure what do you mean by this. It should work exactly as default RN SafeAreaView

**Comment by marcosrdz** [comment]
> I'm not sure what do you mean by this. It should work exactly as default RN SafeAreaView

Ok cool. RNSafeView shouldnt be used in scroll views cause content gets clipped under the home screen bar. But i see youre replacing. Cool

**Review by Overtorment — APPROVED** [review]
i dream of a world where we dont need an extra dep just so components wold not break the layout

**Comment by marcosrdz** [comment]
@limpbrains  conflicts

**Comment by Overtorment** [comment]
hmm thats a lot of conflicts

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
