### PR TITLE
ADD: NZD Fiat

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by marcosrdz** [comment]
I’m not a git pro as you can tell. I branched it off acinq’s branch. Stupid me

**Comment by matt-auckland** [comment]
I can make a new PR with just the NZD changes if you don't want to deal with this @marcosrdz (just opened up this repo to make these changes myself actually)

**Comment by Overtorment** [comment]
That would be awesome, will merge NZD asap. Acinq integration requires quite some time to review & test

**Comment by matt-auckland** [comment]
See #301.

**Comment by Overtorment** [comment]
closed because of #301

**Pull request closed without merging**
