### PR TITLE
ADD: Market Price intent

### PR DESCRIPTION
**Pull request by marcosrdz**
This can linked in a shortcut pipeline such as:

If price goes under X: turn home LED lights red

Simulator Screenshot - iPhone 16 Pro Max - 2024-10-27 at 18 11 42
Simulator Screenshot - iPhone 16 Pro Max - 2024-10-27 at 18 05 26
Simulator Screenshot - iPhone 16 Pro Max - 2024-10-27 at 18 03 08
Simulator Screenshot - iPhone 16 Pro Max - 2024-10-27 at 18 03 12

image

## Release Notes

- **New Features**
  - Introduced a new price widget that displays the current Bitcoin market rate.
  - Added app shortcuts for quick access to market rates.
  - Implemented a new `CompactPriceView` for enhanced price display.
  - Added support for various fiat currencies through `FiatUnitEnum`.
  - Enhanced widget functionality with a new `PriceIntent` for retrieving market rates.

- **Improvements**
  - Enhanced localization support with new strings for better user experience.
  - Updated widget architecture for improved performance and maintainability.
  - Refined error handling in data fetching for smoother functionality.
  - Improved date and number formatting utilities for enhanced display options.
  - Updated deployment target to support newer iOS versions.

- **Bug Fixes**
  - Corrected minor formatting issues in the app's configuration files.

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Review by Overtorment — APPROVED** [review]
last new feature im approving before the feature freeze.
i remind you that you dont write any tests, we dont have any qa engineers, and i cant properly read and debug your swift code

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
