### PR TITLE
FIX:  The + in the add-wallet-button is not centered #1898

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/3b0p565mkbrjyr5f05xkd3yq3w

[download apk](http://filestorage.bluewallet.io:1488/1600830661.apk)

**Comment by ncoelho** [comment]
The entire header changed... 

- It is bigger now
- Title font changed, it is bigger now

Try to align the icon, without changing everything

**Comment by marcosrdz** [comment]
> The entire header changed.
> 
>     * Header is bigger now
> 
>     * It is misaligned
> 
>     * Title font changed, it is bigger now
> 
> 
> Try to align the icon, without changing everything.
> Before 	After
>  	

Updated. Header component is part of RN Elements. changes made are to conform to latest API.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/gfdx5e29fna00m35vnupdwauxw

[download apk](http://filestorage.bluewallet.io:1488/1600922390.apk)

**Review by ncoelho — APPROVED** [review]

**Comment by ncoelho** [comment]
Good to go.

Updating the rn elements misconfigured the cell + switcher element, but just a detail that can be fixed later.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/75wfvkezrgzkdvr618w1jn83uw

[download apk](http://filestorage.bluewallet.io:1488/1600983174.apk)

**Review by Overtorment — APPROVED** [review]
lgtm

**Pull request merged**
