### PR TITLE
ADD: Apple Watch Price Complication

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by marcosrdz** [comment]
Simulator Screen Shot - Apple Watch Series 6 - 44mm - 2021-02-08 at 20 39 49

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/mkjxf2pev1hhjdt2nzx743fwh8

[download apk](http://filestorage.bluewallet.io:1488/complicationprice-1612839263.apk)

**Comment by limpbrains** [comment]
I need an Apple Watch to review this

**Comment by marcosrdz** [comment]
> I need an Apple Watch to review this

You can run it in the Simulator with Xcode.

**Comment by limpbrains** [comment]
> > I need an Apple Watch to review this
> 
> You can run it in the Simulator with Xcode.

Ok... Worth trying

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/namm3z77vqyfta0cfnakxrhrcw

[download apk](http://filestorage.bluewallet.io:1488/complicationprice-1612883795.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/049mj14rfne45pz0krmkg1jjfw

[download apk](http://filestorage.bluewallet.io:1488/complicationprice-1612892499.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/dt3f7h3bv91b12x6am00u47m38

[download apk](http://filestorage.bluewallet.io:1488/complicationprice-1612898978.apk)

**Review by limpbrains — APPROVED** [review]
image

Works good!
Blue `$` symbol looks a bit strange. 
Is it USD only ?

**Comment by marcosrdz** [comment]
> image
> 
> Works good!
> Blue `$` symbol looks a bit strange.

Fixed. It now uses default color values

> Is it USD only ?

Nope. All currencies supported by the app. The entitlement has to be updated to support app groups (which is why its only showing USD so far)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/d3uadyznbepn06bvnn6h3t1jhc

[download apk](http://filestorage.bluewallet.io:1488/complicationprice-1613019560.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/xgdec4fjuamv7ny5284t2zheg8

[download apk](http://filestorage.bluewallet.io:1488/complicationprice-1613051759.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/zjmbdbgp8h6k0ev55mngcxzcc4

[download apk](http://filestorage.bluewallet.io:1488/complicationprice-1613101755.apk)

**Review by Overtorment — APPROVED** [review]

**Comment by Overtorment** [comment]
conflicts

**Comment by Overtorment** [comment]
nvm

**Pull request merged**
