### PR TITLE
FIX: QRCode size on large devices

### PR DESCRIPTION
**Pull request by marcosrdz**

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/jguhqrzp4eyxgfpaxzyfqe6vpg

[download apk](http://filestorage.bluewallet.io:1488/qrsize-1612375501.apk)

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/fxhj2bjhaec1cknaxmaywyr88w

[download apk](http://filestorage.bluewallet.io:1488/qrsize-1612441044.apk)

**Review by ncoelho — CHANGES_REQUESTED** [review]
Should be applied to big screens only?

Screenshot 2021-02-04 at 14 07 52

**Review by Overtorment — APPROVED** [review]
lgtm

**Comment by ncoelho** [comment]
> Should be applied to big screens only?
> 
> Screenshot 2021-02-04 at 14 07 52

@marcosrdz wdyt? Seems a bit small on normal screens.

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/df8v4x52g01w5va5g107gj3n9c

[download apk](http://filestorage.bluewallet.io:1488/qrsize-1614223585.apk)

**Review by ncoelho — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
