### PR TITLE
REF: hide bip47 behind backdoor; refactor

### PR DESCRIPTION
**Pull request by Overtorment**
* forked bip47 dep under our org
* refactored a bit to speed it up
* if payment codes are disabled, wallets wont even try to fetch their balance from network

### CODE REVIEW

**Comment by Overtorment** [comment]
cc @ncoelho

**Review by marcosrdz — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/555zewcz5l32muu5mkvngs6jv4?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11051)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @limpbrains] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/limpbrains

**Review by limpbrains — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
