### PR TITLE
FIX: Cleanup the menu when the view is navigating away

### PR DESCRIPTION
**Pull request by marcosrdz**
If u pressed a tx list item really quickly after long press the onPress would trigger both the navigation and menu show which would lead to a crash

### CODE REVIEW

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/bf7w4jlgty2744zh4g6mcymoiu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11040)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/7opmrnaq6tg6t54gwq6mdovxre?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11041)

**Comment by GladosBlueWallet** [comment]
Wake the fuck up samurai, we have PRs to merge

image

[all PRs for @Overtorment] https://github.com/BlueWallet/BlueWallet/pulls/review-requested/Overtorment

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/qifuorzzdus5utrbnzlxg26itu?device=pixel4

[download apk](https://lambda-download-android-build.herokuapp.com/download/11042)

**Review by Overtorment — APPROVED** [review]

**Comment by GladosBlueWallet** [comment]
Unbelievable. You, [subject name here], must be the pride of [subject hometown here]!

**Pull request merged**
