### PR TITLE
FIX: BIP38 import support

### PR DESCRIPTION
**Pull request by Overtorment**

### CODE REVIEW

**Comment by Overtorment** [comment]
IOS should fallback on js implementation, which could take like 10 minutes to decode BIP38 wallet

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/pt4b4hkyd25nmxey9t8ev1t5m8

[download apk](http://filestorage.bluewallet.io:1488/1586271731.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/z8cc3yww6wat15d3d42g5xwrwg

[download apk](http://filestorage.bluewallet.io:1488/1586517848.apk)

**Comment by GladosBlueWallet** [comment]
♫ This was a triumph. I'm making a note here: HUGE SUCCESS ♫

 [android in browser] https://appetize.io/app/g38djjddedkw6h4n6jnt3df2xw

[download apk](http://filestorage.bluewallet.io:1488/1586535393.apk)

**Comment by Overtorment** [comment]
@marcosrdz can you pls take a look again and give your blessing. take a look at native module as well

**Pull request merged**
